# ACER PRODUCTS CATALOG & SEED DATA
# Strictly ordered to match amazon acer accessories .xlsx (1-90)
# Live Amazon India Verified Pricing & Metadata

# ACER MONITORS: 61 Tracked Models strictly ordered 1-61 matching monitors .xlsx
ACER_MONITOR_SEED_PRODUCTS = [
    {   'amazon_link': 'https://www.amazon.in/dp/B082MDD1QZ',
    'asin': 'B082MDD1QZ',
    'base_price': 7299.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/81U3xQrx3LL._SY355_.jpg',
    'model': 'PM161Q B1',
    'mrp': 9999.0,
    'part_no': 'UM.ZP1SS.102',
    'product_group': 'acer_monitors',
    'rating': 4.4,
    'review_count': 294,
    'sort_order': 1,
    'stock_status': 'In Stock',
    'title': 'Acer PM161Q B1 - 15.6" Full HD Portable IPS Monitor (UM.ZP1SS.102)',
    'url_slug': 'acer-pm161q-b1-um-zp1ss-102'},
    {   'amazon_link': 'https://www.amazon.in/dp/B01IK52EAK',
    'asin': 'B01IK52EAK',
    'base_price': 5299.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/61SiWC83dQL._SX355_.jpg',
    'model': 'V176L',
    'mrp': 7499.0,
    'part_no': 'UM.BV6SS.005',
    'product_group': 'acer_monitors',
    'rating': 4.0,
    'review_count': 74,
    'sort_order': 2,
    'stock_status': 'Out of Stock',
    'title': 'Acer V176L - 17" Square SXGA LED Monitor (UM.BV6SS.005)',
    'url_slug': 'acer-v176l-um-bv6ss-005'},
    {   'amazon_link': 'https://www.amazon.in/dp/B07RNLPRF2',
    'asin': 'B07RNLPRF2',
    'base_price': 5299.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/815oR8wjAfL._SY355_.jpg',
    'model': 'V196L',
    'mrp': 7499.0,
    'part_no': 'UM.CV6SS.B03',
    'product_group': 'acer_monitors',
    'rating': 4.0,
    'review_count': 74,
    'sort_order': 3,
    'stock_status': 'Out of Stock',
    'title': 'Acer V196L - 19" Square SXGA LED Monitor (UM.CV6SS.B03)',
    'url_slug': 'acer-v196l-um-cv6ss-b03'},
    {   'amazon_link': 'https://www.amazon.in/dp/B0CCSKTFJF',
    'asin': 'B0CCSKTFJF',
    'base_price': 5769.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/81FWNkMHSZL._SX355_.jpg',
    'model': 'K202Q',
    'mrp': 8000.0,
    'part_no': 'UM.IE0SI.001',
    'product_group': 'acer_monitors',
    'rating': 4.1,
    'review_count': 178,
    'sort_order': 4,
    'stock_status': 'In Stock',
    'title': 'Acer K202Q - 19.5" HD+ LED Monitor (UM.IE0SI.001)',
    'url_slug': 'acer-k202q-um-ie0si-001'},
    {   'amazon_link': 'https://www.amazon.in/dp/B0CCSK23DM',
    'asin': 'B0CCSK23DM',
    'base_price': 6299.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/81xhVyS995L._SX355_.jpg',
    'model': 'SA222Q E',
    'mrp': 8999.0,
    'part_no': 'UM.WS2SI.E01',
    'product_group': 'acer_monitors',
    'rating': 4.3,
    'review_count': 805,
    'sort_order': 5,
    'stock_status': 'Out of Stock',
    'title': 'Acer SA222Q E - 21.5" Full HD IPS Ultra-Slim Monitor (UM.WS2SI.E01)',
    'url_slug': 'acer-sa222q-e-um-ws2si-e01'},
    {   'amazon_link': 'https://www.amazon.in/dp/B0G363W6VL',
    'asin': 'B0G363W6VL',
    'base_price': 5885.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/61hh04cSU+L._SY355_.jpg',
    'model': 'EK220Q J0',
    'mrp': 7699.0,
    'part_no': 'UM.WE0SI.001',
    'product_group': 'acer_monitors',
    'rating': 4.3,
    'review_count': 78,
    'sort_order': 6,
    'stock_status': 'In Stock',
    'title': 'Acer EK220Q J0 - 21.5" Full HD VA Monitor (UM.WE0SI.001)',
    'url_slug': 'acer-ek220q-j0-um-we0si-001'},
    {   'amazon_link': 'https://www.amazon.in/dp/B0BXP3CP9K',
    'asin': 'B0BXP3CP9K',
    'base_price': 6299.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/81xHjVQPwAL._SX355_.jpg',
    'model': 'EK220Q H',
    'mrp': 8999.0,
    'part_no': 'UM.WE0SI.301',
    'product_group': 'acer_monitors',
    'rating': 4.3,
    'review_count': 3406,
    'sort_order': 7,
    'stock_status': 'Out of Stock',
    'title': 'Acer EK220Q H - 21.5" Full HD VA Monitor (UM.WE0SI.301)',
    'url_slug': 'acer-ek220q-h-um-we0si-301'},
    {   'amazon_link': 'https://www.amazon.in/dp/B0CLY9HWHN',
    'asin': 'B0CLY9HWHN',
    'base_price': 6199.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/810Vo6MDf6L._SX355_.jpg',
    'model': 'EK220Q E',
    'mrp': 7599.0,
    'part_no': 'UM.WE0SS.E01',
    'product_group': 'acer_monitors',
    'rating': 4.3,
    'review_count': 1544,
    'sort_order': 8,
    'stock_status': 'In Stock',
    'title': 'Acer EK220Q E - 21.5" Full HD IPS Monitor (UM.WE0SS.E01)',
    'url_slug': 'acer-ek220q-e-um-we0ss-e01'},
    {   'amazon_link': 'https://www.amazon.in/dp/B0GHRQSMLF',
    'asin': 'B0GHRQSMLF',
    'base_price': 7999.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/61JZMfJJxeL._SY355_.jpg',
    'model': 'B227Q D1',
    'mrp': 12999.0,
    'part_no': 'UM.WB7SI.101',
    'product_group': 'acer_monitors',
    'rating': 3.7,
    'review_count': 11,
    'sort_order': 9,
    'stock_status': 'Out of Stock',
    'title': 'Acer B227Q D1 - 21.5" Full HD IPS Ergonomic Monitor with Webcam (UM.WB7SI.101)',
    'url_slug': 'acer-b227q-d1-um-wb7si-101'},
    {   'amazon_link': 'https://www.amazon.in/dp/B09TL1RGM9',
    'asin': 'B09TL1RGM9',
    'base_price': 17899.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/71ccuT-YVHS._SX355_.jpg',
    'model': 'UT222Q',
    'mrp': 33000.0,
    'part_no': 'UM.WW2SI.001',
    'product_group': 'acer_monitors',
    'rating': 4.1,
    'review_count': 97,
    'sort_order': 10,
    'stock_status': 'In Stock',
    'title': 'Acer UT222Q - 21.5" Full HD IPS 10-Point Touch Monitor (UM.WW2SI.001)',
    'url_slug': 'acer-ut222q-um-ww2si-001'},
    {   'amazon_link': 'https://www.amazon.in/dp/B0DZHY5N59',
    'asin': 'B0DZHY5N59',
    'base_price': 10299.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/91YcMJQSQvL._SY355_.jpg',
    'model': 'VG240Y X1',
    'mrp': 12999.0,
    'part_no': 'UM.QV0SS.101',
    'product_group': 'acer_monitors',
    'rating': 4.3,
    'review_count': 438,
    'sort_order': 11,
    'stock_status': 'In Stock',
    'title': 'Acer VG240Y X1 - 23.8" Full HD IPS Nitro Gaming Monitor (UM.QV0SS.101)',
    'url_slug': 'acer-vg240y-x1-um-qv0ss-101'},
    {   'amazon_link': 'https://www.amazon.in/dp/B0FFD2YSBY',
    'asin': 'B0FFD2YSBY',
    'base_price': 6999.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/81K8IpnFcZL._SX355_.jpg',
    'model': 'EK240Y P6',
    'mrp': 8999.0,
    'part_no': 'UM.QE1SS.601',
    'product_group': 'acer_monitors',
    'rating': 4.4,
    'review_count': 979,
    'sort_order': 12,
    'stock_status': 'In Stock',
    'title': 'Acer EK240Y P6 - 23.8" Full HD IPS Monitor (UM.QE1SS.601)',
    'url_slug': 'acer-ek240y-p6-um-qe1ss-601'},
    {   'amazon_link': 'https://www.amazon.in/dp/B0CX1YT2SK',
    'asin': 'B0CX1YT2SK',
    'base_price': 8399.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/81zC7E7pDwL._SY355_.jpg',
    'model': 'SA242Y P1',
    'mrp': 9499.0,
    'part_no': 'UM.QS2SI.101',
    'product_group': 'acer_monitors',
    'rating': 3.9,
    'review_count': 88,
    'sort_order': 13,
    'stock_status': 'Out of Stock',
    'title': 'Acer SA242Y P1 - 23.8" Full HD IPS Ultra-Slim Monitor (UM.QS2SI.101)',
    'url_slug': 'acer-sa242y-p1-um-qs2si-101'},
    {   'amazon_link': 'https://www.amazon.in/dp/B0F671WWMX',
    'asin': 'B0F671WWMX',
    'base_price': 7999.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/71TrMGqp1OL._SX355_.jpg',
    'model': 'SH242Y G',
    'mrp': 11999.0,
    'part_no': 'UM.QS2SS.001',
    'product_group': 'acer_monitors',
    'rating': 4.2,
    'review_count': 31,
    'sort_order': 14,
    'stock_status': 'Out of Stock',
    'title': 'Acer SH242Y G - 23.8" Full HD IPS Ultra-Slim Monitor (UM.QS2SS.001)',
    'url_slug': 'acer-sh242y-g-um-qs2ss-001'},
    {   'amazon_link': 'https://www.amazon.in/dp/B0DWTGH28J',
    'asin': 'B0DWTGH28J',
    'base_price': 14549.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/81X69-Qo6yL._SX355_.jpg',
    'model': 'B247Y D6',
    'mrp': 17999.0,
    'part_no': 'UM.QB7SI.601',
    'product_group': 'acer_monitors',
    'rating': 3.6,
    'review_count': 20,
    'sort_order': 15,
    'stock_status': 'In Stock',
    'title': 'Acer B247Y D6 - 23.8" Full HD IPS Ergonomic Monitor (UM.QB7SI.601)',
    'url_slug': 'acer-b247y-d6-um-qb7si-601'},
    {   'amazon_link': 'https://www.amazon.in/dp/B0CX238HXB',
    'asin': 'B0CX238HXB',
    'base_price': 7899.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/8107UxDxAaL._SX355_.jpg',
    'model': 'RS242Y G',
    'mrp': 12999.0,
    'part_no': 'UM.QR2SS.001',
    'product_group': 'acer_monitors',
    'rating': 4.4,
    'review_count': 64,
    'sort_order': 16,
    'stock_status': 'In Stock',
    'title': 'Acer RS242Y G - 23.8" Full HD IPS Ultra-Thin Monitor (UM.QR2SS.001)',
    'url_slug': 'acer-rs242y-g-um-qr2ss-001'},
    {   'amazon_link': 'https://www.amazon.in/dp/B0GSS5VV5Z',
    'asin': 'B0GSS5VV5Z',
    'base_price': 8599.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/7189bFz7ipL._SY355_.jpg',
    'model': 'RS242YP1',
    'mrp': 10999.0,
    'part_no': 'UM.QR2SI.102',
    'product_group': 'acer_monitors',
    'rating': 4.0,
    'review_count': 25,
    'sort_order': 17,
    'stock_status': 'Out of Stock',
    'title': 'Acer RS242YP1 - 23.8" Full HD IPS Monitor (UM.QR2SI.102)',
    'url_slug': 'acer-rs242yp1-um-qr2si-102'},
    {   'amazon_link': 'https://www.amazon.in/dp/B0GMRZNZDT',
    'asin': 'B0GMRZNZDT',
    'base_price': 22598.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/71r1lO5DpmL._SX355_.jpg',
    'model': 'UT242Y',
    'mrp': 26999.0,
    'part_no': 'UM.QW2SI.001',
    'product_group': 'acer_monitors',
    'rating': 4.1,
    'review_count': 97,
    'sort_order': 18,
    'stock_status': 'In Stock',
    'title': 'Acer UT242Y - 23.8" Full HD Touch Screen Monitor (UM.QW2SI.001)',
    'url_slug': 'acer-ut242y-um-qw2si-001'},
    {   'amazon_link': 'https://www.amazon.in/dp/B0BJDJQ3C2',
    'asin': 'B0BJDJQ3C2',
    'base_price': 7999.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/71Ap6wOc1-L._SX355_.jpg',
    'model': 'RS242Y W',
    'mrp': 11999.0,
    'part_no': 'UM.QR2SI.W01',
    'product_group': 'acer_monitors',
    'rating': 4.0,
    'review_count': 86,
    'sort_order': 19,
    'stock_status': 'Out of Stock',
    'title': 'Acer RS242Y W - 23.8" Smart Full HD IPS White Monitor (UM.QR2SI.W01)',
    'url_slug': 'acer-rs242y-w-um-qr2si-w01'},
    {   'amazon_link': 'https://www.amazon.in/dp/B0839G3FWK',
    'asin': 'B0839G3FWK',
    'base_price': 7549.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/81OhwDq-fwL._SX355_.jpg',
    'model': 'EK251Q P6',
    'mrp': 8999.0,
    'part_no': 'UM.KE1SI.601',
    'product_group': 'acer_monitors',
    'rating': 4.3,
    'review_count': 77,
    'sort_order': 20,
    'stock_status': 'In Stock',
    'title': 'Acer EK251Q P6 - 24.5" Full HD IPS Monitor (UM.KE1SI.601)',
    'url_slug': 'acer-ek251q-p6-um-ke1si-601'},
    {   'amazon_link': 'https://www.amazon.in/dp/B083FQ83WB',
    'asin': 'B083FQ83WB',
    'base_price': 14998.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/61gH+AncjeL._SY355_.jpg',
    'model': 'XB253Q F3',
    'mrp': 19999.0,
    'part_no': 'UM.KX3SS.301',
    'product_group': 'acer_monitors',
    'rating': 4.4,
    'review_count': 64,
    'sort_order': 21,
    'stock_status': 'In Stock',
    'title': 'Predator XB253Q F3 - 24.5" Full HD IPS Gaming Monitor (UM.KX3SS.301)',
    'url_slug': 'acer-xb253q-f3-um-kx3ss-301'},
    {   'amazon_link': 'https://www.amazon.in/dp/B0FBKFH2HY',
    'asin': 'B0FBKFH2HY',
    'base_price': 16499.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/81HjnnLjQ0L._SX355_.jpg',
    'model': 'B277 D6',
    'mrp': 24000.0,
    'part_no': 'UM.HB7SI.601',
    'product_group': 'acer_monitors',
    'rating': 4.0,
    'review_count': 33,
    'sort_order': 22,
    'stock_status': 'In Stock',
    'title': 'Acer B277 D6 - 27" Full HD IPS Ergonomic Monitor (UM.HB7SI.601)',
    'url_slug': 'acer-b277-d6-um-hb7si-601'},
    {   'amazon_link': 'https://www.amazon.in/dp/B0G3Y54BCB',
    'asin': 'B0G3Y54BCB',
    'base_price': 10999.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/71zq9HcZXLL._SY355_.jpg',
    'model': 'B277 G',
    'mrp': 14999.0,
    'part_no': 'UM.HB7SI.G03',
    'product_group': 'acer_monitors',
    'rating': 3.6,
    'review_count': 13,
    'sort_order': 23,
    'stock_status': 'In Stock',
    'title': 'Acer B277 G - 27" Full HD IPS Vero Monitor (UM.HB7SI.G03)',
    'url_slug': 'acer-b277-g-um-hb7si-g03'},
    {   'amazon_link': 'https://www.amazon.in/dp/B083LLNGPJ',
    'asin': 'B083LLNGPJ',
    'base_price': 14999.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/61N5fCeppmL._SY355_.jpg',
    'model': 'B277U GB',
    'mrp': 29999.0,
    'part_no': 'UM.HB7SI.B01',
    'product_group': 'acer_monitors',
    'rating': 4.6,
    'review_count': 30,
    'sort_order': 24,
    'stock_status': 'In Stock',
    'title': 'Acer B277U GB - 27" WQHD 2K IPS Monitor (UM.HB7SI.B01)',
    'url_slug': 'acer-b277u-gb-um-hb7si-b01'},
    {   'amazon_link': 'https://www.amazon.in/dp/B0GS2M3YKB',
    'asin': 'B0GS2M3YKB',
    'base_price': 17999.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/81NF0RBCoiL._SX355_.jpg',
    'model': 'B277U G',
    'mrp': 24999.0,
    'part_no': 'UM.HB7SI.G02',
    'product_group': 'acer_monitors',
    'rating': 4.3,
    'review_count': 10,
    'sort_order': 25,
    'stock_status': 'Out of Stock',
    'title': 'Acer B277U G - 27" WQHD 2K IPS Monitor (UM.HB7SI.G02)',
    'url_slug': 'acer-b277u-g-um-hb7si-g02'},
    {   'amazon_link': 'https://www.amazon.in/dp/B0BRK8JVD7',
    'asin': 'B0BRK8JVD7',
    'base_price': 19999.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/712iu65c4tL._SX355_.jpg',
    'model': 'B277U D6',
    'mrp': 23999.0,
    'part_no': 'UM.HB7SI.602',
    'product_group': 'acer_monitors',
    'rating': 4.3,
    'review_count': 3,
    'sort_order': 26,
    'stock_status': 'Out of Stock',
    'title': 'Acer B277U D6 - 27" WQHD 2K IPS Ergonomic Monitor (UM.HB7SI.602)',
    'url_slug': 'acer-b277u-d6-um-hb7si-602'},
    {   'amazon_link': 'https://www.amazon.in/dp/B0BRK899TH',
    'asin': 'B0BRK899TH',
    'base_price': 18698.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/81JuXQVR9xL._SX355_.jpg',
    'model': 'CB272U D6',
    'mrp': 21999.0,
    'part_no': 'UM.HB2SI.601',
    'product_group': 'acer_monitors',
    'rating': 4.0,
    'review_count': 5,
    'sort_order': 27,
    'stock_status': 'In Stock',
    'title': 'Acer CB272U D6 - 27" WQHD 2K IPS Monitor (UM.HB2SI.601)',
    'url_slug': 'acer-cb272u-d6-um-hb2si-601'},
    {   'amazon_link': 'https://www.amazon.in/dp/B0D4QLXLBH',
    'asin': 'B0D4QLXLBH',
    'base_price': 19999.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/716cWivRkQL._SX355_.jpg',
    'model': 'CB272K',
    'mrp': 25999.0,
    'part_no': 'UM.HB2SI.002',
    'product_group': 'acer_monitors',
    'rating': 4.2,
    'review_count': 129,
    'sort_order': 28,
    'stock_status': 'In Stock',
    'title': 'Acer CB272K - 27" 4K UHD IPS Monitor (UM.HB2SI.002)',
    'url_slug': 'acer-cb272k-um-hb2si-002'},
    {   'amazon_link': 'https://www.amazon.in/dp/B0G64CRWVL',
    'asin': 'B0G64CRWVL',
    'base_price': 17999.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/81Y38lFq9ZL._SX355_.jpg',
    'model': 'CB272K L2',
    'mrp': 24999.0,
    'part_no': 'UM.HB2SI.201',
    'product_group': 'acer_monitors',
    'rating': 4.4,
    'review_count': 31,
    'sort_order': 29,
    'stock_status': 'Out of Stock',
    'title': 'Acer CB272K L2 - 27" 4K UHD IPS Vero Monitor (UM.HB2SI.201)',
    'url_slug': 'acer-cb272k-l2-um-hb2si-201'},
    {   'amazon_link': 'https://www.amazon.in/dp/B0BFB4GZ4J',
    'asin': 'B0BFB4GZ4J',
    'base_price': 17999.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/7123z3uKcWL._SX355_.jpg',
    'model': 'CB272K-C',
    'mrp': 24999.0,
    'part_no': 'UM.HB2SI.003',
    'product_group': 'acer_monitors',
    'rating': 4.2,
    'review_count': 51,
    'sort_order': 30,
    'stock_status': 'Out of Stock',
    'title': 'Acer CB272K-C - 27" 4K UHD IPS Monitor (UM.HB2SI.003)',
    'url_slug': 'acer-cb272k-c-um-hb2si-003'},
    {   'amazon_link': 'https://www.amazon.in/dp/B0DYCXHGRR',
    'asin': 'B0DYCXHGRR',
    'base_price': 17999.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/81wT+365aWL._SX355_.jpg',
    'model': 'SA272U G',
    'mrp': 24999.0,
    'part_no': 'UM.HS2SS.002',
    'product_group': 'acer_monitors',
    'rating': 4.4,
    'review_count': 155,
    'sort_order': 31,
    'stock_status': 'Out of Stock',
    'title': 'Acer SA272U G - 27" WQHD 2K IPS Monitor (UM.HS2SS.002)',
    'url_slug': 'acer-sa272u-g-um-hs2ss-002'},
    {   'amazon_link': 'https://www.amazon.in/dp/B0FGXN53SS',
    'asin': 'B0FGXN53SS',
    'base_price': 9699.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/81zC7E7pDwL._SY355_.jpg',
    'model': 'SA272 P1',
    'mrp': 11999.0,
    'part_no': 'UM.HS2SI.101',
    'product_group': 'acer_monitors',
    'rating': 4.4,
    'review_count': 196,
    'sort_order': 32,
    'stock_status': 'In Stock',
    'title': 'Acer SA272 P1 - 27" Full HD IPS Ultra-Slim Monitor (UM.HS2SI.101)',
    'url_slug': 'acer-sa272-p1-um-hs2si-101'},
    {   'amazon_link': 'https://www.amazon.in/dp/B0CVXMWHP2',
    'asin': 'B0CVXMWHP2',
    'base_price': 10999.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/71P4CVs96bL._SY355_.jpg',
    'model': 'RS272 G',
    'mrp': 15999.0,
    'part_no': 'UM.HR2SS.001',
    'product_group': 'acer_monitors',
    'rating': 4.4,
    'review_count': 291,
    'sort_order': 33,
    'stock_status': 'Out of Stock',
    'title': 'Acer RS272 G - 27" Full HD IPS Ultra-Thin Monitor (UM.HR2SS.001)',
    'url_slug': 'acer-rs272-g-um-hr2ss-001'},
    {   'amazon_link': 'https://www.amazon.in/dp/B0GSS7M67C',
    'asin': 'B0GSS7M67C',
    'base_price': 10599.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/71Zs+JJzi6L._SY355_.jpg',
    'model': 'RS272 P1',
    'mrp': 12999.0,
    'part_no': 'UM.HR2SI.101',
    'product_group': 'acer_monitors',
    'rating': 4.0,
    'review_count': 25,
    'sort_order': 34,
    'stock_status': 'Out of Stock',
    'title': 'Acer RS272 P1 - 27" Full HD IPS Monitor (UM.HR2SI.101)',
    'url_slug': 'acer-rs272-p1-um-hr2si-101'},
    {   'amazon_link': 'https://www.amazon.in/dp/B0DZHXSXP4',
    'asin': 'B0DZHXSXP4',
    'base_price': 11589.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/81pvtaRKELL._SX355_.jpg',
    'model': 'VG270 X1',
    'mrp': 14599.0,
    'part_no': 'UM.HV0SS.101',
    'product_group': 'acer_monitors',
    'rating': 4.3,
    'review_count': 438,
    'sort_order': 35,
    'stock_status': 'In Stock',
    'title': 'Acer VG270 X1 - 27" Full HD IPS Nitro Gaming Monitor (UM.HV0SS.101)',
    'url_slug': 'acer-vg270-x1-um-hv0ss-101'},
    {   'amazon_link': 'https://www.amazon.in/dp/B083BV3Z1D',
    'asin': 'B083BV3Z1D',
    'base_price': 17999.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/816E2HRfkgL._SY355_.jpg',
    'model': 'KG271 X1',
    'mrp': 24999.0,
    'part_no': 'UM.HX1SI.101',
    'product_group': 'acer_monitors',
    'rating': 4.3,
    'review_count': 209,
    'sort_order': 36,
    'stock_status': 'Out of Stock',
    'title': 'Acer KG271 X1 - 27" Full HD IPS Nitro Gaming Monitor (UM.HX1SI.101)',
    'url_slug': 'acer-kg271-x1-um-hx1si-101'},
    {   'amazon_link': 'https://www.amazon.in/dp/B09R1QVPQL',
    'asin': 'B09R1QVPQL',
    'base_price': 11999.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/81NwUyECc6L._SY355_.jpg',
    'model': 'ED270 X0',
    'mrp': 14999.0,
    'part_no': 'UM.HE0SI.001',
    'product_group': 'acer_monitors',
    'rating': 4.2,
    'review_count': 48,
    'sort_order': 37,
    'stock_status': 'In Stock',
    'title': 'Acer ED270 X0 - 27" Full HD 1500R Curved Gaming Monitor (UM.HE0SI.001)',
    'url_slug': 'acer-ed270-x0-um-he0si-001'},
    {   'amazon_link': 'https://www.amazon.in/dp/B0DM2PMQWR',
    'asin': 'B0DM2PMQWR',
    'base_price': 13899.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/81HGFaYjhFL._SY355_.jpg',
    'model': 'ED270 Z',
    'mrp': 15999.0,
    'part_no': 'UM.HE0SI.Z01',
    'product_group': 'acer_monitors',
    'rating': 4.4,
    'review_count': 90,
    'sort_order': 38,
    'stock_status': 'In Stock',
    'title': 'Acer ED270 Z - 27" Full HD 1500R Curved Monitor (UM.HE0SI.Z01)',
    'url_slug': 'acer-ed270-z-um-he0si-z01'},
    {   'amazon_link': 'https://www.amazon.in/dp/B0FF37F5XR',
    'asin': 'B0FF37F5XR',
    'base_price': 9599.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/814IB8Xc7iL._SY355_.jpg',
    'model': 'KA270 P6',
    'mrp': 11999.0,
    'part_no': 'UM.HX2SS.601',
    'product_group': 'acer_monitors',
    'rating': 4.4,
    'review_count': 979,
    'sort_order': 39,
    'stock_status': 'Out of Stock',
    'title': 'Acer KA270 P6 - 27" Full HD IPS Monitor (UM.HX2SS.601)',
    'url_slug': 'acer-ka270-p6-um-hx2ss-601'},
    {   'amazon_link': 'https://www.amazon.in/dp/B0BJDHXWT2',
    'asin': 'B0BJDHXWT2',
    'base_price': 10999.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/71Ap6wOc1-L._SX355_.jpg',
    'model': 'RS272 W',
    'mrp': 15999.0,
    'part_no': 'UM.HR2SI.W01',
    'product_group': 'acer_monitors',
    'rating': 4.3,
    'review_count': 192,
    'sort_order': 40,
    'stock_status': 'Out of Stock',
    'title': 'Acer RS272 W - 27" Smart Full HD IPS White Monitor (UM.HR2SI.W01)',
    'url_slug': 'acer-rs272-w-um-hr2si-w01'},
    {   'amazon_link': 'https://www.amazon.in/dp/B083BVT37J',
    'asin': 'B083BVT37J',
    'base_price': 14999.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/81Zpm+JvTyL._SX355_.jpg',
    'model': 'VG270U X1',
    'mrp': 18999.0,
    'part_no': 'UM.HV0SI.101',
    'product_group': 'acer_monitors',
    'rating': 4.2,
    'review_count': 80,
    'sort_order': 41,
    'stock_status': 'In Stock',
    'title': 'Acer VG270U X1 - 27" WQHD 2K IPS Nitro Gaming Monitor (UM.HV0SI.101)',
    'url_slug': 'acer-vg270u-x1-um-hv0si-101'},
    {   'amazon_link': 'https://www.amazon.in/dp/B083BVXY36',
    'asin': 'B083BVXY36',
    'base_price': 15999.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/81oAY1EIruL._SY355_.jpg',
    'model': 'XV272U X1',
    'mrp': 25999.0,
    'part_no': 'UM.HX2SI.101',
    'product_group': 'acer_monitors',
    'rating': 4.1,
    'review_count': 95,
    'sort_order': 42,
    'stock_status': 'In Stock',
    'title': 'Acer XV272U X1 - 27" WQHD 2K IPS Nitro Gaming Monitor (UM.HX2SI.101)',
    'url_slug': 'acer-xv272u-x1-um-hx2si-101'},
    {   'amazon_link': 'https://www.amazon.in/dp/B0D3VF2LTF',
    'asin': 'B0D3VF2LTF',
    'base_price': 21599.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/718ToVLGo8L._SX355_.jpg',
    'model': 'XV272U F3',
    'mrp': 31999.0,
    'part_no': 'UM.HX2SI.303',
    'product_group': 'acer_monitors',
    'rating': 4.3,
    'review_count': 144,
    'sort_order': 43,
    'stock_status': 'In Stock',
    'title': 'Acer XV272U F3 - 27" WQHD 2K IPS Nitro Gaming Monitor (UM.HX2SI.303)',
    'url_slug': 'acer-xv272u-f3-um-hx2si-303'},
    {   'amazon_link': 'https://www.amazon.in/dp/B0BVLP8ZQ1',
    'asin': 'B0BVLP8ZQ1',
    'base_price': 37999.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/71MjMUgrHTL._SX355_.jpg',
    'model': 'XV275K P5',
    'mrp': 52999.0,
    'part_no': 'UM.HX5SI.501',
    'product_group': 'acer_monitors',
    'rating': 4.3,
    'review_count': 49,
    'sort_order': 44,
    'stock_status': 'Out of Stock',
    'title': 'Acer XV275K P5 - 27" 4K UHD IPS Nitro Gaming Monitor (UM.HX5SI.501)',
    'url_slug': 'acer-xv275k-p5-um-hx5si-501'},
    {   'amazon_link': 'https://www.amazon.in/dp/B0BDDP5XWC',
    'asin': 'B0BDDP5XWC',
    'base_price': 26799.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/71v5nv5UYdL._SX355_.jpg',
    'model': 'GA271U',
    'mrp': 32999.0,
    'part_no': 'UM.HG1SI.P01',
    'product_group': 'acer_monitors',
    'rating': 4.0,
    'review_count': 72,
    'sort_order': 45,
    'stock_status': 'In Stock',
    'title': 'Acer GA271U - 27" WQHD 2K IPS Gaming Monitor (UM.HG1SI.P01)',
    'url_slug': 'acer-ga271u-um-hg1si-p01'},
    {   'amazon_link': 'https://www.amazon.in/dp/B08334VFQQ',
    'asin': 'B08334VFQQ',
    'base_price': 25399.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/71XQ2fudNML._SY355_.jpg',
    'model': 'UT272',
    'mrp': 32999.0,
    'part_no': 'UM.HW2SI.001',
    'product_group': 'acer_monitors',
    'rating': 4.1,
    'review_count': 97,
    'sort_order': 46,
    'stock_status': 'In Stock',
    'title': 'Acer UT272 - 27" Full HD Touch Screen Monitor (UM.HW2SI.001)',
    'url_slug': 'acer-ut272-um-hw2si-001'},
    {   'amazon_link': 'https://www.amazon.in/dp/B09RPJL6NL',
    'asin': 'B09RPJL6NL',
    'base_price': 16999.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/71G-neJQYRL._SX355_.jpg',
    'model': 'XZ306CX',
    'mrp': 35000.0,
    'part_no': 'UM.RX6SI.X02',
    'product_group': 'acer_monitors',
    'rating': 4.3,
    'review_count': 780,
    'sort_order': 47,
    'stock_status': 'In Stock',
    'title': 'Acer XZ306CX - 29.5" Ultrawide 21:9 Curved Gaming Monitor (UM.RX6SI.X02)',
    'url_slug': 'acer-xz306cx-um-rx6si-x02'},
    {   'amazon_link': 'https://www.amazon.in/dp/B07FRQC89V',
    'asin': 'B07FRQC89V',
    'base_price': 12995.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/7125bziGjHL._SX355_.jpg',
    'model': 'EB321HQ',
    'mrp': 23000.0,
    'part_no': 'UM.JE1SI.A02',
    'product_group': 'acer_monitors',
    'rating': 4.1,
    'review_count': 932,
    'sort_order': 48,
    'stock_status': 'In Stock',
    'title': 'Acer EB321HQ - 31.5" Full HD IPS Monitor (UM.JE1SI.A02)',
    'url_slug': 'acer-eb321hq-um-je1si-a02'},
    {   'amazon_link': 'https://www.amazon.in/dp/B09JZF3YX4',
    'asin': 'B09JZF3YX4',
    'base_price': 16999.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/81vx1fDkM9L._SX355_.jpg',
    'model': 'ED320Q X2',
    'mrp': 23999.0,
    'part_no': 'UM.JE0SI.201',
    'product_group': 'acer_monitors',
    'rating': 4.2,
    'review_count': 242,
    'sort_order': 49,
    'stock_status': 'Out of Stock',
    'title': 'Acer ED320Q X2 - 31.5" Full HD 1500R Curved Monitor (UM.JE0SI.201)',
    'url_slug': 'acer-ed320q-x2-um-je0si-201'},
    {   'amazon_link': 'https://www.amazon.in/dp/B0BRX92H1Q',
    'asin': 'B0BRX92H1Q',
    'base_price': 17599.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/81UbSzYOREL._SY355_.jpg',
    'model': 'ED320Q W0',
    'mrp': 21999.0,
    'part_no': 'UM.JE0SI.002',
    'product_group': 'acer_monitors',
    'rating': 2.9,
    'review_count': 3,
    'sort_order': 50,
    'stock_status': 'In Stock',
    'title': 'Acer ED320Q W0 - 31.5" Full HD Curved Gaming Monitor (UM.JE0SI.002)',
    'url_slug': 'acer-ed320q-w0-um-je0si-002'},
    {   'amazon_link': 'https://www.amazon.in/dp/B0CYCK4BWT',
    'asin': 'B0CYCK4BWT',
    'base_price': 13599.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/81dNG77VzbL._SY355_.jpg',
    'model': 'ED320QR H',
    'mrp': 16999.0,
    'part_no': 'UM.JE0SI.H01',
    'product_group': 'acer_monitors',
    'rating': 4.3,
    'review_count': 187,
    'sort_order': 51,
    'stock_status': 'Out of Stock',
    'title': 'Acer ED320QR H - 31.5" Full HD VA Curved Monitor (UM.JE0SI.H01)',
    'url_slug': 'acer-ed320qr-h-um-je0si-h01'},
    {   'amazon_link': 'https://www.amazon.in/dp/B0CCSLJPT9',
    'asin': 'B0CCSLJPT9',
    'base_price': 15919.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/81-HEflLXLL._SX355_.jpg',
    'model': 'ED320QR S3',
    'mrp': 20999.0,
    'part_no': 'UM.JE0SI.301',
    'product_group': 'acer_monitors',
    'rating': 4.2,
    'review_count': 274,
    'sort_order': 52,
    'stock_status': 'In Stock',
    'title': 'Acer ED320QR S3 - 31.5" Full HD VA Curved Monitor (UM.JE0SI.301)',
    'url_slug': 'acer-ed320qr-s3-um-je0si-301'},
    {   'amazon_link': 'https://www.amazon.in/dp/B0D9C1D7CC',
    'asin': 'B0D9C1D7CC',
    'base_price': 16999.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/81uN7Z7figL._SY355_.jpg',
    'model': 'SA322QA',
    'mrp': 23999.0,
    'part_no': 'UM.JS2SI.A02',
    'product_group': 'acer_monitors',
    'rating': 4.4,
    'review_count': 172,
    'sort_order': 53,
    'stock_status': 'Out of Stock',
    'title': 'Acer SA322QA - 31.5" Full HD IPS Monitor (UM.JS2SI.A02)',
    'url_slug': 'acer-sa322qa-um-js2si-a02'},
    {   'amazon_link': 'https://www.amazon.in/dp/B0D2MXDSP8',
    'asin': 'B0D2MXDSP8',
    'base_price': 17599.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/81Bep0+38gL._SX355_.jpg',
    'model': 'SA322QU E',
    'mrp': 20999.0,
    'part_no': 'UM.JS2SI.E01',
    'product_group': 'acer_monitors',
    'rating': 4.1,
    'review_count': 184,
    'sort_order': 54,
    'stock_status': 'Out of Stock',
    'title': 'Acer SA322QU E - 31.5" WQHD 2K IPS Monitor (UM.JS2SI.E01)',
    'url_slug': 'acer-sa322qu-e-um-js2si-e01'},
    {   'amazon_link': 'https://www.amazon.in/dp/B0DH2Y8MJK',
    'asin': 'B0DH2Y8MJK',
    'base_price': 19999.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/81YjdzxFSOL._SY355_.jpg',
    'model': 'SA322QK',
    'mrp': 26999.0,
    'part_no': 'UM.JS2SI.001',
    'product_group': 'acer_monitors',
    'rating': 3.7,
    'review_count': 65,
    'sort_order': 55,
    'stock_status': 'In Stock',
    'title': 'Acer SA322QK - 31.5" 4K UHD IPS Monitor (UM.JS2SI.001)',
    'url_slug': 'acer-sa322qk-um-js2si-001'},
    {   'amazon_link': 'https://www.amazon.in/dp/B0BDD91273',
    'asin': 'B0BDD91273',
    'base_price': 29299.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/71RIts-62tL._SY355_.jpg',
    'model': 'GA321QU',
    'mrp': 36999.0,
    'part_no': 'UM.JG1SI.P01',
    'product_group': 'acer_monitors',
    'rating': 4.0,
    'review_count': 72,
    'sort_order': 56,
    'stock_status': 'In Stock',
    'title': 'Acer GA321QU - 31.5" WQHD 2K VA Curved Gaming Monitor (UM.JG1SI.P01)',
    'url_slug': 'acer-ga321qu-um-jg1si-p01'},
    {   'amazon_link': 'https://www.amazon.in/dp/B0CYCG7WKY',
    'asin': 'B0CYCG7WKY',
    'base_price': 26999.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/81YJV6rp69L._SX355_.jpg',
    'model': 'ED343CUR V3',
    'mrp': 36999.0,
    'part_no': 'UM.CE3SI.301',
    'product_group': 'acer_monitors',
    'rating': 4.4,
    'review_count': 378,
    'sort_order': 57,
    'stock_status': 'Out of Stock',
    'title': 'Acer ED343CUR V3 - 34" UWQHD 21:9 Curved Gaming Monitor (UM.CE3SI.301)',
    'url_slug': 'acer-ed343cur-v3-um-ce3si-301'},
    {   'amazon_link': 'https://www.amazon.in/dp/B083BWT63C',
    'asin': 'B083BWT63C',
    'base_price': 26999.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/71kVs0QOnwL._SY355_.jpg',
    'model': 'ED343CUR X0',
    'mrp': 36999.0,
    'part_no': 'UM.CE3SI.001',
    'product_group': 'acer_monitors',
    'rating': 4.1,
    'review_count': 106,
    'sort_order': 58,
    'stock_status': 'Out of Stock',
    'title': 'Acer ED343CUR X0 - 34" UWQHD 21:9 Curved Nitro Gaming Monitor (UM.CE3SI.001)',
    'url_slug': 'acer-ed343cur-x0-um-ce3si-001'},
    {   'amazon_link': 'https://www.amazon.in/dp/B0GXPDRDGJ',
    'asin': 'B0GXPDRDGJ',
    'base_price': 23599.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/51klzhGTCgL._SY355_.jpg',
    'model': 'ED340CUR X0',
    'mrp': 27999.0,
    'part_no': 'UM.CE0SI.001',
    'product_group': 'acer_monitors',
    'rating': 4.1,
    'review_count': 63,
    'sort_order': 59,
    'stock_status': 'In Stock',
    'title': 'Acer ED340CUR X0 - 34" UWQHD 21:9 Curved Nitro Gaming Monitor (UM.CE0SI.001)',
    'url_slug': 'acer-ed340cur-x0-um-ce0si-001'},
    {   'amazon_link': 'https://www.amazon.in/dp/B09RZR8YKQ',
    'asin': 'B09RZR8YKQ',
    'base_price': 39999.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/71F8KF5t8ML._SX355_.jpg',
    'model': 'XZ396QU',
    'mrp': 54999.0,
    'part_no': 'UM.TX6SI.P01',
    'product_group': 'acer_monitors',
    'rating': 3.9,
    'review_count': 100,
    'sort_order': 60,
    'stock_status': 'Out of Stock',
    'title': 'Acer XZ396QU - 38.5" Curved Gaming Monitor (UM.TX6SI.P01)',
    'url_slug': 'acer-xz396qu-um-tx6si-p01'},
    {   'amazon_link': 'https://www.amazon.in/dp/B097T8CR3S',
    'asin': 'B097T8CR3S',
    'base_price': 64999.0,
    'category': 'Monitors',
    'image_url': 'https://m.media-amazon.com/images/I/71ynrq8IqbL._SX355_.jpg',
    'model': 'EI491CR S',
    'mrp': 89999.0,
    'part_no': 'UM.SE1SI.S02',
    'product_group': 'acer_monitors',
    'rating': 3.8,
    'review_count': 56,
    'sort_order': 61,
    'stock_status': 'Out of Stock',
    'title': 'Acer EI491CR S - 49" Super Ultrawide 32:9 Curved Gaming Monitor (UM.SE1SI.S02)',
    'url_slug': 'acer-ei491cr-s-um-se1si-s02'},
]

# ALL 90 ACER ACCESSORIES (including stands & privacy screens, ordered 1-90 matching Excel)
ACER_OTHER_SEED_PRODUCTS = [
    {   'amazon_link': 'https://amzn.in/d/0gFTTe4f',
    'asin': 'B0DNNLW8MK',
    'base_price': 499.0,
    'category': 'Wireless & Wired Mice',
    'image_url': 'https://m.media-amazon.com/images/I/71YJjGWaGHL._SL1500_.jpg',
    'model': 'Acer ClearView Transparent Mouse - Green',
    'mrp': 999.0,
    'part_no': 'ZC.A01SI.18F',
    'product_group': 'other_products',
    'rating': 3.7,
    'review_count': 111,
    'sort_order': 1,
    'stock_status': 'In Stock',
    'title': 'Acer ClearView Transparent Mouse - Green (ZC.A01SI.18F)',
    'url_slug': 'acer-clearview-transparent-mouse-green-zc-a01si-18'},
    {   'amazon_link': 'https://amzn.in/d/096DqpWo',
    'asin': 'B0DNNLWB1V',
    'base_price': 409.0,
    'category': 'Wireless & Wired Mice',
    'image_url': 'https://m.media-amazon.com/images/I/61gqfGpXVzL._SL1500_.jpg',
    'model': 'Acer ClearView Transparent Mouse - White',
    'mrp': 999.0,
    'part_no': 'ZC.A01SI.18D',
    'product_group': 'other_products',
    'rating': 3.5,
    'review_count': 38,
    'sort_order': 2,
    'stock_status': 'In Stock',
    'title': 'Acer ClearView Transparent Mouse - White (ZC.A01SI.18D)',
    'url_slug': 'acer-clearview-transparent-mouse-white-zc-a01si-18'},
    {   'amazon_link': 'https://amzn.in/d/02vcJ7aV',
    'asin': 'B0DNNLNTHY',
    'base_price': 499.0,
    'category': 'Wireless & Wired Mice',
    'image_url': 'https://m.media-amazon.com/images/I/71OflSCvFYL._SL1500_.jpg',
    'model': 'Acer ClearView Transparent Mouse - Blue',
    'mrp': 999.0,
    'part_no': 'ZC.A01SI.18E',
    'product_group': 'other_products',
    'rating': 3.7,
    'review_count': 111,
    'sort_order': 3,
    'stock_status': 'In Stock',
    'title': 'Acer ClearView Transparent Mouse - Blue (ZC.A01SI.18E)',
    'url_slug': 'acer-clearview-transparent-mouse-blue-zc-a01si-18e'},
    {   'amazon_link': 'https://amzn.in/d/02klBboU',
    'asin': 'B0H5XK7SRG',
    'base_price': 499.0,
    'category': 'Wireless & Wired Mice',
    'image_url': 'https://m.media-amazon.com/images/I/71Oo+Q016SL._SL1500_.jpg',
    'model': 'Acer ClearView Transparent Mouse - Black',
    'mrp': 999.0,
    'part_no': 'ZC.A01SI.4WE',
    'product_group': 'other_products',
    'rating': 3.7,
    'review_count': 111,
    'sort_order': 4,
    'stock_status': 'In Stock',
    'title': 'Acer ClearView Transparent Mouse - Black (ZC.A01SI.4WE)',
    'url_slug': 'acer-clearview-transparent-mouse-black-zc-a01si-4w'},
    {   'amazon_link': 'https://amzn.in/d/01WsvzuO',
    'asin': 'B0FCFW7QB5',
    'base_price': 598.0,
    'category': 'Wireless & Wired Mice',
    'image_url': 'https://m.media-amazon.com/images/I/71qh6BvmAsL._SL1500_.jpg',
    'model': 'Wireless Transparent Rechargeable Mouse – Grey OS',
    'mrp': 999.0,
    'part_no': 'ZC.A01SI.2DR',
    'product_group': 'other_products',
    'rating': 4.3,
    'review_count': 512,
    'sort_order': 5,
    'stock_status': 'In Stock',
    'title': 'Wireless Transparent Rechargeable Mouse  Grey OS (ZC.A01SI.2DR)',
    'url_slug': 'wireless-transparent-rechargeable-mouse-grey-os-zc'},
    {   'amazon_link': 'https://amzn.in/d/04hQzsx1',
    'asin': 'B0FCFW9LNG',
    'base_price': 584.0,
    'category': 'Wireless & Wired Mice',
    'image_url': 'https://m.media-amazon.com/images/I/71NVFIKSliL._SL1500_.jpg',
    'model': 'Wireless Transparent Rechargeable Mouse – Peach OS',
    'mrp': 999.0,
    'part_no': 'ZC.A01SI.2DT',
    'product_group': 'other_products',
    'rating': 4.3,
    'review_count': 512,
    'sort_order': 6,
    'stock_status': 'In Stock',
    'title': 'Wireless Transparent Rechargeable Mouse  Peach OS (ZC.A01SI.2DT)',
    'url_slug': 'wireless-transparent-rechargeable-mouse-peach-os-z'},
    {   'amazon_link': 'https://amzn.in/d/0d8sfi77',
    'asin': 'B0D378LN1J',
    'base_price': 315.0,
    'category': 'Wireless & Wired Mice',
    'image_url': 'https://m.media-amazon.com/images/I/41wDHNWqqmL._SL1000_.jpg',
    'model': 'Acer Wireless Mouse White Green',
    'mrp': 1499.0,
    'part_no': '5W.50611.004',
    'product_group': 'other_products',
    'rating': 4.2,
    'review_count': 1353,
    'sort_order': 7,
    'stock_status': 'In Stock',
    'title': 'Acer Wireless Mouse White Green (5W.50611.004)',
    'url_slug': 'acer-wireless-mouse-white-green-5w-50611-004'},
    {   'amazon_link': 'https://amzn.in/d/01HTqM53',
    'asin': 'B0D7VSW3W9',
    'base_price': 355.0,
    'category': 'Wireless & Wired Mice',
    'image_url': 'https://m.media-amazon.com/images/I/51zKXH9e23L._SL1500_.jpg',
    'model': 'Acer Wireless Mouse, White Orange',
    'mrp': 1499.0,
    'part_no': 'ZC.A01SI.0WB',
    'product_group': 'other_products',
    'rating': 4.2,
    'review_count': 1353,
    'sort_order': 8,
    'stock_status': 'In Stock',
    'title': 'Acer Wireless Mouse, White Orange (ZC.A01SI.0WB)',
    'url_slug': 'acer-wireless-mouse-white-orange-zc-a01si-0wb'},
    {   'amazon_link': 'https://amzn.in/d/05Fir8bg',
    'asin': 'B0DJBK21X7',
    'base_price': 355.0,
    'category': 'Wireless & Wired Mice',
    'image_url': 'https://m.media-amazon.com/images/I/51jOAM8+8zL._SL1500_.jpg',
    'model': 'Acer Wireless Mouse, White Blue',
    'mrp': 1499.0,
    'part_no': 'ZC.A01SI.0WC',
    'product_group': 'other_products',
    'rating': 4.2,
    'review_count': 1353,
    'sort_order': 9,
    'stock_status': 'In Stock',
    'title': 'Acer Wireless Mouse, White Blue (ZC.A01SI.0WC)',
    'url_slug': 'acer-wireless-mouse-white-blue-zc-a01si-0wc'},
    {   'amazon_link': 'https://amzn.in/d/0iGTa5NW',
    'asin': 'B0FQQMSRP8',
    'base_price': 355.0,
    'category': 'Wireless & Wired Mice',
    'image_url': 'https://m.media-amazon.com/images/I/71cWw7ip0qL._SL1500_.jpg',
    'model': 'Acer Wireless Mouse, Black/Red',
    'mrp': 1499.0,
    'part_no': 'ZC.A01SI.3S8',
    'product_group': 'other_products',
    'rating': 4.2,
    'review_count': 1353,
    'sort_order': 10,
    'stock_status': 'In Stock',
    'title': 'Acer Wireless Mouse, Black/Red (ZC.A01SI.3S8)',
    'url_slug': 'acer-wireless-mouse-black-red-zc-a01si-3s8'},
    {   'amazon_link': 'https://amzn.in/d/0drqvfM7',
    'asin': 'B0FPDKR4GX',
    'base_price': 499.0,
    'category': 'Wireless & Wired Mice',
    'image_url': 'https://m.media-amazon.com/images/I/61MecoKNwDL._SL1500_.jpg',
    'model': 'Acer Prism Wireless Rechargeable Mouse - Black',
    'mrp': 1499.0,
    'part_no': 'ZC.A01SI.2ZQ',
    'product_group': 'other_products',
    'rating': 4.4,
    'review_count': 212,
    'sort_order': 11,
    'stock_status': 'In Stock',
    'title': 'Acer Prism Wireless Rechargeable Mouse - Black (ZC.A01SI.2ZQ)',
    'url_slug': 'acer-prism-wireless-rechargeable-mouse-black-zc-a0'},
    {   'amazon_link': 'https://amzn.in/d/02zAZaxY',
    'asin': 'B0GYT9GRFW',
    'base_price': 799.0,
    'category': 'Wireless & Wired Mice',
    'image_url': 'https://m.media-amazon.com/images/I/71vQ4nDMN8L._SL1500_.jpg',
    'model': 'Acer Prism Wireless Rechargeable Mouse - Yellow',
    'mrp': 1499.0,
    'part_no': 'ZC.A01SI.4R7',
    'product_group': 'other_products',
    'rating': 4.4,
    'review_count': 212,
    'sort_order': 12,
    'stock_status': 'Out of Stock',
    'title': 'Acer Prism Wireless Rechargeable Mouse - Yellow (ZC.A01SI.4R7)',
    'url_slug': 'acer-prism-wireless-rechargeable-mouse-yellow-zc-a'},
    {   'amazon_link': 'https://amzn.in/d/0iA8VsbU',
    'asin': 'B0FPDJYKBX',
    'base_price': 598.0,
    'category': 'Wireless & Wired Mice',
    'image_url': 'https://m.media-amazon.com/images/I/615BCc-qFqL._SL1500_.jpg',
    'model': 'Acer Prism Wireless Rechargeable Mouse - White',
    'mrp': 1499.0,
    'part_no': 'ZC.A01SI.2ZP',
    'product_group': 'other_products',
    'rating': 4.4,
    'review_count': 212,
    'sort_order': 13,
    'stock_status': 'In Stock',
    'title': 'Acer Prism Wireless Rechargeable Mouse - White (ZC.A01SI.2ZP)',
    'url_slug': 'acer-prism-wireless-rechargeable-mouse-white-zc-a0'},
    {   'amazon_link': 'https://amzn.in/d/03p9eVRt',
    'asin': 'B0FRZ85XH1',
    'base_price': 998.0,
    'category': 'Wireless & Wired Mice',
    'image_url': 'https://m.media-amazon.com/images/I/61TAZuSmL+L._SL1500_.jpg',
    'model': 'Acer Ergo Vertical Wireless Mouse - White',
    'mrp': 2000.0,
    'part_no': 'ZC.A01SI.393',
    'product_group': 'other_products',
    'rating': 3.8,
    'review_count': 205,
    'sort_order': 14,
    'stock_status': 'In Stock',
    'title': 'Acer Ergo Vertical Wireless Mouse - White (ZC.A01SI.393)',
    'url_slug': 'acer-ergo-vertical-wireless-mouse-white-zc-a01si-3'},
    {   'amazon_link': 'https://amzn.in/d/0byavpY9',
    'asin': 'B0FRZ861L9',
    'base_price': 998.0,
    'category': 'Wireless & Wired Mice',
    'image_url': 'https://m.media-amazon.com/images/I/717BUFALtgL._SL1500_.jpg',
    'model': 'Acer Ergo Vertical Wireless Mouse - Grey',
    'mrp': 2000.0,
    'part_no': 'ZC.A01SI.394',
    'product_group': 'other_products',
    'rating': 3.8,
    'review_count': 205,
    'sort_order': 15,
    'stock_status': 'In Stock',
    'title': 'Acer Ergo Vertical Wireless Mouse - Grey (ZC.A01SI.394)',
    'url_slug': 'acer-ergo-vertical-wireless-mouse-grey-zc-a01si-39'},
    {   'amazon_link': 'https://amzn.in/d/0dYfjK4d',
    'asin': 'B0FKPCRVCZ',
    'base_price': 499.0,
    'category': 'Wireless & Wired Mice',
    'image_url': 'https://m.media-amazon.com/images/I/71XWRGOzb-L._SL1500_.jpg',
    'model': 'Bubble Mouse Blue/Green',
    'mrp': 999.0,
    'part_no': 'ZC.A01SI.2N0',
    'product_group': 'other_products',
    'rating': 4.3,
    'review_count': 909,
    'sort_order': 16,
    'stock_status': 'Out of Stock',
    'title': 'Bubble Mouse Blue/Green (ZC.A01SI.2N0)',
    'url_slug': 'bubble-mouse-blue-green-zc-a01si-2n0'},
    {   'amazon_link': 'https://amzn.in/d/05zCkpwR',
    'asin': 'B0FKPXG5R8',
    'base_price': 499.0,
    'category': 'Wireless & Wired Mice',
    'image_url': 'https://m.media-amazon.com/images/I/71RaUC00idL._SL1500_.jpg',
    'model': 'Bubble Mouse Peach',
    'mrp': 999.0,
    'part_no': 'ZC.A01SI.2N1',
    'product_group': 'other_products',
    'rating': 4.3,
    'review_count': 909,
    'sort_order': 17,
    'stock_status': 'Out of Stock',
    'title': 'Bubble Mouse Peach (ZC.A01SI.2N1)',
    'url_slug': 'bubble-mouse-peach-zc-a01si-2n1'},
    {   'amazon_link': 'https://amzn.in/d/0iDzqvS3',
    'asin': 'B0FKPNYY9Z',
    'base_price': 499.0,
    'category': 'Wireless & Wired Mice',
    'image_url': 'https://m.media-amazon.com/images/I/61Wr9tOYxRL._SL1500_.jpg',
    'model': 'Bubble Mouse White',
    'mrp': 999.0,
    'part_no': 'ZC.A01SI.2MZ',
    'product_group': 'other_products',
    'rating': 4.3,
    'review_count': 909,
    'sort_order': 18,
    'stock_status': 'Out of Stock',
    'title': 'Bubble Mouse White (ZC.A01SI.2MZ)',
    'url_slug': 'bubble-mouse-white-zc-a01si-2mz'},
    {   'amazon_link': 'https://amzn.in/d/01DqOKBG',
    'asin': 'B0GQVQF9YQ',
    'base_price': 698.0,
    'category': 'Wireless & Wired Mice',
    'image_url': 'https://m.media-amazon.com/images/I/71AmPFtYmHL._SL1500_.jpg',
    'model': 'PopGo Wireless Mouse | 2.4G + BT5.4 Dual Mode',
    'mrp': 1599.0,
    'part_no': 'ZC.A01SI.3ZE',
    'product_group': 'other_products',
    'rating': 4.3,
    'review_count': 135,
    'sort_order': 19,
    'stock_status': 'In Stock',
    'title': 'PopGo Wireless Mouse | 2.4G + BT5.4 Dual Mode (ZC.A01SI.3ZE)',
    'url_slug': 'popgo-wireless-mouse-2-4g-bt5-4-dual-mode-zc-a01si'},
    {   'amazon_link': 'https://amzn.in/d/0hb3pkuS',
    'asin': 'B0H83FL8CJ',
    'base_price': 1499.0,
    'category': 'Gaming Mice',
    'image_url': 'https://m.media-amazon.com/images/I/61qjtyIv4lL._SL1500_.jpg',
    'model': 'Acer Nitro Phantom X12 Tri-Mode Gaming Mouse',
    'mrp': 2499.0,
    'part_no': 'ZC.A01SI.4ND',
    'product_group': 'other_products',
    'rating': 4.4,
    'review_count': 310,
    'sort_order': 20,
    'stock_status': 'Out of Stock',
    'title': 'Acer Nitro Phantom X12 Tri-Mode Gaming Mouse (ZC.A01SI.4ND)',
    'url_slug': 'acer-nitro-phantom-x12-tri-mode-gaming-mouse-zc-a0'},
    {   'amazon_link': 'https://amzn.in/d/0a2asTCM',
    'asin': 'B0H83548VY',
    'base_price': 899.0,
    'category': 'Gaming Mice',
    'image_url': 'https://m.media-amazon.com/images/I/61JNCNvVtXL._SL1500_.jpg',
    'model': 'Acer Nitro Phantom X7 Wired Gaming Mouse | 7200 DPI',
    'mrp': 1799.0,
    'part_no': 'ZC.A01SI.4NE',
    'product_group': 'other_products',
    'rating': 4.4,
    'review_count': 310,
    'sort_order': 21,
    'stock_status': 'Out of Stock',
    'title': 'Acer Nitro Phantom X7 Wired Gaming Mouse | 7200 DPI (ZC.A01SI.4NE)',
    'url_slug': 'acer-nitro-phantom-x7-wired-gaming-mouse-7200-dpi-'},
    {   'amazon_link': 'https://amzn.in/d/0iHFtpej',
    'asin': 'B0G5FM1C7J',
    'base_price': 899.0,
    'category': 'Gaming Mice',
    'image_url': 'https://m.media-amazon.com/images/I/61eU9U99ASL._SL1500_.jpg',
    'model': 'Nitro 7 Gaming Mouse',
    'mrp': 2999.0,
    'part_no': 'ZC.A01SI.3RX',
    'product_group': 'other_products',
    'rating': 4.4,
    'review_count': 21,
    'sort_order': 22,
    'stock_status': 'In Stock',
    'title': 'Nitro 7 Gaming Mouse (ZC.A01SI.3RX)',
    'url_slug': 'nitro-7-gaming-mouse-zc-a01si-3rx'},
    {   'amazon_link': 'https://amzn.in/d/0cs3yrH9',
    'asin': 'B0G5FFNPDN',
    'base_price': 575.0,
    'category': 'Gaming Mice',
    'image_url': 'https://m.media-amazon.com/images/I/613sMu0LojL._SL1500_.jpg',
    'model': 'Acer Titan X Gaming Mouse',
    'mrp': 1999.0,
    'part_no': 'ZC.A01SI.3RY',
    'product_group': 'other_products',
    'rating': 4.1,
    'review_count': 30,
    'sort_order': 23,
    'stock_status': 'Out of Stock',
    'title': 'Acer Titan X Gaming Mouse (ZC.A01SI.3RY)',
    'url_slug': 'acer-titan-x-gaming-mouse-zc-a01si-3ry'},
    {   'amazon_link': 'https://amzn.in/d/0dZscBFB',
    'asin': 'B0DP4M69WM',
    'base_price': 1496.0,
    'category': 'Keyboards',
    'image_url': 'https://m.media-amazon.com/images/I/81vlxcYQIJL._SL1500_.jpg',
    'model': 'ACER Wireless Rechargeable Keyboard BLACK with GREEN cradle ACR101',
    'mrp': 3500.0,
    'part_no': 'ZC.A01SI.18K',
    'product_group': 'other_products',
    'rating': 4.0,
    'review_count': 184,
    'sort_order': 24,
    'stock_status': 'In Stock',
    'title': 'ACER Wireless Rechargeable Keyboard BLACK with GREEN cradle ACR101 (ZC.A01SI.18K)',
    'url_slug': 'acer-wireless-rechargeable-keyboard-black-with-gre'},
    {   'amazon_link': 'https://amzn.in/d/0db8lr4G',
    'asin': 'B0DP1FCHQ9',
    'base_price': 1995.0,
    'category': 'Keyboards',
    'image_url': 'https://m.media-amazon.com/images/I/81ma1RrYczL._SL1500_.jpg',
    'model': 'ACER ClearView Wireless Rechargeable Keyboard SILVER ACR100',
    'mrp': 4000.0,
    'part_no': 'ZC.A01SI.18J',
    'product_group': 'other_products',
    'rating': 3.6,
    'review_count': 354,
    'sort_order': 25,
    'stock_status': 'In Stock',
    'title': 'ACER ClearView Wireless Rechargeable Keyboard SILVER ACR100 (ZC.A01SI.18J)',
    'url_slug': 'acer-clearview-wireless-rechargeable-keyboard-silv'},
    {   'amazon_link': 'https://amzn.in/d/0ah5sBet',
    'asin': 'B0GRJXKCRQ',
    'base_price': 1698.0,
    'category': 'Keyboards',
    'image_url': 'https://m.media-amazon.com/images/I/71I4S3Nt7qL._SL1500_.jpg',
    'model': 'Acer KeyPro Wireless Dual Mode Keyboard - Space Grey',
    'mrp': 2999.0,
    'part_no': 'ZC.A01SI.3ZF',
    'product_group': 'other_products',
    'rating': 4.3,
    'review_count': 75,
    'sort_order': 26,
    'stock_status': 'In Stock',
    'title': 'Acer KeyPro Wireless Dual Mode Keyboard - Space Grey (ZC.A01SI.3ZF)',
    'url_slug': 'acer-keypro-wireless-dual-mode-keyboard-space-grey'},
    {   'amazon_link': 'https://amzn.in/d/05dx2Scc',
    'asin': 'B0GRJX27DG',
    'base_price': 1698.0,
    'category': 'Keyboards',
    'image_url': 'https://m.media-amazon.com/images/I/71v9YOES30L._SL1500_.jpg',
    'model': 'Acer KeyPro Wireless Dual Mode Keyboard - Silver',
    'mrp': 2999.0,
    'part_no': 'ZC.A01SI.3ZG',
    'product_group': 'other_products',
    'rating': 4.2,
    'review_count': 92,
    'sort_order': 27,
    'stock_status': 'In Stock',
    'title': 'Acer KeyPro Wireless Dual Mode Keyboard - Silver (ZC.A01SI.3ZG)',
    'url_slug': 'acer-keypro-wireless-dual-mode-keyboard-silver-zc-'},
    {   'amazon_link': 'https://amzn.in/d/04lyF1ax',
    'asin': 'B0FG94XRNK',
    'base_price': 2299.0,
    'category': 'Keyboards',
    'image_url': 'https://m.media-amazon.com/images/I/71+U+2hRXXL._SL1500_.jpg',
    'model': 'ACER Wireless Rechargeable Keyboard BLACK with GREEN cradle and Touchpad',
    'mrp': 3499.0,
    'part_no': 'ZC.A01SI.224',
    'product_group': 'other_products',
    'rating': 3.9,
    'review_count': 144,
    'sort_order': 28,
    'stock_status': 'Out of Stock',
    'title': 'ACER Wireless Rechargeable Keyboard BLACK with GREEN cradle and Touchpad (ZC.A01SI.224)',
    'url_slug': 'acer-wireless-rechargeable-keyboard-black-with-gre'},
    {   'amazon_link': 'https://amzn.in/d/02knIdjO',
    'asin': 'B0FG995CZS',
    'base_price': 1085.0,
    'category': 'Keyboards',
    'image_url': 'https://m.media-amazon.com/images/I/71fMrvjPbfL._SL1500_.jpg',
    'model': 'Acer Wireless Rechargeable Keyboard with cradle and Numpad - off white colored keys',
    'mrp': 3699.0,
    'part_no': 'ZC.A01SI.225',
    'product_group': 'other_products',
    'rating': 3.8,
    'review_count': 35,
    'sort_order': 29,
    'stock_status': 'In Stock',
    'title': 'Acer Wireless Rechargeable Keyboard with cradle and Numpad - off white colored keys (ZC.A01SI.225)',
    'url_slug': 'acer-wireless-rechargeable-keyboard-with-cradle-an'},
    {   'amazon_link': 'https://amzn.in/d/0dnY3fzz',
    'asin': 'B0F9PLCSKL',
    'base_price': 2299.0,
    'category': 'Keyboards',
    'image_url': 'https://m.media-amazon.com/images/I/71V0dJYfCeL._SL1500_.jpg',
    'model': 'Acer Solar Keyboard',
    'mrp': 3499.0,
    'part_no': 'ZC.A01SI.1LH',
    'product_group': 'other_products',
    'rating': 4.0,
    'review_count': 18,
    'sort_order': 30,
    'stock_status': 'Out of Stock',
    'title': 'Acer Solar Keyboard (ZC.A01SI.1LH)',
    'url_slug': 'acer-solar-keyboard-zc-a01si-1lh'},
    {   'amazon_link': 'https://amzn.in/d/07t1OXTz',
    'asin': 'B0H18M1KZ5',
    'base_price': 698.0,
    'category': 'Keyboards',
    'image_url': 'https://m.media-amazon.com/images/I/71lSEaT0jsL._SL1500_.jpg',
    'model': 'Acer SoftKey Pro Wireless Keyboard | 2.4GHz ',
    'mrp': 1999.0,
    'part_no': 'ZC.A01SI.4VY',
    'product_group': 'other_products',
    'rating': 4.0,
    'review_count': 30,
    'sort_order': 31,
    'stock_status': 'In Stock',
    'title': 'Acer SoftKey Pro Wireless Keyboard | 2.4GHz (ZC.A01SI.4VY)',
    'url_slug': 'acer-softkey-pro-wireless-keyboard-2-4ghz-zc-a01si'},
    {   'amazon_link': 'https://amzn.in/d/0j4CJByc',
    'asin': 'B0FTZXFSH1',
    'base_price': 1999.0,
    'category': 'Keyboards',
    'image_url': 'https://m.media-amazon.com/images/I/81ZdVORcT9L._SL1500_.jpg',
    'model': 'Acer Trifold Pro | 60 Keys Foldable ',
    'mrp': 2599.0,
    'part_no': 'ZC.A01SI.39X',
    'product_group': 'other_products',
    'rating': 3.6,
    'review_count': 38,
    'sort_order': 32,
    'stock_status': 'In Stock',
    'title': 'Acer Trifold Pro | 60 Keys Foldable (ZC.A01SI.39X)',
    'url_slug': 'acer-trifold-pro-60-keys-foldable-zc-a01si-39x'},
    {   'amazon_link': 'https://amzn.in/d/07fZITfY',
    'asin': 'B0FTZX7RP8',
    'base_price': 2668.0,
    'category': 'Keyboards',
    'image_url': 'https://m.media-amazon.com/images/I/81n5tV9xFEL._SL1500_.jpg',
    'model': 'Acer Fold Max | 99 Keys',
    'mrp': 2999.0,
    'part_no': 'ZC.A01SI.39Y',
    'product_group': 'other_products',
    'rating': 3.5,
    'review_count': 41,
    'sort_order': 33,
    'stock_status': 'In Stock',
    'title': 'Acer Fold Max | 99 Keys (ZC.A01SI.39Y)',
    'url_slug': 'acer-fold-max-99-keys-zc-a01si-39y'},
    {   'amazon_link': 'https://amzn.in/d/091waa5V',
    'asin': 'B0FTZXX729',
    'base_price': 999.0,
    'category': 'Keyboards',
    'image_url': 'https://m.media-amazon.com/images/I/71FSalzPqeL._SL1500_.jpg',
    'model': 'Acer Mini Fold | 67 Keys Compact',
    'mrp': 1999.0,
    'part_no': 'ZC.A01SI.39Z',
    'product_group': 'other_products',
    'rating': 4.0,
    'review_count': 103,
    'sort_order': 34,
    'stock_status': 'In Stock',
    'title': 'Acer Mini Fold | 67 Keys Compact (ZC.A01SI.39Z)',
    'url_slug': 'acer-mini-fold-67-keys-compact-zc-a01si-39z'},
    {   'amazon_link': 'https://amzn.in/d/0hKaWdc5',
    'asin': 'B0H65TZF1R',
    'base_price': 1199.0,
    'category': 'Keyboards',
    'image_url': 'https://m.media-amazon.com/images/I/71-c+qkae4L._SL1500_.jpg',
    'model': 'Acer NanoPad Touch (Green)',
    'mrp': 1999.0,
    'part_no': 'ZC.A01SI.4YV',
    'product_group': 'other_products',
    'rating': 2.6,
    'review_count': 85,
    'sort_order': 35,
    'stock_status': 'Out of Stock',
    'title': 'Acer NanoPad Touch (Green) (ZC.A01SI.4YV)',
    'url_slug': 'acer-nanopad-touch-green-zc-a01si-4yv'},
    {   'amazon_link': 'https://amzn.in/d/0h1ZTet3',
    'asin': 'B0H65MQ33D',
    'base_price': 899.0,
    'category': 'Keyboards',
    'image_url': 'https://m.media-amazon.com/images/I/71Ku1ZHaOXL._SL1500_.jpg',
    'model': 'Acer NanoPad Touch (Peach)',
    'mrp': 1999.0,
    'part_no': 'ZC.A01SI.4YU',
    'product_group': 'other_products',
    'rating': 2.6,
    'review_count': 85,
    'sort_order': 36,
    'stock_status': 'In Stock',
    'title': 'Acer NanoPad Touch (Peach) (ZC.A01SI.4YU)',
    'url_slug': 'acer-nanopad-touch-peach-zc-a01si-4yu'},
    {   'amazon_link': 'https://amzn.in/d/05wObS7l',
    'asin': 'B0D8354479',
    'base_price': 1099.0,
    'category': 'Keyboard & Mouse Combos',
    'image_url': 'https://m.media-amazon.com/images/I/7157dBNL9LL._SL1500_.jpg',
    'model': 'Acer Wireless KBD Mouse White Gray Combo',
    'mrp': 1999.0,
    'part_no': 'ZC.A01SI.0WD',
    'product_group': 'other_products',
    'rating': 3.8,
    'review_count': 1507,
    'sort_order': 37,
    'stock_status': 'In Stock',
    'title': 'Acer Wireless KBD Mouse White Gray Combo (ZC.A01SI.0WD)',
    'url_slug': 'acer-wireless-kbd-mouse-white-gray-combo-zc-a01si-'},
    {   'amazon_link': 'https://amzn.in/d/00oXwCPx',
    'asin': 'B0F9LN35XH',
    'base_price': 1299.0,
    'category': 'Keyboard & Mouse Combos',
    'image_url': 'https://m.media-amazon.com/images/I/718s8LifBeL._SL1500_.jpg',
    'model': 'Acer Fusion Wireless KBD Mouse Black Silver COMBO',
    'mrp': 1999.0,
    'part_no': 'ZC.A01SI.204',
    'product_group': 'other_products',
    'rating': 3.9,
    'review_count': 210,
    'sort_order': 38,
    'stock_status': 'In Stock',
    'title': 'Acer Fusion Wireless KBD Mouse Black Silver COMBO (ZC.A01SI.204)',
    'url_slug': 'acer-fusion-wireless-kbd-mouse-black-silver-combo-'},
    {   'amazon_link': 'https://amzn.in/d/0cvhC7Ds',
    'asin': 'B0FCS5V5V1',
    'base_price': 598.0,
    'category': 'Keyboard & Mouse Combos',
    'image_url': 'https://m.media-amazon.com/images/I/71rgztpcpkL._SL1500_.jpg',
    'model': 'Acer PalmEase Wired Keyboard & Mouse Combo with Palm Rest',
    'mrp': 1299.0,
    'part_no': 'ZC.A01SI.2DQ',
    'product_group': 'other_products',
    'rating': 4.2,
    'review_count': 132,
    'sort_order': 39,
    'stock_status': 'In Stock',
    'title': 'Acer PalmEase Wired Keyboard & Mouse Combo with Palm Rest (ZC.A01SI.2DQ)',
    'url_slug': 'acer-palmease-wired-keyboard-mouse-combo-with-palm'},
    {   'amazon_link': 'https://amzn.in/d/0fvxtU2O',
    'asin': 'B0GTG3VHZW',
    'base_price': 699.0,
    'category': 'Keyboard & Mouse Combos',
    'image_url': 'https://m.media-amazon.com/images/I/71JogHAjw3L._SL1500_.jpg',
    'model': 'Acer OfficeMate Wired Keyboard Mouse Combo-Black',
    'mrp': 1299.0,
    'part_no': 'ZC.A01SI.4JA',
    'product_group': 'other_products',
    'rating': 3.4,
    'review_count': 111,
    'sort_order': 40,
    'stock_status': 'In Stock',
    'title': 'Acer OfficeMate Wired Keyboard Mouse Combo-Black (ZC.A01SI.4JA)',
    'url_slug': 'acer-officemate-wired-keyboard-mouse-combo-black-z'},
    {   'amazon_link': 'https://amzn.in/d/0d0nItAm',
    'asin': 'B0GTG3X6FF',
    'base_price': 599.0,
    'category': 'Keyboard & Mouse Combos',
    'image_url': 'https://m.media-amazon.com/images/I/710zUWN-ZCL._SL1500_.jpg',
    'model': 'Acer OfficeMate Wired Keyboard Mouse Combo-White',
    'mrp': 1299.0,
    'part_no': 'ZC.A01SI.4JB',
    'product_group': 'other_products',
    'rating': 3.4,
    'review_count': 111,
    'sort_order': 41,
    'stock_status': 'Out of Stock',
    'title': 'Acer OfficeMate Wired Keyboard Mouse Combo-White (ZC.A01SI.4JB)',
    'url_slug': 'acer-officemate-wired-keyboard-mouse-combo-white-z'},
    {   'amazon_link': 'https://amzn.in/d/0bPFvu98',
    'asin': 'B0FCSFT4VX',
    'base_price': 899.0,
    'category': 'Keyboard & Mouse Combos',
    'image_url': 'https://m.media-amazon.com/images/I/71gxJKoZptL._SL1500_.jpg',
    'model': 'Acer PalmEase Wireless Keyboard & Mouse Combo with Palm Rest-Black',
    'mrp': 1999.0,
    'part_no': 'ZC.A01SI.2DP',
    'product_group': 'other_products',
    'rating': 3.9,
    'review_count': 81,
    'sort_order': 42,
    'stock_status': 'In Stock',
    'title': 'Acer PalmEase Wireless Keyboard & Mouse Combo with Palm Rest-Black (ZC.A01SI.2DP)',
    'url_slug': 'acer-palmease-wireless-keyboard-mouse-combo-with-p'},
    {   'amazon_link': 'https://amzn.in/d/028vmivd',
    'asin': 'B0GJTT63ML',
    'base_price': 1099.0,
    'category': 'Keyboard & Mouse Combos',
    'image_url': 'https://m.media-amazon.com/images/I/61i2-mNIrML._SL1500_.jpg',
    'model': 'Acer PalmEase Wireless Keyboard & Mouse Combo with Palm Rest-White',
    'mrp': 1999.0,
    'part_no': 'ZC.A01SI.313',
    'product_group': 'other_products',
    'rating': 3.9,
    'review_count': 81,
    'sort_order': 43,
    'stock_status': 'In Stock',
    'title': 'Acer PalmEase Wireless Keyboard & Mouse Combo with Palm Rest-White (ZC.A01SI.313)',
    'url_slug': 'acer-palmease-wireless-keyboard-mouse-combo-with-p'},
    {   'amazon_link': 'https://amzn.in/d/0e0IBHGC',
    'asin': 'B0FFN8C3KW',
    'base_price': 1099.0,
    'category': 'Keyboard & Mouse Combos',
    'image_url': 'https://m.media-amazon.com/images/I/612DWHDVsHL._SL1500_.jpg',
    'model': 'Acer Nano Pad COMBO - Black',
    'mrp': 1999.0,
    'part_no': 'ZC.A01SI.223',
    'product_group': 'other_products',
    'rating': 3.4,
    'review_count': 1009,
    'sort_order': 44,
    'stock_status': 'Out of Stock',
    'title': 'Acer Nano Pad COMBO - Black (ZC.A01SI.223)',
    'url_slug': 'acer-nano-pad-combo-black-zc-a01si-223'},
    {   'amazon_link': 'https://amzn.in/d/0iKvJyBx',
    'asin': 'B0FTTH71SY',
    'base_price': 999.0,
    'category': 'Keyboard & Mouse Combos',
    'image_url': 'https://m.media-amazon.com/images/I/71e3gwEBcAL._SL1500_.jpg',
    'model': 'Acer Nano Pad COMBO - Purple',
    'mrp': 2000.0,
    'part_no': 'ZC.A01SI.3BH',
    'product_group': 'other_products',
    'rating': 3.4,
    'review_count': 1009,
    'sort_order': 45,
    'stock_status': 'Out of Stock',
    'title': 'Acer Nano Pad COMBO - Purple (ZC.A01SI.3BH)',
    'url_slug': 'acer-nano-pad-combo-purple-zc-a01si-3bh'},
    {   'amazon_link': 'https://amzn.in/d/0fVcwg3C',
    'asin': 'B0G4DCBM4D',
    'base_price': 1398.0,
    'category': 'Keyboard & Mouse Combos',
    'image_url': 'https://m.media-amazon.com/images/I/713AuC+vzUL._SL1500_.jpg',
    'model': 'Acer ZenKeys Duos - Black/Lime',
    'mrp': 2000.0,
    'part_no': 'ZC.A01SI.3R2',
    'product_group': 'other_products',
    'rating': 2.9,
    'review_count': 257,
    'sort_order': 46,
    'stock_status': 'In Stock',
    'title': 'Acer ZenKeys Duos - Black/Lime (ZC.A01SI.3R2)',
    'url_slug': 'acer-zenkeys-duos-black-lime-zc-a01si-3r2'},
    {   'amazon_link': 'https://amzn.in/d/00Sw1xzi',
    'asin': 'B0G4DJQMXK',
    'base_price': 1398.0,
    'category': 'Keyboard & Mouse Combos',
    'image_url': 'https://m.media-amazon.com/images/I/71+T2spJm2L._SL1500_.jpg',
    'model': 'Acer ZenKeys Duos - White/Blue',
    'mrp': 2000.0,
    'part_no': 'ZC.A01SI.3R3',
    'product_group': 'other_products',
    'rating': 2.9,
    'review_count': 257,
    'sort_order': 47,
    'stock_status': 'In Stock',
    'title': 'Acer ZenKeys Duos - White/Blue (ZC.A01SI.3R3)',
    'url_slug': 'acer-zenkeys-duos-white-blue-zc-a01si-3r3'},
    {   'amazon_link': 'https://amzn.in/d/0e1xb7cm',
    'asin': 'B0H8M56QXM',
    'base_price': 899.0,
    'category': 'Keyboard & Mouse Combos',
    'image_url': 'https://m.media-amazon.com/images/I/71mn9to+zJL._SL1500_.jpg',
    'model': 'Acer OfficeLite KM 300 WL COMBO Black -DY',
    'mrp': 1999.0,
    'part_no': 'ZC.A01SI.4VM',
    'product_group': 'other_products',
    'rating': 4.1,
    'review_count': 15,
    'sort_order': 48,
    'stock_status': 'In Stock',
    'title': 'Acer OfficeLite KM 300 WL COMBO Black -DY (ZC.A01SI.4VM)',
    'url_slug': 'acer-officelite-km-300-wl-combo-black-dy-zc-a01si-'},
    {   'amazon_link': 'https://amzn.in/d/00A3nlLp',
    'asin': 'B0H8M8SF2R',
    'base_price': 998.0,
    'category': 'Keyboard & Mouse Combos',
    'image_url': 'https://m.media-amazon.com/images/I/71+1Ok3Rs+L._SL1500_.jpg',
    'model': 'Acer OfficeLite KM 300 WL COMBO White & Grey -DY',
    'mrp': 1999.0,
    'part_no': 'ZC.A01SI.4VN',
    'product_group': 'other_products',
    'rating': 4.1,
    'review_count': 15,
    'sort_order': 49,
    'stock_status': 'In Stock',
    'title': 'Acer OfficeLite KM 300 WL COMBO White & Grey -DY (ZC.A01SI.4VN)',
    'url_slug': 'acer-officelite-km-300-wl-combo-white-grey-dy-zc-a'},
    {   'amazon_link': 'https://amzn.in/d/06sEKkEz',
    'asin': 'B0GK2L7DW7',
    'base_price': 1459.0,
    'category': 'Keyboard & Mouse Combos',
    'image_url': 'https://m.media-amazon.com/images/I/71fE3RKnXdL._SL1500_.jpg',
    'model': 'Acer RedShift Wireless Keyboard & Mouse Combo ',
    'mrp': 2499.0,
    'part_no': 'ZC.A01SI.3U0',
    'product_group': 'other_products',
    'rating': 3.2,
    'review_count': 61,
    'sort_order': 50,
    'stock_status': 'Out of Stock',
    'title': 'Acer RedShift Wireless Keyboard & Mouse Combo (ZC.A01SI.3U0)',
    'url_slug': 'acer-redshift-wireless-keyboard-mouse-combo-zc-a01'},
    {   'amazon_link': 'https://amzn.in/d/03s6F5mt',
    'asin': 'B0DVGSLGB7',
    'base_price': 1599.0,
    'category': 'Keyboard & Mouse Combos',
    'image_url': 'https://m.media-amazon.com/images/I/715Qzq1XMlL._SL1500_.jpg',
    'model': 'Acer Cuteo Keyboard Mouse COMBO - Pink',
    'mrp': 3500.0,
    'part_no': 'ZC.A01SI.18N',
    'product_group': 'other_products',
    'rating': 3.5,
    'review_count': 144,
    'sort_order': 51,
    'stock_status': 'In Stock',
    'title': 'Acer Cuteo Keyboard Mouse COMBO - Pink (ZC.A01SI.18N)',
    'url_slug': 'acer-cuteo-keyboard-mouse-combo-pink-zc-a01si-18n'},
    {   'amazon_link': 'https://amzn.in/d/0ecovzK7',
    'asin': 'B0H66952HK',
    'base_price': 1605.0,
    'category': 'Keyboard & Mouse Combos',
    'image_url': 'https://m.media-amazon.com/images/I/71srROxXWpL._SL1500_.jpg',
    'model': 'Acer PopGo Wireless COMBO - Beige',
    'mrp': 3999.0,
    'part_no': 'ZC.A01SI.4YN',
    'product_group': 'other_products',
    'rating': 3.9,
    'review_count': 12,
    'sort_order': 52,
    'stock_status': 'In Stock',
    'title': 'Acer PopGo Wireless COMBO - Beige (ZC.A01SI.4YN)',
    'url_slug': 'acer-popgo-wireless-combo-beige-zc-a01si-4yn'},
    {   'amazon_link': 'https://amzn.in/d/014JfY3b',
    'asin': 'B0H6628VLR',
    'base_price': 1605.0,
    'category': 'Keyboard & Mouse Combos',
    'image_url': 'https://m.media-amazon.com/images/I/710fsFXgaPL._SL1500_.jpg',
    'model': 'Acer PopGo Wireless COMBO - Purple',
    'mrp': 3999.0,
    'part_no': 'ZC.A01SI.4YP',
    'product_group': 'other_products',
    'rating': 3.9,
    'review_count': 12,
    'sort_order': 53,
    'stock_status': 'In Stock',
    'title': 'Acer PopGo Wireless COMBO - Purple (ZC.A01SI.4YP)',
    'url_slug': 'acer-popgo-wireless-combo-purple-zc-a01si-4yp'},
    {   'amazon_link': 'https://amzn.in/d/0dd5h6uG',
    'asin': 'B0DT9TMYHW',
    'base_price': 1999.0,
    'category': 'Keyboard & Mouse Combos',
    'image_url': 'https://m.media-amazon.com/images/I/81JilIXX68L._SL1500_.jpg',
    'model': 'Acer ALG 4 in 1 COMBO',
    'mrp': 4999.0,
    'part_no': 'ZC.A01SI.1LG',
    'product_group': 'other_products',
    'rating': 3.9,
    'review_count': 182,
    'sort_order': 54,
    'stock_status': 'In Stock',
    'title': 'Acer ALG 4 in 1 COMBO (ZC.A01SI.1LG)',
    'url_slug': 'acer-alg-4-in-1-combo-zc-a01si-1lg'},
    {   'amazon_link': 'https://amzn.in/d/02h2iZTD',
    'asin': 'B0D8YCXLRD',
    'base_price': 2799.0,
    'category': 'Gaming Keyboards',
    'image_url': 'https://m.media-amazon.com/images/I/71gllABTI4L._SL1500_.jpg',
    'model': 'Predator Aethon 303',
    'mrp': 4499.0,
    'part_no': 'GP.KBD11.048',
    'product_group': 'other_products',
    'rating': 4.6,
    'review_count': 6,
    'sort_order': 55,
    'stock_status': 'Out of Stock',
    'title': 'Predator Aethon 303 (GP.KBD11.048)',
    'url_slug': 'predator-aethon-303-gp-kbd11-048'},
    {   'amazon_link': 'https://amzn.in/d/053R055F',
    'asin': 'B0DNFL4C1R',
    'base_price': 3999.0,
    'category': 'Gaming Keyboards',
    'image_url': 'https://m.media-amazon.com/images/I/61J0UQRjvML._SL1500_.jpg',
    'model': 'Predator Aethon 330',
    'mrp': 5999.0,
    'part_no': 'GP.KBD11.04A',
    'product_group': 'other_products',
    'rating': 4.1,
    'review_count': 8,
    'sort_order': 56,
    'stock_status': 'In Stock',
    'title': 'Predator Aethon 330 (GP.KBD11.04A)',
    'url_slug': 'predator-aethon-330-gp-kbd11-04a'},
    {   'amazon_link': 'https://amzn.in/d/0awRxZWI',
    'asin': 'B0G61CFR13',
    'base_price': 2098.0,
    'category': 'Gaming Keyboards',
    'image_url': 'https://m.media-amazon.com/images/I/81T3b9Fw76L._SL1500_.jpg',
    'model': 'acer Nitro G Wired Mechanical Gaming Keyboard',
    'mrp': 3999.0,
    'part_no': 'ZC.A01SI.3RW',
    'product_group': 'other_products',
    'rating': 3.9,
    'review_count': 124,
    'sort_order': 57,
    'stock_status': 'In Stock',
    'title': 'acer Nitro G Wired Mechanical Gaming Keyboard (ZC.A01SI.3RW)',
    'url_slug': 'acer-nitro-g-wired-mechanical-gaming-keyboard-zc-a'},
    {   'amazon_link': 'https://amzn.in/d/032kanBK',
    'asin': 'B07H5R7K2M',
    'base_price': 1699.0,
    'category': 'Audio & Headsets',
    'image_url': 'https://m.media-amazon.com/images/I/71wGpUdWCrL._SL1500_.jpg',
    'model': 'Nitro Wired Gaming Headset',
    'mrp': 2999.0,
    'part_no': 'NP.HDS1A.008',
    'product_group': 'other_products',
    'rating': 4.0,
    'review_count': 160,
    'sort_order': 58,
    'stock_status': 'Out of Stock',
    'title': 'Nitro Wired Gaming Headset (NP.HDS1A.008)',
    'url_slug': 'nitro-wired-gaming-headset-np-hds1a-008'},
    {   'amazon_link': 'https://amzn.in/d/0anrVGEF',
    'asin': 'B0FTVYCWZ8',
    'base_price': 998.0,
    'category': 'Audio & Headsets',
    'image_url': 'https://m.media-amazon.com/images/I/71H9SFO10wL._SL1500_.jpg',
    'model': 'Nitro Wired Gaming Headset',
    'mrp': 2500.0,
    'part_no': 'ZC.A01SI.395',
    'product_group': 'other_products',
    'rating': 3.9,
    'review_count': 33,
    'sort_order': 59,
    'stock_status': 'In Stock',
    'title': 'Nitro Wired Gaming Headset (ZC.A01SI.395)',
    'url_slug': 'nitro-wired-gaming-headset-zc-a01si-395'},
    {   'amazon_link': 'https://amzn.in/d/01GLG4A7',
    'asin': 'B0FR4KJ6NT',
    'base_price': 3453.0,
    'category': 'Audio & Headsets',
    'image_url': 'https://m.media-amazon.com/images/I/71+WYMQs2ZL._SL1500_.jpg',
    'model': 'Nitro Wireless 4 in 1 Headset, 7.1 Surround',
    'mrp': 4000.0,
    'part_no': 'ZC.A01SI.396',
    'product_group': 'other_products',
    'rating': 3.6,
    'review_count': 43,
    'sort_order': 60,
    'stock_status': 'In Stock',
    'title': 'Nitro Wireless 4 in 1 Headset, 7.1 Surround (ZC.A01SI.396)',
    'url_slug': 'nitro-wireless-4-in-1-headset-7-1-surround-zc-a01s'},
    {   'amazon_link': 'https://amzn.in/d/05gaWPCq',
    'asin': 'B0H6629LXR',
    'base_price': 1799.0,
    'category': 'Audio & Headsets',
    'image_url': 'https://m.media-amazon.com/images/I/71oIZunL6WL._SL1500_.jpg',
    'model': 'Nitro Phatom Headset',
    'mrp': 3999.0,
    'part_no': 'ZC.A01SI.4YR',
    'product_group': 'other_products',
    'rating': 3.4,
    'review_count': 7,
    'sort_order': 61,
    'stock_status': 'In Stock',
    'title': 'Nitro Phatom Headset (ZC.A01SI.4YR)',
    'url_slug': 'nitro-phatom-headset-zc-a01si-4yr'},
    {   'amazon_link': 'https://amzn.in/d/0gaJ0c9Q',
    'asin': 'B0GKHYTGB3',
    'base_price': 1299.0,
    'category': 'Audio & Headsets',
    'image_url': 'https://m.media-amazon.com/images/I/714pN+PB1jL._SL1500_.jpg',
    'model': 'Dreamwave Speaker',
    'mrp': 4000.0,
    'part_no': 'ZC.A01SI.3LG',
    'product_group': 'other_products',
    'rating': 3.9,
    'review_count': 23,
    'sort_order': 62,
    'stock_status': 'In Stock',
    'title': 'Dreamwave Speaker (ZC.A01SI.3LG)',
    'url_slug': 'dreamwave-speaker-zc-a01si-3lg'},
    {   'amazon_link': 'https://amzn.in/d/03Gp2VKd',
    'asin': 'B0DCW32MB9',
    'base_price': 1799.0,
    'category': 'Monitor Stands & Mounts',
    'image_url': 'https://m.media-amazon.com/images/I/610REoj1IpL._SL1500_.jpg',
    'model': 'Acer Ergo Monitor Stand with RGB Lights and 4 Port USB HUB (Black)',
    'mrp': 8999.0,
    'part_no': 'ZC.A01SI.179',
    'product_group': 'other_products',
    'rating': 4.1,
    'review_count': 304,
    'sort_order': 63,
    'stock_status': 'In Stock',
    'title': 'Acer Ergo Monitor Stand with RGB Lights and 4 Port USB HUB (Black) (ZC.A01SI.179)',
    'url_slug': 'acer-ergo-monitor-stand-with-rgb-lights-and-4-port'},
    {   'amazon_link': 'https://amzn.in/d/08wi0EN8',
    'asin': 'B0DCW28VCS',
    'base_price': 1799.0,
    'category': 'Monitor Stands & Mounts',
    'image_url': 'https://m.media-amazon.com/images/I/61DFXCjquhL._SL1500_.jpg',
    'model': 'Acer Ergo Monitor Stand with RGB Lights and 4 Port USB HUB (White)',
    'mrp': 8999.0,
    'part_no': 'ZC.A01SI.17A',
    'product_group': 'other_products',
    'rating': 4.3,
    'review_count': 209,
    'sort_order': 64,
    'stock_status': 'In Stock',
    'title': 'acer Ergo Multifunction Monitor & Laptop Stand Featuring RGB Lighting and a 4-Port USB Hub with Aluminum '
             'Multi Keyboard Storage Space Bar, Suitable for Both Office and Home Environments (White)',
    'url_slug': 'acer-ergo-monitor-stand-with-rgb-lights-and-4-port'},
    {   'amazon_link': 'https://amzn.in/d/0egJWQkY',
    'asin': 'B0FQDD56FW',
    'base_price': 2999.0,
    'category': 'Monitor Stands & Mounts',
    'image_url': 'https://m.media-amazon.com/images/I/71GFjNV4lIL._SL1500_.jpg',
    'model': 'Acer FusionBase Ergo Monitor Stand with wireless Charging',
    'mrp': 4999.0,
    'part_no': 'ZC.A01SI.2ZT',
    'product_group': 'other_products',
    'rating': 4.0,
    'review_count': 53,
    'sort_order': 65,
    'stock_status': 'Out of Stock',
    'title': 'Acer FusionBase Ergo Monitor Stand with wireless Charging (ZC.A01SI.2ZT)',
    'url_slug': 'acer-fusionbase-ergo-monitor-stand-with-wireless-c'},
    {   'amazon_link': 'https://amzn.in/d/0fFAi1pK',
    'asin': 'B0GZWS5CL1',
    'base_price': 2499.0,
    'category': 'Monitor Stands & Mounts',
    'image_url': 'https://m.media-amazon.com/images/I/81VlU5-LA2L._SL1500_.jpg',
    'model': 'DeskPro Stand',
    'mrp': 3999.0,
    'part_no': 'ZC.A01SI.4VX',
    'product_group': 'other_products',
    'rating': 3.4,
    'review_count': 20,
    'sort_order': 66,
    'stock_status': 'In Stock',
    'title': 'DeskPro Stand (ZC.A01SI.4VX)',
    'url_slug': 'deskpro-stand-zc-a01si-4vx'},
    {   'amazon_link': 'https://amzn.in/d/04v36OgI',
    'asin': 'B0FZX217Q9',
    'base_price': 2423.0,
    'category': 'Backpacks & Sleeves',
    'image_url': 'https://m.media-amazon.com/images/I/71+F53KqcsL._SL1500_.jpg',
    'model': 'New Predator Backpack',
    'mrp': 3999.0,
    'part_no': 'ZC.A01SI.3BU',
    'product_group': 'other_products',
    'rating': 4.9,
    'review_count': 40,
    'sort_order': 67,
    'stock_status': 'In Stock',
    'title': 'New Predator Backpack (ZC.A01SI.3BU)',
    'url_slug': 'new-predator-backpack-zc-a01si-3bu'},
    {   'amazon_link': 'https://amzn.in/d/05L9cSW5',
    'asin': 'B002EWQY5W',
    'base_price': 1995.0,
    'category': 'Backpacks & Sleeves',
    'image_url': 'https://m.media-amazon.com/images/I/71lneMiBDqL._SL1500_.jpg',
    'model': 'Acer Estilo Beige',
    'mrp': 4999.0,
    'part_no': 'ZC.A01SI.1B7',
    'product_group': 'other_products',
    'rating': 4.3,
    'review_count': 259,
    'sort_order': 68,
    'stock_status': 'In Stock',
    'title': 'Acer Estilo Beige (ZC.A01SI.1B7)',
    'url_slug': 'acer-estilo-beige-zc-a01si-1b7'},
    {   'amazon_link': 'https://amzn.in/d/0bcvRtma',
    'asin': 'B0FSSTD2VS',
    'base_price': 1995.0,
    'category': 'Backpacks & Sleeves',
    'image_url': 'https://m.media-amazon.com/images/I/71tsL1BakEL._SL1500_.jpg',
    'model': 'Acer Estilo Black',
    'mrp': 4999.0,
    'part_no': 'ZC.A01SI.3FJ',
    'product_group': 'other_products',
    'rating': 4.1,
    'review_count': 25,
    'sort_order': 69,
    'stock_status': 'In Stock',
    'title': 'Acer Estilo Black (ZC.A01SI.3FJ)',
    'url_slug': 'acer-estilo-black-zc-a01si-3fj'},
    {   'amazon_link': 'https://amzn.in/d/02hunQ83',
    'asin': 'B0DLB6QBH8',
    'base_price': 1391.0,
    'category': 'Backpacks & Sleeves',
    'image_url': 'https://m.media-amazon.com/images/I/71TVEpNun0L._SL1500_.jpg',
    'model': 'Acer Sling Bag Green',
    'mrp': 3999.0,
    'part_no': 'ZC.A01SI.1B5',
    'product_group': 'other_products',
    'rating': 4.2,
    'review_count': 182,
    'sort_order': 70,
    'stock_status': 'In Stock',
    'title': 'Acer Sling Bag Green (ZC.A01SI.1B5)',
    'url_slug': 'acer-sling-bag-green-zc-a01si-1b5'},
    {   'amazon_link': 'https://amzn.in/d/07NNp9EU',
    'asin': 'B008N4JKEC',
    'base_price': 688.0,
    'category': 'Backpacks & Sleeves',
    'image_url': 'https://m.media-amazon.com/images/I/61PFwGE3BEL._SL1500_.jpg',
    'model': 'Acer Sling Bag Grey',
    'mrp': 3999.0,
    'part_no': 'ZC.A01SI.1B6',
    'product_group': 'other_products',
    'rating': 4.3,
    'review_count': 49,
    'sort_order': 71,
    'stock_status': 'In Stock',
    'title': 'Acer Sling Bag Grey (ZC.A01SI.1B6)',
    'url_slug': 'acer-sling-bag-grey-zc-a01si-1b6'},
    {   'amazon_link': 'https://amzn.in/d/0736fmpt',
    'asin': 'B0FWYRSPNB',
    'base_price': 998.0,
    'category': 'Backpacks & Sleeves',
    'image_url': 'https://m.media-amazon.com/images/I/71MOWm9++oL._SL1500_.jpg',
    'model': 'Acer Sling Bag Black',
    'mrp': 3999.0,
    'part_no': 'ZC.A01SI.3LA',
    'product_group': 'other_products',
    'rating': 4.2,
    'review_count': 182,
    'sort_order': 72,
    'stock_status': 'In Stock',
    'title': 'Acer Sling Bag Black (ZC.A01SI.3LA)',
    'url_slug': 'acer-sling-bag-black-zc-a01si-3la'},
    {   'amazon_link': 'https://amzn.in/d/0ih18G5u',
    'asin': 'B0GKC55B4H',
    'base_price': 1899.0,
    'category': 'Backpacks & Sleeves',
    'image_url': 'https://m.media-amazon.com/images/I/71kzj5TWOXL._SL1500_.jpg',
    'model': 'Acer ChargeMate 4-in-1 Wireless Charging Laptop Sleeve - Grey',
    'mrp': 3000.0,
    'part_no': 'ZC.A01SI.3LJ',
    'product_group': 'other_products',
    'rating': 3.7,
    'review_count': 45,
    'sort_order': 73,
    'stock_status': 'In Stock',
    'title': 'Acer ChargeMate 4-in-1 Wireless Charging Laptop Sleeve - Grey (ZC.A01SI.3LJ)',
    'url_slug': 'acer-chargemate-4-in-1-wireless-charging-laptop-sl'},
    {   'amazon_link': 'https://amzn.in/d/0ii9l0h2',
    'asin': 'B0GKBXTL5S',
    'base_price': 1899.0,
    'category': 'Backpacks & Sleeves',
    'image_url': 'https://m.media-amazon.com/images/I/71tDHc4po7L._SL1500_.jpg',
    'model': 'Acer ChargeMate 4-in-1 Wireless Charging Laptop Sleeve - Black',
    'mrp': 3000.0,
    'part_no': 'ZC.A01SI.3LK',
    'product_group': 'other_products',
    'rating': 3.7,
    'review_count': 45,
    'sort_order': 74,
    'stock_status': 'In Stock',
    'title': 'Acer ChargeMate 4-in-1 Wireless Charging Laptop Sleeve - Black (ZC.A01SI.3LK)',
    'url_slug': 'acer-chargemate-4-in-1-wireless-charging-laptop-sl'},
    {   'amazon_link': 'https://amzn.in/d/0acVoJ1E',
    'asin': 'B0FX5HWSWD',
    'base_price': 784.0,
    'category': 'Backpacks & Sleeves',
    'image_url': 'https://m.media-amazon.com/images/I/71JS7IA6aOL._SL1500_.jpg',
    'model': 'Acer Cross Body Bag',
    'mrp': 1599.0,
    'part_no': 'ZC.A01SI.3HB',
    'product_group': 'other_products',
    'rating': 4.4,
    'review_count': 37,
    'sort_order': 75,
    'stock_status': 'In Stock',
    'title': 'Acer Cross Body Bag (ZC.A01SI.3HB)',
    'url_slug': 'acer-cross-body-bag-zc-a01si-3hb'},
    {   'amazon_link': 'https://amzn.in/d/029BJiPl',
    'asin': 'B0FXV4PWJ9',
    'base_price': 1444.0,
    'category': 'Backpacks & Sleeves',
    'image_url': 'https://m.media-amazon.com/images/I/815Zn+MH1nL._SL1500_.jpg',
    'model': 'Acer UrbanLite Slim',
    'mrp': 2999.0,
    'part_no': 'ZC.A01SI.3BV',
    'product_group': 'other_products',
    'rating': 4.4,
    'review_count': 53,
    'sort_order': 76,
    'stock_status': 'In Stock',
    'title': 'Acer UrbanLite Slim (ZC.A01SI.3BV)',
    'url_slug': 'acer-urbanlite-slim-zc-a01si-3bv'},
    {   'amazon_link': 'https://amzn.in/d/09VAgml9',
    'asin': 'B0F6V5YMKJ',
    'base_price': 508.0,
    'category': 'Backpacks & Sleeves',
    'image_url': 'https://m.media-amazon.com/images/I/81RL4Ewy9ML._SL1500_.jpg',
    'model': 'Acer Pulse Backpack Yellow/Navy blue',
    'mrp': 999.0,
    'part_no': 'ZC.A01SI.21X',
    'product_group': 'other_products',
    'rating': 3.8,
    'review_count': 169,
    'sort_order': 77,
    'stock_status': 'In Stock',
    'title': 'Acer Pulse Backpack Yellow/Navy blue (ZC.A01SI.21X)',
    'url_slug': 'acer-pulse-backpack-yellow-navy-blue-zc-a01si-21x'},
    {   'amazon_link': 'https://amzn.in/d/07a22lJr',
    'asin': 'B0F6VGF7K1',
    'base_price': 799.0,
    'category': 'Backpacks & Sleeves',
    'image_url': 'https://m.media-amazon.com/images/I/81aEpO3s50L._SL1500_.jpg',
    'model': 'Acer Pulse Backpack Silver/Navy blue',
    'mrp': 999.0,
    'part_no': 'ZC.A01SI.21Y',
    'product_group': 'other_products',
    'rating': 3.8,
    'review_count': 169,
    'sort_order': 78,
    'stock_status': 'Out of Stock',
    'title': 'Acer Pulse Backpack Silver/Navy blue (ZC.A01SI.21Y)',
    'url_slug': 'acer-pulse-backpack-silver-navy-blue-zc-a01si-21y'},
    {   'amazon_link': 'https://amzn.in/d/0anqBsVY',
    'asin': 'B0G1CX438C',
    'base_price': 999.0,
    'category': 'Backpacks & Sleeves',
    'image_url': 'https://m.media-amazon.com/images/I/81554-3L0uL._SL1500_.jpg',
    'model': 'Acer Pulse Backpack Black / Maroon',
    'mrp': 2499.0,
    'part_no': 'ZC.A01SI.3VP',
    'product_group': 'other_products',
    'rating': 3.8,
    'review_count': 169,
    'sort_order': 79,
    'stock_status': 'In Stock',
    'title': 'Acer Pulse Backpack Black / Maroon (ZC.A01SI.3VP)',
    'url_slug': 'acer-pulse-backpack-black-maroon-zc-a01si-3vp'},
    {   'amazon_link': 'https://amzn.in/d/0hVfDqZG',
    'asin': 'B0F3TJZ9JG',
    'base_price': 3999.0,
    'category': 'Backpacks & Sleeves',
    'image_url': 'https://m.media-amazon.com/images/I/61uq1vvbtLL._SL1500_.jpg',
    'model': 'Acer Swift 2 in one Convertible Backpack ( Navy Blue)',
    'mrp': 4999.0,
    'part_no': 'ZC.A01SI.1KE',
    'product_group': 'other_products',
    'rating': 4.5,
    'review_count': 38,
    'sort_order': 80,
    'stock_status': 'In Stock',
    'title': 'Acer Swift 2 in one Convertible Backpack ( Navy Blue) (ZC.A01SI.1KE)',
    'url_slug': 'acer-swift-2-in-one-convertible-backpack-navy-blue'},
    {   'amazon_link': 'https://amzn.in/d/0dHU9YZv',
    'asin': 'B0F3TQ9655',
    'base_price': 1265.0,
    'category': 'Backpacks & Sleeves',
    'image_url': 'https://m.media-amazon.com/images/I/61fk7P3g9HL._SL1500_.jpg',
    'model': 'Acer Swift 2 in one Convertible Backpack (TAN)',
    'mrp': 4999.0,
    'part_no': 'ZC.A01SI.1KF',
    'product_group': 'other_products',
    'rating': 4.5,
    'review_count': 38,
    'sort_order': 81,
    'stock_status': 'In Stock',
    'title': 'Acer Swift 2 in one Convertible Backpack (TAN) (ZC.A01SI.1KF)',
    'url_slug': 'acer-swift-2-in-one-convertible-backpack-tan-zc-a0'},
    {   'amazon_link': 'https://amzn.in/d/0iNKWFIP',
    'asin': 'B0FGQ2QD59',
    'base_price': 3302.0,
    'category': 'Backpacks & Sleeves',
    'image_url': 'https://m.media-amazon.com/images/I/81qjCRAw8YL._SL1500_.jpg',
    'model': 'Acer Premium Business Laptop Backpack',
    'mrp': 8999.0,
    'part_no': 'ZC.A01SI.1QP',
    'product_group': 'other_products',
    'rating': 4.6,
    'review_count': 52,
    'sort_order': 82,
    'stock_status': 'In Stock',
    'title': 'Acer Premium Business Laptop Backpack (ZC.A01SI.1QP)',
    'url_slug': 'acer-premium-business-laptop-backpack-zc-a01si-1qp'},
    {   'amazon_link': 'https://amzn.in/d/0bibRtB8',
    'asin': 'B0FGPTK1N8',
    'base_price': 1615.0,
    'category': 'Backpacks & Sleeves',
    'image_url': 'https://m.media-amazon.com/images/I/81c7V8ALeGL._SL1500_.jpg',
    'model': 'Acer Premium Professional Laptop Backpack',
    'mrp': 8999.0,
    'part_no': 'ZC.A01SI.1QQ',
    'product_group': 'other_products',
    'rating': 3.6,
    'review_count': 10,
    'sort_order': 83,
    'stock_status': 'In Stock',
    'title': 'Acer Premium Professional Laptop Backpack (ZC.A01SI.1QQ)',
    'url_slug': 'acer-premium-professional-laptop-backpack-zc-a01si'},
    {   'amazon_link': 'https://amzn.in/d/0j5fMhx6',
    'asin': 'B0GRSB3DNX',
    'base_price': 5998.0,
    'category': 'Backpacks & Sleeves',
    'image_url': 'https://m.media-amazon.com/images/I/71LIdOGincL._SL1500_.jpg',
    'model': 'Acer VacuPack Backpack',
    'mrp': 9999.0,
    'part_no': 'ZC.A01SI.4MB',
    'product_group': 'other_products',
    'rating': 4.2,
    'review_count': 21,
    'sort_order': 84,
    'stock_status': 'In Stock',
    'title': 'Acer VacuPack Backpack (ZC.A01SI.4MB)',
    'url_slug': 'acer-vacupack-backpack-zc-a01si-4mb'},
    {   'amazon_link': 'https://amzn.in/d/0epw1kGk',
    'asin': 'B0FDKXG11W',
    'base_price': 1968.0,
    'category': 'Power & Cable Management',
    'image_url': 'https://m.media-amazon.com/images/I/61luv7mjsGL._SL1500_.jpg',
    'model': 'Management Power Strip',
    'mrp': 3999.0,
    'part_no': 'ZC.A01SI.2P1',
    'product_group': 'other_products',
    'rating': 4.3,
    'review_count': 48,
    'sort_order': 85,
    'stock_status': 'In Stock',
    'title': 'Management Power Strip (ZC.A01SI.2P1)',
    'url_slug': 'management-power-strip-zc-a01si-2p1'},
    {   'amazon_link': 'https://amzn.in/d/00SX8Ctx',
    'asin': 'B0FDKWY2TS',
    'base_price': 2239.0,
    'category': 'Power & Cable Management',
    'image_url': 'https://m.media-amazon.com/images/I/61rMD55JqgL._SL1500_.jpg',
    'model': 'Wifi Smart Power Strip',
    'mrp': 3999.0,
    'part_no': 'ZC.A01SI.2P2',
    'product_group': 'other_products',
    'rating': 3.8,
    'review_count': 81,
    'sort_order': 86,
    'stock_status': 'In Stock',
    'title': 'Wifi Smart Power Strip (ZC.A01SI.2P2)',
    'url_slug': 'wifi-smart-power-strip-zc-a01si-2p2'},
    {   'amazon_link': 'https://amzn.in/d/0h32ZOIv',
    'asin': 'B0FDKXXQHH',
    'base_price': 1499.0,
    'category': 'Power & Cable Management',
    'image_url': 'https://m.media-amazon.com/images/I/614zwFtp-uL._SL1500_.jpg',
    'model': 'Tower Extension',
    'mrp': 2499.0,
    'part_no': 'ZC.A01SI.2P3',
    'product_group': 'other_products',
    'rating': 4.4,
    'review_count': 113,
    'sort_order': 87,
    'stock_status': 'Out of Stock',
    'title': 'Tower Extension (ZC.A01SI.2P3)',
    'url_slug': 'tower-extension-zc-a01si-2p3'},
    {   'amazon_link': 'https://amzn.in/d/04WN2Fzz',
    'asin': 'B0FDKYVCPP',
    'base_price': 2385.0,
    'category': 'Power & Cable Management',
    'image_url': 'https://m.media-amazon.com/images/I/61dspGUaE3L._SL1500_.jpg',
    'model': 'Tubo GaN Strip',
    'mrp': 3599.0,
    'part_no': 'ZC.A01SI.2P4',
    'product_group': 'other_products',
    'rating': 4.1,
    'review_count': 74,
    'sort_order': 88,
    'stock_status': 'In Stock',
    'title': 'Tubo GaN Strip (ZC.A01SI.2P4)',
    'url_slug': 'tubo-gan-strip-zc-a01si-2p4'},
    {   'amazon_link': 'https://amzn.in/d/0jcSu0LD',
    'asin': 'B0DMP3Q1TV',
    'base_price': 407.0,
    'category': 'Privacy Screens',
    'image_url': 'https://m.media-amazon.com/images/I/71qmsxQUeyL._SL1500_.jpg',
    'model': 'Acer 14" Privacy Screen (ASF14W9AC-80)',
    'mrp': 4999.0,
    'part_no': 'ZC.A01SI.18A',
    'product_group': 'other_products',
    'rating': 3.6,
    'review_count': 9,
    'sort_order': 89,
    'stock_status': 'In Stock',
    'title': 'Acer 14" Privacy Screen (ASF14W9AC-80) (ZC.A01SI.18A)',
    'url_slug': 'acer-14-privacy-screen-asf14w9ac-80-zc-a01si-18a'},
    {   'amazon_link': 'https://amzn.in/d/0bixuE7R',
    'asin': 'B0DMP1272V',
    'base_price': 556.0,
    'category': 'Privacy Screens',
    'image_url': 'https://m.media-amazon.com/images/I/716vp8GnGAL._SL1500_.jpg',
    'model': 'Acer 15.6" Privacy Screen (ASF14W9AC-80)',
    'mrp': 5999.0,
    'part_no': 'ZC.A01SI.18B',
    'product_group': 'other_products',
    'rating': 3.5,
    'review_count': 4,
    'sort_order': 90,
    'stock_status': 'In Stock',
    'title': 'Acer 15.6" Privacy Screen (ASF14W9AC-80) (ZC.A01SI.18B)',
    'url_slug': 'acer-15-6-privacy-screen-asf14w9ac-80-zc-a01si-18b'},
]

# Unified portfolio list (strictly ordered 1 to 90)
ACER_SEED_PRODUCTS = ACER_MONITOR_SEED_PRODUCTS + ACER_OTHER_SEED_PRODUCTS
ALL_SEED_PRODUCTS = ACER_SEED_PRODUCTS
