# ACER PRODUCTS CATALOG & SEED DATA
# Reordered to strictly match amazon acer accessories .xlsx (1-90)
# Live Amazon India Verified Pricing & Metadata

ACER_SEED_PRODUCTS = [
    {   'amazon_link': 'https://amzn.in/d/0gFTTe4f',
    'asin': 'B0DNNLW8MK',
    'base_price': 429.0,
    'category': 'Wireless & Wired Mice',
    'image_url': 'https://m.media-amazon.com/images/I/71YJjGWaGHL._SL1500_.jpg',
    'mrp': 999.0,
    'part_no': 'ZC.A01SI.18F',
    'product_group': 'other_products',
    'rating': 3.7,
    'review_count': 101,
    'sort_order': 1,
    'stock_status': 'In Stock',
    'title': 'Acer ClearView Transparent Mouse - Green (ZC.A01SI.18F)',
    'url_slug': 'acer-clearview-transparent-mouse-green-zc-a01si-18'},
    {   'amazon_link': 'https://amzn.in/d/096DqpWo',
    'asin': 'B0DNNLWB1V',
    'base_price': 428.0,
    'category': 'Wireless & Wired Mice',
    'image_url': 'https://m.media-amazon.com/images/I/61gqfGpXVzL._SL1500_.jpg',
    'mrp': 999.0,
    'part_no': 'ZC.A01SI.18D',
    'product_group': 'other_products',
    'rating': 3.6,
    'review_count': 37,
    'sort_order': 2,
    'stock_status': 'In Stock',
    'title': 'Acer ClearView Transparent Mouse - White (ZC.A01SI.18D)',
    'url_slug': 'acer-clearview-transparent-mouse-white-zc-a01si-18'},
    {   'amazon_link': 'https://amzn.in/d/02vcJ7aV',
    'asin': 'B0DNNLNTHY',
    'base_price': 399.0,
    'category': 'Wireless & Wired Mice',
    'image_url': 'https://m.media-amazon.com/images/I/71OflSCvFYL._SL1500_.jpg',
    'mrp': 999.0,
    'part_no': 'ZC.A01SI.18E',
    'product_group': 'other_products',
    'rating': 3.7,
    'review_count': 101,
    'sort_order': 3,
    'stock_status': 'In Stock',
    'title': 'Acer ClearView Transparent Mouse - Blue (ZC.A01SI.18E)',
    'url_slug': 'acer-clearview-transparent-mouse-blue-zc-a01si-18e'},
    {   'amazon_link': 'https://amzn.in/d/02klBboU',
    'asin': 'B0H5XK7SRG',
    'base_price': 399.0,
    'category': 'Wireless & Wired Mice',
    'image_url': 'https://m.media-amazon.com/images/I/71Oo+Q016SL._SL1500_.jpg',
    'mrp': 999.0,
    'part_no': 'ZC.A01SI.4WE',
    'product_group': 'other_products',
    'rating': 3.7,
    'review_count': 101,
    'sort_order': 4,
    'stock_status': 'In Stock',
    'title': 'Acer ClearView Transparent Mouse - Black (ZC.A01SI.4WE)',
    'url_slug': 'acer-clearview-transparent-mouse-black-zc-a01si-4w'},
    {   'amazon_link': 'https://amzn.in/d/01WsvzuO',
    'asin': 'B0FCFW7QB5',
    'base_price': 580.0,
    'category': 'Wireless & Wired Mice',
    'image_url': 'https://m.media-amazon.com/images/I/71qh6BvmAsL._SL1500_.jpg',
    'mrp': 999.0,
    'part_no': 'ZC.A01SI.2DR',
    'product_group': 'other_products',
    'rating': 4.3,
    'review_count': 483,
    'sort_order': 5,
    'stock_status': 'In Stock',
    'title': 'Wireless Transparent Rechargeable Mouse  Grey OS (ZC.A01SI.2DR)',
    'url_slug': 'wireless-transparent-rechargeable-mouse-grey-os-zc'},
    {   'amazon_link': 'https://amzn.in/d/04hQzsx1',
    'asin': 'B0FCFW9LNG',
    'base_price': 495.0,
    'category': 'Wireless & Wired Mice',
    'image_url': 'https://m.media-amazon.com/images/I/71NVFIKSliL._SL1500_.jpg',
    'mrp': 999.0,
    'part_no': 'ZC.A01SI.2DT',
    'product_group': 'other_products',
    'rating': 4.3,
    'review_count': 483,
    'sort_order': 6,
    'stock_status': 'In Stock',
    'title': 'Wireless Transparent Rechargeable Mouse  Peach OS (ZC.A01SI.2DT)',
    'url_slug': 'wireless-transparent-rechargeable-mouse-peach-os-z'},
    {   'amazon_link': 'https://amzn.in/d/0d8sfi77',
    'asin': 'B0D378LN1J',
    'base_price': 315.0,
    'category': 'Wireless & Wired Mice',
    'image_url': 'https://m.media-amazon.com/images/I/41wDHNWqqmL._SL1000_.jpg',
    'mrp': 1499.0,
    'part_no': '5W.50611.004',
    'product_group': 'other_products',
    'rating': 4.2,
    'review_count': 1327,
    'sort_order': 7,
    'stock_status': 'In Stock',
    'title': 'Acer Wireless Mouse White Green (5W.50611.004)',
    'url_slug': 'acer-wireless-mouse-white-green-5w-50611-004'},
    {   'amazon_link': 'https://amzn.in/d/01HTqM53',
    'asin': 'B0D7VSW3W9',
    'base_price': 355.0,
    'category': 'Wireless & Wired Mice',
    'image_url': 'https://m.media-amazon.com/images/I/51zKXH9e23L._SL1500_.jpg',
    'mrp': 1499.0,
    'part_no': 'ZC.A01SI.0WB',
    'product_group': 'other_products',
    'rating': 4.2,
    'review_count': 1327,
    'sort_order': 8,
    'stock_status': 'In Stock',
    'title': 'Acer Wireless Mouse, White Orange (ZC.A01SI.0WB)',
    'url_slug': 'acer-wireless-mouse-white-orange-zc-a01si-0wb'},
    {   'amazon_link': 'https://amzn.in/d/05Fir8bg',
    'asin': 'B0DJBK21X7',
    'base_price': 355.0,
    'category': 'Wireless & Wired Mice',
    'image_url': 'https://m.media-amazon.com/images/I/51jOAM8+8zL._SL1500_.jpg',
    'mrp': 1499.0,
    'part_no': 'ZC.A01SI.0WC',
    'product_group': 'other_products',
    'rating': 4.2,
    'review_count': 1327,
    'sort_order': 9,
    'stock_status': 'In Stock',
    'title': 'Acer Wireless Mouse, White Blue (ZC.A01SI.0WC)',
    'url_slug': 'acer-wireless-mouse-white-blue-zc-a01si-0wc'},
    {   'amazon_link': 'https://amzn.in/d/0iGTa5NW',
    'asin': 'B0FQQMSRP8',
    'base_price': 355.0,
    'category': 'Wireless & Wired Mice',
    'image_url': 'https://m.media-amazon.com/images/I/71cWw7ip0qL._SL1500_.jpg',
    'mrp': 1499.0,
    'part_no': 'ZC.A01SI.3S8',
    'product_group': 'other_products',
    'rating': 4.2,
    'review_count': 1327,
    'sort_order': 10,
    'stock_status': 'In Stock',
    'title': 'Acer Wireless Mouse, Black/Red (ZC.A01SI.3S8)',
    'url_slug': 'acer-wireless-mouse-black-red-zc-a01si-3s8'},
    {   'amazon_link': 'https://amzn.in/d/0drqvfM7',
    'asin': 'B0FPDKR4GX',
    'base_price': 598.0,
    'category': 'Wireless & Wired Mice',
    'image_url': 'https://m.media-amazon.com/images/I/61MecoKNwDL._SL1500_.jpg',
    'mrp': 1499.0,
    'part_no': 'ZC.A01SI.2ZQ',
    'product_group': 'other_products',
    'rating': 4.4,
    'review_count': 203,
    'sort_order': 11,
    'stock_status': 'In Stock',
    'title': 'Acer Prism Wireless Rechargeable Mouse - Black (ZC.A01SI.2ZQ)',
    'url_slug': 'acer-prism-wireless-rechargeable-mouse-black-zc-a0'},
    {   'amazon_link': 'https://amzn.in/d/02zAZaxY',
    'asin': 'B0GYT9GRFW',
    'base_price': 799.0,
    'category': 'Wireless & Wired Mice',
    'image_url': 'https://m.media-amazon.com/images/I/71vQ4nDMN8L._SL1500_.jpg',
    'mrp': 1499.0,
    'part_no': 'ZC.A01SI.4R7',
    'product_group': 'other_products',
    'rating': 4.4,
    'review_count': 203,
    'sort_order': 12,
    'stock_status': 'Out of Stock',
    'title': 'Acer Prism Wireless Rechargeable Mouse - Yellow (ZC.A01SI.4R7)',
    'url_slug': 'acer-prism-wireless-rechargeable-mouse-yellow-zc-a'},
    {   'amazon_link': 'https://amzn.in/d/0iA8VsbU',
    'asin': 'B0FPDJYKBX',
    'base_price': 799.0,
    'category': 'Wireless & Wired Mice',
    'image_url': 'https://m.media-amazon.com/images/I/615BCc-qFqL._SL1500_.jpg',
    'mrp': 1499.0,
    'part_no': 'ZC.A01SI.2ZP',
    'product_group': 'other_products',
    'rating': 4.4,
    'review_count': 203,
    'sort_order': 13,
    'stock_status': 'Out of Stock',
    'title': 'Acer Prism Wireless Rechargeable Mouse - White (ZC.A01SI.2ZP)',
    'url_slug': 'acer-prism-wireless-rechargeable-mouse-white-zc-a0'},
    {   'amazon_link': 'https://amzn.in/d/03p9eVRt',
    'asin': 'B0FRZ85XH1',
    'base_price': 998.0,
    'category': 'Wireless & Wired Mice',
    'image_url': 'https://m.media-amazon.com/images/I/61TAZuSmL+L._SL1500_.jpg',
    'mrp': 2000.0,
    'part_no': 'ZC.A01SI.393',
    'product_group': 'other_products',
    'rating': 3.8,
    'review_count': 186,
    'sort_order': 14,
    'stock_status': 'In Stock',
    'title': 'Acer Ergo Vertical Wireless Mouse - White (ZC.A01SI.393)',
    'url_slug': 'acer-ergo-vertical-wireless-mouse-white-zc-a01si-3'},
    {   'amazon_link': 'https://amzn.in/d/0byavpY9',
    'asin': 'B0FRZ861L9',
    'base_price': 998.0,
    'category': 'Wireless & Wired Mice',
    'image_url': 'https://m.media-amazon.com/images/I/717BUFALtgL._SL1500_.jpg',
    'mrp': 2000.0,
    'part_no': 'ZC.A01SI.394',
    'product_group': 'other_products',
    'rating': 3.8,
    'review_count': 186,
    'sort_order': 15,
    'stock_status': 'In Stock',
    'title': 'Acer Ergo Vertical Wireless Mouse - Grey (ZC.A01SI.394)',
    'url_slug': 'acer-ergo-vertical-wireless-mouse-grey-zc-a01si-39'},
    {   'amazon_link': 'https://amzn.in/d/0dYfjK4d',
    'asin': 'B0FKPCRVCZ',
    'base_price': 499.0,
    'category': 'Wireless & Wired Mice',
    'image_url': 'https://m.media-amazon.com/images/I/71XWRGOzb-L._SL1500_.jpg',
    'mrp': 999.0,
    'part_no': 'ZC.A01SI.2N0',
    'product_group': 'other_products',
    'rating': 4.3,
    'review_count': 871,
    'sort_order': 16,
    'stock_status': 'Out of Stock',
    'title': 'Bubble Mouse Blue/Green (ZC.A01SI.2N0)',
    'url_slug': 'bubble-mouse-blue-green-zc-a01si-2n0'},
    {   'amazon_link': 'https://amzn.in/d/05zCkpwR',
    'asin': 'B0FKPXG5R8',
    'base_price': 499.0,
    'category': 'Wireless & Wired Mice',
    'image_url': 'https://m.media-amazon.com/images/I/71RaUC00idL._SL1500_.jpg',
    'mrp': 999.0,
    'part_no': 'ZC.A01SI.2N1',
    'product_group': 'other_products',
    'rating': 4.3,
    'review_count': 871,
    'sort_order': 17,
    'stock_status': 'In Stock',
    'title': 'Bubble Mouse Peach (ZC.A01SI.2N1)',
    'url_slug': 'bubble-mouse-peach-zc-a01si-2n1'},
    {   'amazon_link': 'https://amzn.in/d/0iDzqvS3',
    'asin': 'B0FKPNYY9Z',
    'base_price': 499.0,
    'category': 'Wireless & Wired Mice',
    'image_url': 'https://m.media-amazon.com/images/I/61Wr9tOYxRL._SL1500_.jpg',
    'mrp': 999.0,
    'part_no': 'ZC.A01SI.2MZ',
    'product_group': 'other_products',
    'rating': 4.3,
    'review_count': 871,
    'sort_order': 18,
    'stock_status': 'Out of Stock',
    'title': 'Bubble Mouse White (ZC.A01SI.2MZ)',
    'url_slug': 'bubble-mouse-white-zc-a01si-2mz'},
    {   'amazon_link': 'https://amzn.in/d/01DqOKBG',
    'asin': 'B0GQVQF9YQ',
    'base_price': 698.0,
    'category': 'Wireless & Wired Mice',
    'image_url': 'https://m.media-amazon.com/images/I/71AmPFtYmHL._SL1500_.jpg',
    'mrp': 1599.0,
    'part_no': 'ZC.A01SI.3ZE',
    'product_group': 'other_products',
    'rating': 4.2,
    'review_count': 114,
    'sort_order': 19,
    'stock_status': 'In Stock',
    'title': 'PopGo Wireless Mouse | 2.4G + BT5.4 Dual Mode (ZC.A01SI.3ZE)',
    'url_slug': 'popgo-wireless-mouse-2-4g-bt5-4-dual-mode-zc-a01si'},
    {   'amazon_link': 'https://amzn.in/d/0hb3pkuS',
    'asin': 'B0H83FL8CJ',
    'base_price': 1499.0,
    'category': 'Gaming Mice',
    'image_url': 'https://m.media-amazon.com/images/I/61qjtyIv4lL._SL1500_.jpg',
    'mrp': 2499.0,
    'part_no': 'ZC.A01SI.4ND',
    'product_group': 'other_products',
    'rating': 4.4,
    'review_count': 310,
    'sort_order': 20,
    'stock_status': 'Out of Stock',
    'title': 'Acer Nitro Phantom X12 Tri-Mode Gaming Mouse (ZC.A01SI.4ND)',
    'url_slug': 'acer-nitro-phantom-x12-tri-mode-gaming-mouse-zc-a0'},
    {   'amazon_link': 'https://amzn.in/d/0a2asTCM',
    'asin': 'B0H83548VY',
    'base_price': 899.0,
    'category': 'Gaming Mice',
    'image_url': 'https://m.media-amazon.com/images/I/61JNCNvVtXL._SL1500_.jpg',
    'mrp': 1799.0,
    'part_no': 'ZC.A01SI.4NE',
    'product_group': 'other_products',
    'rating': 4.4,
    'review_count': 310,
    'sort_order': 21,
    'stock_status': 'Out of Stock',
    'title': 'Acer Nitro Phantom X7 Wired Gaming Mouse | 7200 DPI (ZC.A01SI.4NE)',
    'url_slug': 'acer-nitro-phantom-x7-wired-gaming-mouse-7200-dpi-'},
    {   'amazon_link': 'https://amzn.in/d/0iHFtpej',
    'asin': 'B0G5FM1C7J',
    'base_price': 899.0,
    'category': 'Gaming Mice',
    'image_url': 'https://m.media-amazon.com/images/I/61eU9U99ASL._SL1500_.jpg',
    'mrp': 2999.0,
    'part_no': 'ZC.A01SI.3RX',
    'product_group': 'other_products',
    'rating': 4.4,
    'review_count': 19,
    'sort_order': 22,
    'stock_status': 'In Stock',
    'title': 'Nitro 7 Gaming Mouse (ZC.A01SI.3RX)',
    'url_slug': 'nitro-7-gaming-mouse-zc-a01si-3rx'},
    {   'amazon_link': 'https://amzn.in/d/0cs3yrH9',
    'asin': 'B0G5FFNPDN',
    'base_price': 575.0,
    'category': 'Gaming Mice',
    'image_url': 'https://m.media-amazon.com/images/I/613sMu0LojL._SL1500_.jpg',
    'mrp': 1999.0,
    'part_no': 'ZC.A01SI.3RY',
    'product_group': 'other_products',
    'rating': 4.1,
    'review_count': 28,
    'sort_order': 23,
    'stock_status': 'Only 1 left in stock.',
    'title': 'Acer Titan X Gaming Mouse (ZC.A01SI.3RY)',
    'url_slug': 'acer-titan-x-gaming-mouse-zc-a01si-3ry'},
    {   'amazon_link': 'https://amzn.in/d/0dZscBFB',
    'asin': 'B0DP4M69WM',
    'base_price': 1495.0,
    'category': 'Keyboards',
    'image_url': 'https://m.media-amazon.com/images/I/81vlxcYQIJL._SL1500_.jpg',
    'mrp': 3500.0,
    'part_no': 'ZC.A01SI.18K',
    'product_group': 'other_products',
    'rating': 3.9,
    'review_count': 175,
    'sort_order': 24,
    'stock_status': 'In Stock',
    'title': 'ACER Wireless Rechargeable Keyboard BLACK with GREEN cradle ACR101 (ZC.A01SI.18K)',
    'url_slug': 'acer-wireless-rechargeable-keyboard-black-with-gre'},
    {   'amazon_link': 'https://amzn.in/d/0db8lr4G',
    'asin': 'B0DP1FCHQ9',
    'base_price': 1995.0,
    'category': 'Keyboards',
    'image_url': 'https://m.media-amazon.com/images/I/81ma1RrYczL._SL1500_.jpg',
    'mrp': 4000.0,
    'part_no': 'ZC.A01SI.18J',
    'product_group': 'other_products',
    'rating': 3.6,
    'review_count': 352,
    'sort_order': 25,
    'stock_status': 'In Stock',
    'title': 'ACER ClearView Wireless Rechargeable Keyboard SILVER ACR100 (ZC.A01SI.18J)',
    'url_slug': 'acer-clearview-wireless-rechargeable-keyboard-silv'},
    {   'amazon_link': 'https://amzn.in/d/0ah5sBet',
    'asin': 'B0GRJXKCRQ',
    'base_price': 1698.0,
    'category': 'Keyboards',
    'image_url': 'https://m.media-amazon.com/images/I/71I4S3Nt7qL._SL1500_.jpg',
    'mrp': 2999.0,
    'part_no': 'ZC.A01SI.3ZF',
    'product_group': 'other_products',
    'rating': 4.3,
    'review_count': 75,
    'sort_order': 26,
    'stock_status': 'In Stock',
    'title': 'Acer KeyPro Wireless Dual Mode Keyboard - Space Grey (ZC.A01SI.3ZF)',
    'url_slug': 'acer-keypro-wireless-dual-mode-keyboard-space-grey'},
    {   'amazon_link': 'https://amzn.in/d/05dx2Scc',
    'asin': 'B0GRJX27DG',
    'base_price': 1698.0,
    'category': 'Keyboards',
    'image_url': 'https://m.media-amazon.com/images/I/71v9YOES30L._SL1500_.jpg',
    'mrp': 2999.0,
    'part_no': 'ZC.A01SI.3ZG',
    'product_group': 'other_products',
    'rating': 4.3,
    'review_count': 75,
    'sort_order': 27,
    'stock_status': 'In Stock',
    'title': 'Acer KeyPro Wireless Dual Mode Keyboard - Silver (ZC.A01SI.3ZG)',
    'url_slug': 'acer-keypro-wireless-dual-mode-keyboard-silver-zc-'},
    {   'amazon_link': 'https://amzn.in/d/04lyF1ax',
    'asin': 'B0FG94XRNK',
    'base_price': 2299.0,
    'category': 'Keyboards',
    'image_url': 'https://m.media-amazon.com/images/I/71+U+2hRXXL._SL1500_.jpg',
    'mrp': 3499.0,
    'part_no': 'ZC.A01SI.224',
    'product_group': 'other_products',
    'rating': 3.9,
    'review_count': 143,
    'sort_order': 28,
    'stock_status': 'Out of Stock',
    'title': 'ACER Wireless Rechargeable Keyboard BLACK with GREEN cradle and Touchpad (ZC.A01SI.224)',
    'url_slug': 'acer-wireless-rechargeable-keyboard-black-with-gre'},
    {   'amazon_link': 'https://amzn.in/d/02knIdjO',
    'asin': 'B0FG995CZS',
    'base_price': 1113.0,
    'category': 'Keyboards',
    'image_url': 'https://m.media-amazon.com/images/I/71fMrvjPbfL._SL1500_.jpg',
    'mrp': 3699.0,
    'part_no': 'ZC.A01SI.225',
    'product_group': 'other_products',
    'rating': 3.8,
    'review_count': 35,
    'sort_order': 29,
    'stock_status': 'In Stock',
    'title': 'Acer Wireless Rechargeable Keyboard with cradle and Numpad - off white colored keys (ZC.A01SI.225)',
    'url_slug': 'acer-wireless-rechargeable-keyboard-with-cradle-an'},
    {   'amazon_link': 'https://amzn.in/d/0dnY3fzz',
    'asin': 'B0F9PLCSKL',
    'base_price': 2299.0,
    'category': 'Keyboards',
    'image_url': 'https://m.media-amazon.com/images/I/71V0dJYfCeL._SL1500_.jpg',
    'mrp': 3499.0,
    'part_no': 'ZC.A01SI.1LH',
    'product_group': 'other_products',
    'rating': 4.0,
    'review_count': 18,
    'sort_order': 30,
    'stock_status': 'Out of Stock',
    'title': 'Acer Solar Keyboard (ZC.A01SI.1LH)',
    'url_slug': 'acer-solar-keyboard-zc-a01si-1lh'},
    {   'amazon_link': 'https://amzn.in/d/07t1OXTz',
    'asin': 'B0H18M1KZ5',
    'base_price': 1199.0,
    'category': 'Keyboards',
    'image_url': 'https://m.media-amazon.com/images/I/71lSEaT0jsL._SL1500_.jpg',
    'mrp': 1999.0,
    'part_no': 'ZC.A01SI.4VY',
    'product_group': 'other_products',
    'rating': 4.0,
    'review_count': 24,
    'sort_order': 31,
    'stock_status': 'Out of Stock',
    'title': 'Acer SoftKey Pro Wireless Keyboard | 2.4GHz (ZC.A01SI.4VY)',
    'url_slug': 'acer-softkey-pro-wireless-keyboard-2-4ghz-zc-a01si'},
    {   'amazon_link': 'https://amzn.in/d/0j4CJByc',
    'asin': 'B0FTZXFSH1',
    'base_price': 1999.0,
    'category': 'Keyboards',
    'image_url': 'https://m.media-amazon.com/images/I/81ZdVORcT9L._SL1500_.jpg',
    'mrp': 2599.0,
    'part_no': 'ZC.A01SI.39X',
    'product_group': 'other_products',
    'rating': 3.5,
    'review_count': 34,
    'sort_order': 32,
    'stock_status': 'In Stock',
    'title': 'Acer Trifold Pro | 60 Keys Foldable (ZC.A01SI.39X)',
    'url_slug': 'acer-trifold-pro-60-keys-foldable-zc-a01si-39x'},
    {   'amazon_link': 'https://amzn.in/d/07fZITfY',
    'asin': 'B0FTZX7RP8',
    'base_price': 2098.0,
    'category': 'Keyboards',
    'image_url': 'https://m.media-amazon.com/images/I/81n5tV9xFEL._SL1500_.jpg',
    'mrp': 2999.0,
    'part_no': 'ZC.A01SI.39Y',
    'product_group': 'other_products',
    'rating': 3.4,
    'review_count': 40,
    'sort_order': 33,
    'stock_status': 'In Stock',
    'title': 'Acer Fold Max | 99 Keys (ZC.A01SI.39Y)',
    'url_slug': 'acer-fold-max-99-keys-zc-a01si-39y'},
    {   'amazon_link': 'https://amzn.in/d/091waa5V',
    'asin': 'B0FTZXX729',
    'base_price': 2299.0,
    'category': 'Keyboards',
    'image_url': 'https://m.media-amazon.com/images/I/71FSalzPqeL._SL1500_.jpg',
    'mrp': 3499.0,
    'part_no': 'ZC.A01SI.39Z',
    'product_group': 'other_products',
    'rating': 4.0,
    'review_count': 98,
    'sort_order': 34,
    'stock_status': 'Out of Stock',
    'title': 'Acer Mini Fold | 67 Keys Compact (ZC.A01SI.39Z)',
    'url_slug': 'acer-mini-fold-67-keys-compact-zc-a01si-39z'},
    {   'amazon_link': 'https://amzn.in/d/0hKaWdc5',
    'asin': 'B0H65TZF1R',
    'base_price': 1199.0,
    'category': 'Keyboards',
    'image_url': 'https://m.media-amazon.com/images/I/71-c+qkae4L._SL1500_.jpg',
    'mrp': 1999.0,
    'part_no': 'ZC.A01SI.4YV',
    'product_group': 'other_products',
    'rating': 2.8,
    'review_count': 73,
    'sort_order': 35,
    'stock_status': 'In Stock',
    'title': 'Acer NanoPad Touch (Green) (ZC.A01SI.4YV)',
    'url_slug': 'acer-nanopad-touch-green-zc-a01si-4yv'},
    {   'amazon_link': 'https://amzn.in/d/0h1ZTet3',
    'asin': 'B0H65MQ33D',
    'base_price': 899.0,
    'category': 'Keyboards',
    'image_url': 'https://m.media-amazon.com/images/I/71Ku1ZHaOXL._SL1500_.jpg',
    'mrp': 1999.0,
    'part_no': 'ZC.A01SI.4YU',
    'product_group': 'other_products',
    'rating': 2.8,
    'review_count': 73,
    'sort_order': 36,
    'stock_status': 'In Stock',
    'title': 'Acer NanoPad Touch (Peach) (ZC.A01SI.4YU)',
    'url_slug': 'acer-nanopad-touch-peach-zc-a01si-4yu'},
    {   'amazon_link': 'https://amzn.in/d/05wObS7l',
    'asin': 'B0D8354479',
    'base_price': 1099.0,
    'category': 'Keyboard & Mouse Combos',
    'image_url': 'https://m.media-amazon.com/images/I/7157dBNL9LL._SL1500_.jpg',
    'mrp': 1999.0,
    'part_no': 'ZC.A01SI.0WD',
    'product_group': 'other_products',
    'rating': 3.8,
    'review_count': 1468,
    'sort_order': 37,
    'stock_status': 'Only 2 left in stock.',
    'title': 'Acer Wireless KBD Mouse White Gray Combo (ZC.A01SI.0WD)',
    'url_slug': 'acer-wireless-kbd-mouse-white-gray-combo-zc-a01si-'},
    {   'amazon_link': 'https://amzn.in/d/00oXwCPx',
    'asin': 'B0F9LN35XH',
    'base_price': 1299.0,
    'category': 'Keyboard & Mouse Combos',
    'image_url': 'https://m.media-amazon.com/images/I/718s8LifBeL._SL1500_.jpg',
    'mrp': 1999.0,
    'part_no': 'ZC.A01SI.204',
    'product_group': 'other_products',
    'rating': 3.9,
    'review_count': 201,
    'sort_order': 38,
    'stock_status': 'In Stock',
    'title': 'Acer Fusion Wireless KBD Mouse Black Silver COMBO (ZC.A01SI.204)',
    'url_slug': 'acer-fusion-wireless-kbd-mouse-black-silver-combo-'},
    {   'amazon_link': 'https://amzn.in/d/0cvhC7Ds',
    'asin': 'B0FCS5V5V1',
    'base_price': 698.0,
    'category': 'Keyboard & Mouse Combos',
    'image_url': 'https://m.media-amazon.com/images/I/71rgztpcpkL._SL1500_.jpg',
    'mrp': 1299.0,
    'part_no': 'ZC.A01SI.2DQ',
    'product_group': 'other_products',
    'rating': 4.2,
    'review_count': 114,
    'sort_order': 39,
    'stock_status': 'In Stock',
    'title': 'Acer PalmEase Wired Keyboard & Mouse Combo with Palm Rest (ZC.A01SI.2DQ)',
    'url_slug': 'acer-palmease-wired-keyboard-mouse-combo-with-palm'},
    {   'amazon_link': 'https://amzn.in/d/0fvxtU2O',
    'asin': 'B0GTG3VHZW',
    'base_price': 1099.0,
    'category': 'Keyboard & Mouse Combos',
    'image_url': 'https://m.media-amazon.com/images/I/71JogHAjw3L._SL1500_.jpg',
    'mrp': 1999.0,
    'part_no': 'ZC.A01SI.4JA',
    'product_group': 'other_products',
    'rating': 3.3,
    'review_count': 84,
    'sort_order': 40,
    'stock_status': 'Out of Stock',
    'title': 'Acer OfficeMate Wired Keyboard Mouse Combo-Black (ZC.A01SI.4JA)',
    'url_slug': 'acer-officemate-wired-keyboard-mouse-combo-black-z'},
    {   'amazon_link': 'https://amzn.in/d/0d0nItAm',
    'asin': 'B0GTG3X6FF',
    'base_price': 599.0,
    'category': 'Keyboard & Mouse Combos',
    'image_url': 'https://m.media-amazon.com/images/I/710zUWN-ZCL._SL1500_.jpg',
    'mrp': 1299.0,
    'part_no': 'ZC.A01SI.4JB',
    'product_group': 'other_products',
    'rating': 3.3,
    'review_count': 84,
    'sort_order': 41,
    'stock_status': 'In Stock',
    'title': 'Acer OfficeMate Wired Keyboard Mouse Combo-White (ZC.A01SI.4JB)',
    'url_slug': 'acer-officemate-wired-keyboard-mouse-combo-white-z'},
    {   'amazon_link': 'https://amzn.in/d/0bPFvu98',
    'asin': 'B0FCSFT4VX',
    'base_price': 949.0,
    'category': 'Keyboard & Mouse Combos',
    'image_url': 'https://m.media-amazon.com/images/I/71gxJKoZptL._SL1500_.jpg',
    'mrp': 1999.0,
    'part_no': 'ZC.A01SI.2DP',
    'product_group': 'other_products',
    'rating': 3.8,
    'review_count': 73,
    'sort_order': 42,
    'stock_status': 'In Stock',
    'title': 'Acer PalmEase Wireless Keyboard & Mouse Combo with Palm Rest-Black (ZC.A01SI.2DP)',
    'url_slug': 'acer-palmease-wireless-keyboard-mouse-combo-with-p'},
    {   'amazon_link': 'https://amzn.in/d/028vmivd',
    'asin': 'B0GJTT63ML',
    'base_price': 1149.0,
    'category': 'Keyboard & Mouse Combos',
    'image_url': 'https://m.media-amazon.com/images/I/61i2-mNIrML._SL1500_.jpg',
    'mrp': 1999.0,
    'part_no': 'ZC.A01SI.313',
    'product_group': 'other_products',
    'rating': 3.8,
    'review_count': 73,
    'sort_order': 43,
    'stock_status': 'In Stock',
    'title': 'Acer PalmEase Wireless Keyboard & Mouse Combo with Palm Rest-White (ZC.A01SI.313)',
    'url_slug': 'acer-palmease-wireless-keyboard-mouse-combo-with-p'},
    {   'amazon_link': 'https://amzn.in/d/0e0IBHGC',
    'asin': 'B0FFN8C3KW',
    'base_price': 1099.0,
    'category': 'Keyboard & Mouse Combos',
    'image_url': 'https://m.media-amazon.com/images/I/612DWHDVsHL._SL1500_.jpg',
    'mrp': 1999.0,
    'part_no': 'ZC.A01SI.223',
    'product_group': 'other_products',
    'rating': 3.4,
    'review_count': 944,
    'sort_order': 44,
    'stock_status': 'Out of Stock',
    'title': 'Acer Nano Pad COMBO - Black (ZC.A01SI.223)',
    'url_slug': 'acer-nano-pad-combo-black-zc-a01si-223'},
    {   'amazon_link': 'https://amzn.in/d/0iKvJyBx',
    'asin': 'B0FTTH71SY',
    'base_price': 999.0,
    'category': 'Keyboard & Mouse Combos',
    'image_url': 'https://m.media-amazon.com/images/I/71e3gwEBcAL._SL1500_.jpg',
    'mrp': 2000.0,
    'part_no': 'ZC.A01SI.3BH',
    'product_group': 'other_products',
    'rating': 3.4,
    'review_count': 944,
    'sort_order': 45,
    'stock_status': 'In Stock',
    'title': 'Acer Nano Pad COMBO - Purple (ZC.A01SI.3BH)',
    'url_slug': 'acer-nano-pad-combo-purple-zc-a01si-3bh'},
    {   'amazon_link': 'https://amzn.in/d/0fVcwg3C',
    'asin': 'B0G4DCBM4D',
    'base_price': 1398.0,
    'category': 'Keyboard & Mouse Combos',
    'image_url': 'https://m.media-amazon.com/images/I/713AuC+vzUL._SL1500_.jpg',
    'mrp': 2000.0,
    'part_no': 'ZC.A01SI.3R2',
    'product_group': 'other_products',
    'rating': 3.0,
    'review_count': 249,
    'sort_order': 46,
    'stock_status': 'In Stock',
    'title': 'Acer ZenKeys Duos - Black/Lime (ZC.A01SI.3R2)',
    'url_slug': 'acer-zenkeys-duos-black-lime-zc-a01si-3r2'},
    {   'amazon_link': 'https://amzn.in/d/00Sw1xzi',
    'asin': 'B0G4DJQMXK',
    'base_price': 1099.0,
    'category': 'Keyboard & Mouse Combos',
    'image_url': 'https://m.media-amazon.com/images/I/71+T2spJm2L._SL1500_.jpg',
    'mrp': 1999.0,
    'part_no': 'ZC.A01SI.3R3',
    'product_group': 'other_products',
    'rating': 3.0,
    'review_count': 249,
    'sort_order': 47,
    'stock_status': 'Out of Stock',
    'title': 'Acer ZenKeys Duos - White/Blue (ZC.A01SI.3R3)',
    'url_slug': 'acer-zenkeys-duos-white-blue-zc-a01si-3r3'},
    {   'amazon_link': 'https://amzn.in/d/0e1xb7cm',
    'asin': 'B0H8M56QXM',
    'base_price': 899.0,
    'category': 'Keyboard & Mouse Combos',
    'image_url': 'https://m.media-amazon.com/images/I/71mn9to+zJL._SL1500_.jpg',
    'mrp': 1999.0,
    'part_no': 'ZC.A01SI.4VM',
    'product_group': 'other_products',
    'rating': 4.0,
    'review_count': 8,
    'sort_order': 48,
    'stock_status': 'In Stock',
    'title': 'Acer OfficeLite KM 300 WL COMBO Black -DY (ZC.A01SI.4VM)',
    'url_slug': 'acer-officelite-km-300-wl-combo-black-dy-zc-a01si-'},
    {   'amazon_link': 'https://amzn.in/d/00A3nlLp',
    'asin': 'B0H8M8SF2R',
    'base_price': 1048.0,
    'category': 'Keyboard & Mouse Combos',
    'image_url': 'https://m.media-amazon.com/images/I/71+1Ok3Rs+L._SL1500_.jpg',
    'mrp': 1999.0,
    'part_no': 'ZC.A01SI.4VN',
    'product_group': 'other_products',
    'rating': 4.0,
    'review_count': 8,
    'sort_order': 49,
    'stock_status': 'In Stock',
    'title': 'Acer OfficeLite KM 300 WL COMBO White & Grey -DY (ZC.A01SI.4VN)',
    'url_slug': 'acer-officelite-km-300-wl-combo-white-grey-dy-zc-a'},
    {   'amazon_link': 'https://amzn.in/d/06sEKkEz',
    'asin': 'B0GK2L7DW7',
    'base_price': 1459.0,
    'category': 'Keyboard & Mouse Combos',
    'image_url': 'https://m.media-amazon.com/images/I/71fE3RKnXdL._SL1500_.jpg',
    'mrp': 2499.0,
    'part_no': 'ZC.A01SI.3U0',
    'product_group': 'other_products',
    'rating': 3.3,
    'review_count': 55,
    'sort_order': 50,
    'stock_status': 'In Stock',
    'title': 'Acer RedShift Wireless Keyboard & Mouse Combo (ZC.A01SI.3U0)',
    'url_slug': 'acer-redshift-wireless-keyboard-mouse-combo-zc-a01'},
    {   'amazon_link': 'https://amzn.in/d/03s6F5mt',
    'asin': 'B0DVGSLGB7',
    'base_price': 1599.0,
    'category': 'Keyboard & Mouse Combos',
    'image_url': 'https://m.media-amazon.com/images/I/715Qzq1XMlL._SL1500_.jpg',
    'mrp': 3500.0,
    'part_no': 'ZC.A01SI.18N',
    'product_group': 'other_products',
    'rating': 3.4,
    'review_count': 132,
    'sort_order': 51,
    'stock_status': 'In Stock',
    'title': 'Acer Cuteo Keyboard Mouse COMBO - Pink (ZC.A01SI.18N)',
    'url_slug': 'acer-cuteo-keyboard-mouse-combo-pink-zc-a01si-18n'},
    {   'amazon_link': 'https://amzn.in/d/0ecovzK7',
    'asin': 'B0H66952HK',
    'base_price': 1499.0,
    'category': 'Keyboard & Mouse Combos',
    'image_url': 'https://m.media-amazon.com/images/I/71srROxXWpL._SL1500_.jpg',
    'mrp': 3999.0,
    'part_no': 'ZC.A01SI.4YN',
    'product_group': 'other_products',
    'rating': 3.8,
    'review_count': 9,
    'sort_order': 52,
    'stock_status': 'In Stock',
    'title': 'Acer PopGo Wireless COMBO - Beige (ZC.A01SI.4YN)',
    'url_slug': 'acer-popgo-wireless-combo-beige-zc-a01si-4yn'},
    {   'amazon_link': 'https://amzn.in/d/014JfY3b',
    'asin': 'B0H6628VLR',
    'base_price': 1499.0,
    'category': 'Keyboard & Mouse Combos',
    'image_url': 'https://m.media-amazon.com/images/I/710fsFXgaPL._SL1500_.jpg',
    'mrp': 3999.0,
    'part_no': 'ZC.A01SI.4YP',
    'product_group': 'other_products',
    'rating': 3.8,
    'review_count': 9,
    'sort_order': 53,
    'stock_status': 'In Stock',
    'title': 'Acer PopGo Wireless COMBO - Purple (ZC.A01SI.4YP)',
    'url_slug': 'acer-popgo-wireless-combo-purple-zc-a01si-4yp'},
    {   'amazon_link': 'https://amzn.in/d/0dd5h6uG',
    'asin': 'B0DT9TMYHW',
    'base_price': 1999.0,
    'category': 'Keyboard & Mouse Combos',
    'image_url': 'https://m.media-amazon.com/images/I/81JilIXX68L._SL1500_.jpg',
    'mrp': 4999.0,
    'part_no': 'ZC.A01SI.1LG',
    'product_group': 'other_products',
    'rating': 3.8,
    'review_count': 179,
    'sort_order': 54,
    'stock_status': 'In Stock',
    'title': 'Acer ALG 4 in 1 COMBO (ZC.A01SI.1LG)',
    'url_slug': 'acer-alg-4-in-1-combo-zc-a01si-1lg'},
    {   'amazon_link': 'https://amzn.in/d/02h2iZTD',
    'asin': 'B0D8YCXLRD',
    'base_price': 2799.0,
    'category': 'Gaming Keyboards',
    'image_url': 'https://m.media-amazon.com/images/I/71gllABTI4L._SL1500_.jpg',
    'mrp': 4499.0,
    'part_no': 'GP.KBD11.048',
    'product_group': 'other_products',
    'rating': 4.6,
    'review_count': 6,
    'sort_order': 55,
    'stock_status': 'Out of Stock',
    'title': 'Predator Aethon 303 (GP.KBD11.048)',
    'url_slug': 'predator-aethon-303-gp-kbd11-048'},
    {   'amazon_link': 'https://amzn.in/d/053R055F',
    'asin': 'B0DNFL4C1R',
    'base_price': 3999.0,
    'category': 'Gaming Keyboards',
    'image_url': 'https://m.media-amazon.com/images/I/61J0UQRjvML._SL1500_.jpg',
    'mrp': 5999.0,
    'part_no': 'GP.KBD11.04A',
    'product_group': 'other_products',
    'rating': 4.1,
    'review_count': 8,
    'sort_order': 56,
    'stock_status': 'In Stock',
    'title': 'Predator Aethon 330 (GP.KBD11.04A)',
    'url_slug': 'predator-aethon-330-gp-kbd11-04a'},
    {   'amazon_link': 'https://amzn.in/d/0awRxZWI',
    'asin': 'B0G61CFR13',
    'base_price': 2398.0,
    'category': 'Gaming Keyboards',
    'image_url': 'https://m.media-amazon.com/images/I/81T3b9Fw76L._SL1500_.jpg',
    'mrp': 3999.0,
    'part_no': 'ZC.A01SI.3RW',
    'product_group': 'other_products',
    'rating': 3.9,
    'review_count': 113,
    'sort_order': 57,
    'stock_status': 'In Stock',
    'title': 'acer Nitro G Wired Mechanical Gaming Keyboard (ZC.A01SI.3RW)',
    'url_slug': 'acer-nitro-g-wired-mechanical-gaming-keyboard-zc-a'},
    {   'amazon_link': 'https://amzn.in/d/032kanBK',
    'asin': 'B07H5R7K2M',
    'base_price': 1699.0,
    'category': 'Audio & Headsets',
    'image_url': 'https://m.media-amazon.com/images/I/71wGpUdWCrL._SL1500_.jpg',
    'mrp': 2999.0,
    'part_no': 'NP.HDS1A.008',
    'product_group': 'other_products',
    'rating': 4.0,
    'review_count': 160,
    'sort_order': 58,
    'stock_status': 'Out of Stock',
    'title': 'Nitro Wired Gaming Headset (NP.HDS1A.008)',
    'url_slug': 'nitro-wired-gaming-headset-np-hds1a-008'},
    {   'amazon_link': 'https://amzn.in/d/0anrVGEF',
    'asin': 'B0FTVYCWZ8',
    'base_price': 1476.0,
    'category': 'Audio & Headsets',
    'image_url': 'https://m.media-amazon.com/images/I/71H9SFO10wL._SL1500_.jpg',
    'mrp': 2500.0,
    'part_no': 'ZC.A01SI.395',
    'product_group': 'other_products',
    'rating': 4.0,
    'review_count': 31,
    'sort_order': 59,
    'stock_status': 'In Stock',
    'title': 'Nitro Wired Gaming Headset (ZC.A01SI.395)',
    'url_slug': 'nitro-wired-gaming-headset-zc-a01si-395'},
    {   'amazon_link': 'https://amzn.in/d/01GLG4A7',
    'asin': 'B0FR4KJ6NT',
    'base_price': 3453.0,
    'category': 'Audio & Headsets',
    'image_url': 'https://m.media-amazon.com/images/I/71+WYMQs2ZL._SL1500_.jpg',
    'mrp': 4000.0,
    'part_no': 'ZC.A01SI.396',
    'product_group': 'other_products',
    'rating': 3.6,
    'review_count': 42,
    'sort_order': 60,
    'stock_status': 'In Stock',
    'title': 'Nitro Wireless 4 in 1 Headset, 7.1 Surround (ZC.A01SI.396)',
    'url_slug': 'nitro-wireless-4-in-1-headset-7-1-surround-zc-a01s'},
    {   'amazon_link': 'https://amzn.in/d/05gaWPCq',
    'asin': 'B0H6629LXR',
    'base_price': 1599.0,
    'category': 'Audio & Headsets',
    'image_url': 'https://m.media-amazon.com/images/I/71oIZunL6WL._SL1500_.jpg',
    'mrp': 3999.0,
    'part_no': 'ZC.A01SI.4YR',
    'product_group': 'other_products',
    'rating': 4.2,
    'review_count': 190,
    'sort_order': 61,
    'stock_status': 'In Stock',
    'title': 'Nitro Phatom Headset (ZC.A01SI.4YR)',
    'url_slug': 'nitro-phatom-headset-zc-a01si-4yr'},
    {   'amazon_link': 'https://amzn.in/d/0gaJ0c9Q',
    'asin': 'B0GKHYTGB3',
    'base_price': 1888.0,
    'category': 'Audio & Headsets',
    'image_url': 'https://m.media-amazon.com/images/I/714pN+PB1jL._SL1500_.jpg',
    'mrp': 4000.0,
    'part_no': 'ZC.A01SI.3LG',
    'product_group': 'other_products',
    'rating': 3.9,
    'review_count': 22,
    'sort_order': 62,
    'stock_status': 'In Stock',
    'title': 'Dreamwave Speaker (ZC.A01SI.3LG)',
    'url_slug': 'dreamwave-speaker-zc-a01si-3lg'},
    {   'amazon_link': 'https://amzn.in/d/03Gp2VKd',
    'asin': 'B0DCW32MB9',
    'base_price': 2999.0,
    'category': 'Monitor Stands & Mounts',
    'image_url': 'https://m.media-amazon.com/images/I/610REoj1IpL._SL1500_.jpg',
    'mrp': 4999.0,
    'part_no': 'ZC.A01SI.179',
    'product_group': 'acer_monitors',
    'rating': 4.1,
    'review_count': 298,
    'sort_order': 63,
    'stock_status': 'Out of Stock',
    'title': 'Acer Ergo Monitor Stand with RGB Lights and 4 Port USB HUB (Black) (ZC.A01SI.179)',
    'url_slug': 'acer-ergo-monitor-stand-with-rgb-lights-and-4-port'},
    {   'amazon_link': 'https://amzn.in/d/08wi0EN8',
    'asin': 'B0DCW28VCS',
    'base_price': 1799.0,
    'category': 'Monitor Stands & Mounts',
    'image_url': 'https://m.media-amazon.com/images/I/61DFXCjquhL._SL1500_.jpg',
    'mrp': 8999.0,
    'part_no': 'ZC.A01SI.17A',
    'product_group': 'acer_monitors',
    'rating': 4.3,
    'review_count': 192,
    'sort_order': 64,
    'stock_status': 'In Stock',
    'title': 'acer Ergo Multifunction Monitor & Laptop Stand Featuring RGB Lighting and a 4-Port USB Hub with Aluminum '
             'Multi Keyboard Storage Space Bar, Suitable for Both Office and Home Environments (White)',
    'url_slug': 'acer-ergo-monitor-stand-with-rgb-lights-and-4-port'},
    {   'amazon_link': 'https://amzn.in/d/0egJWQkY',
    'asin': 'B0FQDD56FW',
    'base_price': 2999.0,
    'category': 'Monitor Stands & Mounts',
    'image_url': 'https://m.media-amazon.com/images/I/71GFjNV4lIL._SL1500_.jpg',
    'mrp': 4999.0,
    'part_no': 'ZC.A01SI.2ZT',
    'product_group': 'acer_monitors',
    'rating': 4.0,
    'review_count': 53,
    'sort_order': 65,
    'stock_status': 'Out of Stock',
    'title': 'Acer FusionBase Ergo Monitor Stand with wireless Charging (ZC.A01SI.2ZT)',
    'url_slug': 'acer-fusionbase-ergo-monitor-stand-with-wireless-c'},
    {   'amazon_link': 'https://amzn.in/d/0fFAi1pK',
    'asin': 'B0GZWS5CL1',
    'base_price': 1999.0,
    'category': 'Monitor Stands & Mounts',
    'image_url': 'https://m.media-amazon.com/images/I/81VlU5-LA2L._SL1500_.jpg',
    'mrp': 3999.0,
    'part_no': 'ZC.A01SI.4VX',
    'product_group': 'acer_monitors',
    'rating': 3.4,
    'review_count': 14,
    'sort_order': 66,
    'stock_status': 'In Stock',
    'title': 'DeskPro Stand (ZC.A01SI.4VX)',
    'url_slug': 'deskpro-stand-zc-a01si-4vx'},
    {   'amazon_link': 'https://amzn.in/d/04v36OgI',
    'asin': 'B0FZX217Q9',
    'base_price': 2423.0,
    'category': 'Backpacks & Sleeves',
    'image_url': 'https://m.media-amazon.com/images/I/71+F53KqcsL._SL1500_.jpg',
    'mrp': 3999.0,
    'part_no': 'ZC.A01SI.3BU',
    'product_group': 'other_products',
    'rating': 4.9,
    'review_count': 38,
    'sort_order': 67,
    'stock_status': 'In Stock',
    'title': 'New Predator Backpack (ZC.A01SI.3BU)',
    'url_slug': 'new-predator-backpack-zc-a01si-3bu'},
    {   'amazon_link': 'https://amzn.in/d/05L9cSW5',
    'asin': 'B002EWQY5W',
    'base_price': 1995.0,
    'category': 'Backpacks & Sleeves',
    'image_url': 'https://m.media-amazon.com/images/I/71lneMiBDqL._SL1500_.jpg',
    'mrp': 4999.0,
    'part_no': 'ZC.A01SI.1B7',
    'product_group': 'other_products',
    'rating': 4.3,
    'review_count': 255,
    'sort_order': 68,
    'stock_status': 'In Stock',
    'title': 'Acer Estilo Beige (ZC.A01SI.1B7)',
    'url_slug': 'acer-estilo-beige-zc-a01si-1b7'},
    {   'amazon_link': 'https://amzn.in/d/0bcvRtma',
    'asin': 'B0FSSTD2VS',
    'base_price': 1718.0,
    'category': 'Backpacks & Sleeves',
    'image_url': 'https://m.media-amazon.com/images/I/71tsL1BakEL._SL1500_.jpg',
    'mrp': 4999.0,
    'part_no': 'ZC.A01SI.3FJ',
    'product_group': 'other_products',
    'rating': 4.2,
    'review_count': 25,
    'sort_order': 69,
    'stock_status': 'In Stock',
    'title': 'Acer Estilo Black (ZC.A01SI.3FJ)',
    'url_slug': 'acer-estilo-black-zc-a01si-3fj'},
    {   'amazon_link': 'https://amzn.in/d/02hunQ83',
    'asin': 'B0DLB6QBH8',
    'base_price': 1391.0,
    'category': 'Backpacks & Sleeves',
    'image_url': 'https://m.media-amazon.com/images/I/71TVEpNun0L._SL1500_.jpg',
    'mrp': 3999.0,
    'part_no': 'ZC.A01SI.1B5',
    'product_group': 'other_products',
    'rating': 4.3,
    'review_count': 178,
    'sort_order': 70,
    'stock_status': 'In Stock',
    'title': 'Acer Sling Bag Green (ZC.A01SI.1B5)',
    'url_slug': 'acer-sling-bag-green-zc-a01si-1b5'},
    {   'amazon_link': 'https://amzn.in/d/07NNp9EU',
    'asin': 'B008N4JKEC',
    'base_price': 944.0,
    'category': 'Backpacks & Sleeves',
    'image_url': 'https://m.media-amazon.com/images/I/61PFwGE3BEL._SL1500_.jpg',
    'mrp': 3999.0,
    'part_no': 'ZC.A01SI.1B6',
    'product_group': 'other_products',
    'rating': 4.3,
    'review_count': 47,
    'sort_order': 71,
    'stock_status': 'In Stock',
    'title': 'Acer Sling Bag Grey (ZC.A01SI.1B6)',
    'url_slug': 'acer-sling-bag-grey-zc-a01si-1b6'},
    {   'amazon_link': 'https://amzn.in/d/0736fmpt',
    'asin': 'B0FWYRSPNB',
    'base_price': 1299.0,
    'category': 'Backpacks & Sleeves',
    'image_url': 'https://m.media-amazon.com/images/I/71MOWm9++oL._SL1500_.jpg',
    'mrp': 3999.0,
    'part_no': 'ZC.A01SI.3LA',
    'product_group': 'other_products',
    'rating': 4.3,
    'review_count': 178,
    'sort_order': 72,
    'stock_status': 'In Stock',
    'title': 'Acer Sling Bag Black (ZC.A01SI.3LA)',
    'url_slug': 'acer-sling-bag-black-zc-a01si-3la'},
    {   'amazon_link': 'https://amzn.in/d/0ih18G5u',
    'asin': 'B0GKC55B4H',
    'base_price': 1899.0,
    'category': 'Backpacks & Sleeves',
    'image_url': 'https://m.media-amazon.com/images/I/71kzj5TWOXL._SL1500_.jpg',
    'mrp': 3000.0,
    'part_no': 'ZC.A01SI.3LJ',
    'product_group': 'other_products',
    'rating': 3.6,
    'review_count': 37,
    'sort_order': 73,
    'stock_status': 'In Stock',
    'title': 'Acer ChargeMate 4-in-1 Wireless Charging Laptop Sleeve - Grey (ZC.A01SI.3LJ)',
    'url_slug': 'acer-chargemate-4-in-1-wireless-charging-laptop-sl'},
    {   'amazon_link': 'https://amzn.in/d/0ii9l0h2',
    'asin': 'B0GKBXTL5S',
    'base_price': 1899.0,
    'category': 'Backpacks & Sleeves',
    'image_url': 'https://m.media-amazon.com/images/I/71tDHc4po7L._SL1500_.jpg',
    'mrp': 3000.0,
    'part_no': 'ZC.A01SI.3LK',
    'product_group': 'other_products',
    'rating': 3.6,
    'review_count': 37,
    'sort_order': 74,
    'stock_status': 'In Stock',
    'title': 'Acer ChargeMate 4-in-1 Wireless Charging Laptop Sleeve - Black (ZC.A01SI.3LK)',
    'url_slug': 'acer-chargemate-4-in-1-wireless-charging-laptop-sl'},
    {   'amazon_link': 'https://amzn.in/d/0acVoJ1E',
    'asin': 'B0FX5HWSWD',
    'base_price': 932.0,
    'category': 'Backpacks & Sleeves',
    'image_url': 'https://m.media-amazon.com/images/I/71JS7IA6aOL._SL1500_.jpg',
    'mrp': 1599.0,
    'part_no': 'ZC.A01SI.3HB',
    'product_group': 'other_products',
    'rating': 4.4,
    'review_count': 37,
    'sort_order': 75,
    'stock_status': 'In Stock',
    'title': 'Acer Cross Body Bag (ZC.A01SI.3HB)',
    'url_slug': 'acer-cross-body-bag-zc-a01si-3hb'},
    {   'amazon_link': 'https://amzn.in/d/029BJiPl',
    'asin': 'B0FXV4PWJ9',
    'base_price': 1444.0,
    'category': 'Backpacks & Sleeves',
    'image_url': 'https://m.media-amazon.com/images/I/815Zn+MH1nL._SL1500_.jpg',
    'mrp': 2999.0,
    'part_no': 'ZC.A01SI.3BV',
    'product_group': 'other_products',
    'rating': 4.4,
    'review_count': 50,
    'sort_order': 76,
    'stock_status': 'In Stock',
    'title': 'Acer UrbanLite Slim (ZC.A01SI.3BV)',
    'url_slug': 'acer-urbanlite-slim-zc-a01si-3bv'},
    {   'amazon_link': 'https://amzn.in/d/09VAgml9',
    'asin': 'B0F6V5YMKJ',
    'base_price': 508.0,
    'category': 'Backpacks & Sleeves',
    'image_url': 'https://m.media-amazon.com/images/I/81RL4Ewy9ML._SL1500_.jpg',
    'mrp': 999.0,
    'part_no': 'ZC.A01SI.21X',
    'product_group': 'other_products',
    'rating': 3.8,
    'review_count': 167,
    'sort_order': 77,
    'stock_status': 'In Stock',
    'title': 'Acer Pulse Backpack Yellow/Navy blue (ZC.A01SI.21X)',
    'url_slug': 'acer-pulse-backpack-yellow-navy-blue-zc-a01si-21x'},
    {   'amazon_link': 'https://amzn.in/d/07a22lJr',
    'asin': 'B0F6VGF7K1',
    'base_price': 799.0,
    'category': 'Backpacks & Sleeves',
    'image_url': 'https://m.media-amazon.com/images/I/81aEpO3s50L._SL1500_.jpg',
    'mrp': 999.0,
    'part_no': 'ZC.A01SI.21Y',
    'product_group': 'other_products',
    'rating': 3.8,
    'review_count': 167,
    'sort_order': 78,
    'stock_status': 'In Stock',
    'title': 'Acer Pulse Backpack Silver/Navy blue (ZC.A01SI.21Y)',
    'url_slug': 'acer-pulse-backpack-silver-navy-blue-zc-a01si-21y'},
    {   'amazon_link': 'https://amzn.in/d/0anqBsVY',
    'asin': 'B0G1CX438C',
    'base_price': 1299.0,
    'category': 'Backpacks & Sleeves',
    'image_url': 'https://m.media-amazon.com/images/I/81554-3L0uL._SL1500_.jpg',
    'mrp': 2499.0,
    'part_no': 'ZC.A01SI.3VP',
    'product_group': 'other_products',
    'rating': 3.8,
    'review_count': 167,
    'sort_order': 79,
    'stock_status': 'In Stock',
    'title': 'Acer Pulse Backpack Black / Maroon (ZC.A01SI.3VP)',
    'url_slug': 'acer-pulse-backpack-black-maroon-zc-a01si-3vp'},
    {   'amazon_link': 'https://amzn.in/d/0hVfDqZG',
    'asin': 'B0F3TJZ9JG',
    'base_price': 1299.0,
    'category': 'Backpacks & Sleeves',
    'image_url': 'https://m.media-amazon.com/images/I/61uq1vvbtLL._SL1500_.jpg',
    'mrp': 2499.0,
    'part_no': 'ZC.A01SI.1KE',
    'product_group': 'other_products',
    'rating': 4.4,
    'review_count': 36,
    'sort_order': 80,
    'stock_status': 'Out of Stock',
    'title': 'Acer Swift 2 in one Convertible Backpack ( Navy Blue) (ZC.A01SI.1KE)',
    'url_slug': 'acer-swift-2-in-one-convertible-backpack-navy-blue'},
    {   'amazon_link': 'https://amzn.in/d/0dHU9YZv',
    'asin': 'B0F3TQ9655',
    'base_price': 2354.0,
    'category': 'Backpacks & Sleeves',
    'image_url': 'https://m.media-amazon.com/images/I/61fk7P3g9HL._SL1500_.jpg',
    'mrp': 4999.0,
    'part_no': 'ZC.A01SI.1KF',
    'product_group': 'other_products',
    'rating': 4.4,
    'review_count': 36,
    'sort_order': 81,
    'stock_status': 'In Stock',
    'title': 'Acer Swift 2 in one Convertible Backpack (TAN) (ZC.A01SI.1KF)',
    'url_slug': 'acer-swift-2-in-one-convertible-backpack-tan-zc-a0'},
    {   'amazon_link': 'https://amzn.in/d/0iNKWFIP',
    'asin': 'B0FGQ2QD59',
    'base_price': 3068.0,
    'category': 'Backpacks & Sleeves',
    'image_url': 'https://m.media-amazon.com/images/I/81qjCRAw8YL._SL1500_.jpg',
    'mrp': 8999.0,
    'part_no': 'ZC.A01SI.1QP',
    'product_group': 'other_products',
    'rating': 4.6,
    'review_count': 51,
    'sort_order': 82,
    'stock_status': 'In Stock',
    'title': 'Acer Premium Business Laptop Backpack (ZC.A01SI.1QP)',
    'url_slug': 'acer-premium-business-laptop-backpack-zc-a01si-1qp'},
    {   'amazon_link': 'https://amzn.in/d/0bibRtB8',
    'asin': 'B0FGPTK1N8',
    'base_price': 2036.0,
    'category': 'Backpacks & Sleeves',
    'image_url': 'https://m.media-amazon.com/images/I/81c7V8ALeGL._SL1500_.jpg',
    'mrp': 8999.0,
    'part_no': 'ZC.A01SI.1QQ',
    'product_group': 'other_products',
    'rating': 3.5,
    'review_count': 8,
    'sort_order': 83,
    'stock_status': 'In Stock',
    'title': 'Acer Premium Professional Laptop Backpack (ZC.A01SI.1QQ)',
    'url_slug': 'acer-premium-professional-laptop-backpack-zc-a01si'},
    {   'amazon_link': 'https://amzn.in/d/0j5fMhx6',
    'asin': 'B0GRSB3DNX',
    'base_price': 5998.0,
    'category': 'Backpacks & Sleeves',
    'image_url': 'https://m.media-amazon.com/images/I/71LIdOGincL._SL1500_.jpg',
    'mrp': 9999.0,
    'part_no': 'ZC.A01SI.4MB',
    'product_group': 'other_products',
    'rating': 4.3,
    'review_count': 19,
    'sort_order': 84,
    'stock_status': 'In Stock',
    'title': 'Acer VacuPack Backpack (ZC.A01SI.4MB)',
    'url_slug': 'acer-vacupack-backpack-zc-a01si-4mb'},
    {   'amazon_link': 'https://amzn.in/d/0epw1kGk',
    'asin': 'B0FDKXG11W',
    'base_price': 2202.0,
    'category': 'Power & Cable Management',
    'image_url': 'https://m.media-amazon.com/images/I/61luv7mjsGL._SL1500_.jpg',
    'mrp': 3999.0,
    'part_no': 'ZC.A01SI.2P1',
    'product_group': 'other_products',
    'rating': 4.3,
    'review_count': 43,
    'sort_order': 85,
    'stock_status': 'In Stock',
    'title': 'Management Power Strip (ZC.A01SI.2P1)',
    'url_slug': 'management-power-strip-zc-a01si-2p1'},
    {   'amazon_link': 'https://amzn.in/d/00SX8Ctx',
    'asin': 'B0FDKWY2TS',
    'base_price': 2765.0,
    'category': 'Power & Cable Management',
    'image_url': 'https://m.media-amazon.com/images/I/61rMD55JqgL._SL1500_.jpg',
    'mrp': 3999.0,
    'part_no': 'ZC.A01SI.2P2',
    'product_group': 'other_products',
    'rating': 3.9,
    'review_count': 74,
    'sort_order': 86,
    'stock_status': 'In Stock',
    'title': 'Wifi Smart Power Strip (ZC.A01SI.2P2)',
    'url_slug': 'wifi-smart-power-strip-zc-a01si-2p2'},
    {   'amazon_link': 'https://amzn.in/d/0h32ZOIv',
    'asin': 'B0FDKXXQHH',
    'base_price': 1499.0,
    'category': 'Power & Cable Management',
    'image_url': 'https://m.media-amazon.com/images/I/614zwFtp-uL._SL1500_.jpg',
    'mrp': 2499.0,
    'part_no': 'ZC.A01SI.2P3',
    'product_group': 'other_products',
    'rating': 4.4,
    'review_count': 113,
    'sort_order': 87,
    'stock_status': 'Out of Stock',
    'title': 'Tower Extension (ZC.A01SI.2P3)',
    'url_slug': 'tower-extension-zc-a01si-2p3'},
    {   'amazon_link': 'https://amzn.in/d/04WN2Fzz',
    'asin': 'B0FDKYVCPP',
    'base_price': 2385.0,
    'category': 'Power & Cable Management',
    'image_url': 'https://m.media-amazon.com/images/I/61dspGUaE3L._SL1500_.jpg',
    'mrp': 3599.0,
    'part_no': 'ZC.A01SI.2P4',
    'product_group': 'other_products',
    'rating': 4.2,
    'review_count': 71,
    'sort_order': 88,
    'stock_status': 'In Stock',
    'title': 'Tubo GaN Strip (ZC.A01SI.2P4)',
    'url_slug': 'tubo-gan-strip-zc-a01si-2p4'},
    {   'amazon_link': 'https://amzn.in/d/0jcSu0LD',
    'asin': 'B0DMP3Q1TV',
    'base_price': 471.0,
    'category': 'Privacy Screens',
    'image_url': 'https://m.media-amazon.com/images/I/71qmsxQUeyL._SL1500_.jpg',
    'mrp': 4999.0,
    'part_no': 'ZC.A01SI.18A',
    'product_group': 'acer_monitors',
    'rating': 3.4,
    'review_count': 8,
    'sort_order': 89,
    'stock_status': 'In Stock',
    'title': 'Acer 14" Privacy Screen (ASF14W9AC-80) (ZC.A01SI.18A)',
    'url_slug': 'acer-14-privacy-screen-asf14w9ac-80-zc-a01si-18a'},
    {   'amazon_link': 'https://amzn.in/d/0bixuE7R',
    'asin': 'B0DMP1272V',
    'base_price': 654.0,
    'category': 'Privacy Screens',
    'image_url': 'https://m.media-amazon.com/images/I/716vp8GnGAL._SL1500_.jpg',
    'mrp': 5999.0,
    'part_no': 'ZC.A01SI.18B',
    'product_group': 'acer_monitors',
    'rating': 3.5,
    'review_count': 4,
    'sort_order': 90,
    'stock_status': 'In Stock',
    'title': 'Acer 15.6" Privacy Screen (ASF14W9AC-80) (ZC.A01SI.18B)',
    'url_slug': 'acer-15-6-privacy-screen-asf14w9ac-80-zc-a01si-18b'},
]

# Derived group lists
ACER_MONITOR_SEED_PRODUCTS = [p for p in ACER_SEED_PRODUCTS if p["product_group"] == "acer_monitors"]
ACER_OTHER_SEED_PRODUCTS = [p for p in ACER_SEED_PRODUCTS if p["product_group"] == "other_products"]
ALL_SEED_PRODUCTS = ACER_SEED_PRODUCTS
