"""
Curated & Verified Acer Accessories & Monitor Hardware Catalog from Amazon India:
1. Acer Monitors & Display Hardware (Monitor Stands, Mounts, Privacy Screens) (6 items)
2. Other Products (Mice, Keyboards, Combos, Audio/Headsets, Backpacks & Sleeves, Power & Cable Strips) (84 items)
Extracted directly from 'amazon acer accessories .xlsx' (Total 90 live ASINs).
"""
from app.config import GROUP_ACER_MONITORS, GROUP_OTHER_PRODUCTS

# --- Acer Monitors & Display Hardware Seed Products (6) ---
ACER_MONITOR_SEED_PRODUCTS = [
    {
        "asin": "B0DCW32MB9",
        "title": "Acer Ergo Monitor Stand with RGB Lights and 4 Port USB HUB (Black) (ZC.A01SI.179)",
        "category": "Monitor Stands & Mounts",
        "product_group": "acer_monitors",
        "part_no": "ZC.A01SI.179",
        "mrp": 4999.0,
        "base_price": 2999.0,
        "rating": 4.3,
        "review_count": 85,
        "image_url": "https://m.media-amazon.com/images/I/61Nl-F3kGLL._SX679_.jpg",
        "url_slug": "acer-ergo-monitor-stand-with-rgb-lights-and-4-port",
        "amazon_link": "https://amzn.in/d/03Gp2VKd"
    },
    {
        "asin": "B0DCW28VCS",
        "title": "Acer Ergo Monitor Stand with RGB Lights and 4 Port USB HUB (White) (ZC.A01SI.17A)",
        "category": "Monitor Stands & Mounts",
        "product_group": "acer_monitors",
        "part_no": "ZC.A01SI.17A",
        "mrp": 4999.0,
        "base_price": 2999.0,
        "rating": 4.3,
        "review_count": 85,
        "image_url": "https://m.media-amazon.com/images/I/61Nl-F3kGLL._SX679_.jpg",
        "url_slug": "acer-ergo-monitor-stand-with-rgb-lights-and-4-port",
        "amazon_link": "https://amzn.in/d/08wi0EN8"
    },
    {
        "asin": "B0FQDD56FW",
        "title": "Acer FusionBase Ergo Monitor Stand with wireless Charging (ZC.A01SI.2ZT)",
        "category": "Monitor Stands & Mounts",
        "product_group": "acer_monitors",
        "part_no": "ZC.A01SI.2ZT",
        "mrp": 4999.0,
        "base_price": 2999.0,
        "rating": 4.3,
        "review_count": 85,
        "image_url": "https://m.media-amazon.com/images/I/61Nl-F3kGLL._SX679_.jpg",
        "url_slug": "acer-fusionbase-ergo-monitor-stand-with-wireless-c",
        "amazon_link": "https://amzn.in/d/0egJWQkY"
    },
    {
        "asin": "B0GZWS5CL1",
        "title": "DeskPro Stand (ZC.A01SI.4VX)",
        "category": "Monitor Stands & Mounts",
        "product_group": "acer_monitors",
        "part_no": "ZC.A01SI.4VX",
        "mrp": 3499.0,
        "base_price": 1999.0,
        "rating": 4.3,
        "review_count": 85,
        "image_url": "https://m.media-amazon.com/images/I/61Nl-F3kGLL._SX679_.jpg",
        "url_slug": "deskpro-stand-zc-a01si-4vx",
        "amazon_link": "https://amzn.in/d/0fFAi1pK"
    },
    {
        "asin": "B0DMP3Q1TV",
        "title": "Acer 14\" Privacy Screen (ASF14W9AC-80) (ZC.A01SI.18A)",
        "category": "Privacy Screens",
        "product_group": "acer_monitors",
        "part_no": "ZC.A01SI.18A",
        "mrp": 2499.0,
        "base_price": 1299.0,
        "rating": 4.1,
        "review_count": 42,
        "image_url": "https://m.media-amazon.com/images/I/71YQkOhyXKL._SX679_.jpg",
        "url_slug": "acer-14-privacy-screen-asf14w9ac-80-zc-a01si-18a",
        "amazon_link": "https://amzn.in/d/0jcSu0LD"
    },
    {
        "asin": "B0DMP1272V",
        "title": "Acer 15.6\" Privacy Screen (ASF14W9AC-80) (ZC.A01SI.18B)",
        "category": "Privacy Screens",
        "product_group": "acer_monitors",
        "part_no": "ZC.A01SI.18B",
        "mrp": 2999.0,
        "base_price": 1499.0,
        "rating": 4.1,
        "review_count": 42,
        "image_url": "https://m.media-amazon.com/images/I/71YQkOhyXKL._SX679_.jpg",
        "url_slug": "acer-15-6-privacy-screen-asf14w9ac-80-zc-a01si-18b",
        "amazon_link": "https://amzn.in/d/0bixuE7R"
    }
]

# --- Other Products Seed Catalog (Mice, Keyboards, Combos, Audio, Bags, Power) (84) ---
OTHER_SEED_PRODUCTS = [
    {
        "asin": "B0DNNLW8MK",
        "title": "Acer ClearView Transparent Mouse - Green (ZC.A01SI.18F)",
        "category": "Wireless & Wired Mice",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.18F",
        "mrp": 1499.0,
        "base_price": 799.0,
        "rating": 4.2,
        "review_count": 340,
        "image_url": "https://m.media-amazon.com/images/I/51wJ5rK0kGL._SX679_.jpg",
        "url_slug": "acer-clearview-transparent-mouse-green-zc-a01si-18",
        "amazon_link": "https://amzn.in/d/0gFTTe4f"
    },
    {
        "asin": "B0DNNLWB1V",
        "title": "Acer ClearView Transparent Mouse - White (ZC.A01SI.18D)",
        "category": "Wireless & Wired Mice",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.18D",
        "mrp": 1499.0,
        "base_price": 799.0,
        "rating": 4.2,
        "review_count": 340,
        "image_url": "https://m.media-amazon.com/images/I/51wJ5rK0kGL._SX679_.jpg",
        "url_slug": "acer-clearview-transparent-mouse-white-zc-a01si-18",
        "amazon_link": "https://amzn.in/d/096DqpWo"
    },
    {
        "asin": "B0DNNLNTHY",
        "title": "Acer ClearView Transparent Mouse - Blue (ZC.A01SI.18E)",
        "category": "Wireless & Wired Mice",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.18E",
        "mrp": 1499.0,
        "base_price": 799.0,
        "rating": 4.2,
        "review_count": 340,
        "image_url": "https://m.media-amazon.com/images/I/51wJ5rK0kGL._SX679_.jpg",
        "url_slug": "acer-clearview-transparent-mouse-blue-zc-a01si-18e",
        "amazon_link": "https://amzn.in/d/02vcJ7aV"
    },
    {
        "asin": "B0H5XK7SRG",
        "title": "Acer ClearView Transparent Mouse - Black (ZC.A01SI.4WE)",
        "category": "Wireless & Wired Mice",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.4WE",
        "mrp": 1499.0,
        "base_price": 799.0,
        "rating": 4.2,
        "review_count": 340,
        "image_url": "https://m.media-amazon.com/images/I/51wJ5rK0kGL._SX679_.jpg",
        "url_slug": "acer-clearview-transparent-mouse-black-zc-a01si-4w",
        "amazon_link": "https://amzn.in/d/02klBboU"
    },
    {
        "asin": "B0FCFW7QB5",
        "title": "Wireless Transparent Rechargeable Mouse  Grey OS (ZC.A01SI.2DR)",
        "category": "Wireless & Wired Mice",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.2DR",
        "mrp": 1499.0,
        "base_price": 799.0,
        "rating": 4.2,
        "review_count": 340,
        "image_url": "https://m.media-amazon.com/images/I/51wJ5rK0kGL._SX679_.jpg",
        "url_slug": "wireless-transparent-rechargeable-mouse-grey-os-zc",
        "amazon_link": "https://amzn.in/d/01WsvzuO"
    },
    {
        "asin": "B0FCFW9LNG",
        "title": "Wireless Transparent Rechargeable Mouse  Peach OS (ZC.A01SI.2DT)",
        "category": "Wireless & Wired Mice",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.2DT",
        "mrp": 1499.0,
        "base_price": 799.0,
        "rating": 4.2,
        "review_count": 340,
        "image_url": "https://m.media-amazon.com/images/I/51wJ5rK0kGL._SX679_.jpg",
        "url_slug": "wireless-transparent-rechargeable-mouse-peach-os-z",
        "amazon_link": "https://amzn.in/d/04hQzsx1"
    },
    {
        "asin": "B0D378LN1J",
        "title": "Acer Wireless Mouse White Green (5W.50611.004)",
        "category": "Wireless & Wired Mice",
        "product_group": "other_products",
        "part_no": "5W.50611.004",
        "mrp": 999.0,
        "base_price": 499.0,
        "rating": 4.2,
        "review_count": 340,
        "image_url": "https://m.media-amazon.com/images/I/51wJ5rK0kGL._SX679_.jpg",
        "url_slug": "acer-wireless-mouse-white-green-5w-50611-004",
        "amazon_link": "https://amzn.in/d/0d8sfi77"
    },
    {
        "asin": "B0D7VSW3W9",
        "title": "Acer Wireless Mouse, White Orange (ZC.A01SI.0WB)",
        "category": "Wireless & Wired Mice",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.0WB",
        "mrp": 999.0,
        "base_price": 499.0,
        "rating": 4.2,
        "review_count": 340,
        "image_url": "https://m.media-amazon.com/images/I/51wJ5rK0kGL._SX679_.jpg",
        "url_slug": "acer-wireless-mouse-white-orange-zc-a01si-0wb",
        "amazon_link": "https://amzn.in/d/01HTqM53"
    },
    {
        "asin": "B0DJBK21X7",
        "title": "Acer Wireless Mouse, White Blue (ZC.A01SI.0WC)",
        "category": "Wireless & Wired Mice",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.0WC",
        "mrp": 999.0,
        "base_price": 499.0,
        "rating": 4.2,
        "review_count": 340,
        "image_url": "https://m.media-amazon.com/images/I/51wJ5rK0kGL._SX679_.jpg",
        "url_slug": "acer-wireless-mouse-white-blue-zc-a01si-0wc",
        "amazon_link": "https://amzn.in/d/05Fir8bg"
    },
    {
        "asin": "B0FQQMSRP8",
        "title": "Acer Wireless Mouse, Black/Red (ZC.A01SI.3S8)",
        "category": "Wireless & Wired Mice",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.3S8",
        "mrp": 999.0,
        "base_price": 499.0,
        "rating": 4.2,
        "review_count": 340,
        "image_url": "https://m.media-amazon.com/images/I/51wJ5rK0kGL._SX679_.jpg",
        "url_slug": "acer-wireless-mouse-black-red-zc-a01si-3s8",
        "amazon_link": "https://amzn.in/d/0iGTa5NW"
    },
    {
        "asin": "B0FPDKR4GX",
        "title": "Acer Prism Wireless Rechargeable Mouse - Black (ZC.A01SI.2ZQ)",
        "category": "Wireless & Wired Mice",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.2ZQ",
        "mrp": 1499.0,
        "base_price": 799.0,
        "rating": 4.2,
        "review_count": 340,
        "image_url": "https://m.media-amazon.com/images/I/51wJ5rK0kGL._SX679_.jpg",
        "url_slug": "acer-prism-wireless-rechargeable-mouse-black-zc-a0",
        "amazon_link": "https://amzn.in/d/0drqvfM7"
    },
    {
        "asin": "B0GYT9GRFW",
        "title": "Acer Prism Wireless Rechargeable Mouse - Yellow (ZC.A01SI.4R7)",
        "category": "Wireless & Wired Mice",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.4R7",
        "mrp": 1499.0,
        "base_price": 799.0,
        "rating": 4.2,
        "review_count": 340,
        "image_url": "https://m.media-amazon.com/images/I/51wJ5rK0kGL._SX679_.jpg",
        "url_slug": "acer-prism-wireless-rechargeable-mouse-yellow-zc-a",
        "amazon_link": "https://amzn.in/d/02zAZaxY"
    },
    {
        "asin": "B0FPDJYKBX",
        "title": "Acer Prism Wireless Rechargeable Mouse - White (ZC.A01SI.2ZP)",
        "category": "Wireless & Wired Mice",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.2ZP",
        "mrp": 1499.0,
        "base_price": 799.0,
        "rating": 4.2,
        "review_count": 340,
        "image_url": "https://m.media-amazon.com/images/I/51wJ5rK0kGL._SX679_.jpg",
        "url_slug": "acer-prism-wireless-rechargeable-mouse-white-zc-a0",
        "amazon_link": "https://amzn.in/d/0iA8VsbU"
    },
    {
        "asin": "B0FRZ85XH1",
        "title": "Acer Ergo Vertical Wireless Mouse - White (ZC.A01SI.393)",
        "category": "Wireless & Wired Mice",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.393",
        "mrp": 1499.0,
        "base_price": 799.0,
        "rating": 4.2,
        "review_count": 340,
        "image_url": "https://m.media-amazon.com/images/I/51wJ5rK0kGL._SX679_.jpg",
        "url_slug": "acer-ergo-vertical-wireless-mouse-white-zc-a01si-3",
        "amazon_link": "https://amzn.in/d/03p9eVRt"
    },
    {
        "asin": "B0FRZ861L9",
        "title": "Acer Ergo Vertical Wireless Mouse - Grey (ZC.A01SI.394)",
        "category": "Wireless & Wired Mice",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.394",
        "mrp": 1499.0,
        "base_price": 799.0,
        "rating": 4.2,
        "review_count": 340,
        "image_url": "https://m.media-amazon.com/images/I/51wJ5rK0kGL._SX679_.jpg",
        "url_slug": "acer-ergo-vertical-wireless-mouse-grey-zc-a01si-39",
        "amazon_link": "https://amzn.in/d/0byavpY9"
    },
    {
        "asin": "B0FKPCRVCZ",
        "title": "Bubble Mouse Blue/Green (ZC.A01SI.2N0)",
        "category": "Wireless & Wired Mice",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.2N0",
        "mrp": 999.0,
        "base_price": 499.0,
        "rating": 4.2,
        "review_count": 340,
        "image_url": "https://m.media-amazon.com/images/I/51wJ5rK0kGL._SX679_.jpg",
        "url_slug": "bubble-mouse-blue-green-zc-a01si-2n0",
        "amazon_link": "https://amzn.in/d/0dYfjK4d"
    },
    {
        "asin": "B0FKPXG5R8",
        "title": "Bubble Mouse Peach (ZC.A01SI.2N1)",
        "category": "Wireless & Wired Mice",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.2N1",
        "mrp": 999.0,
        "base_price": 499.0,
        "rating": 4.2,
        "review_count": 340,
        "image_url": "https://m.media-amazon.com/images/I/51wJ5rK0kGL._SX679_.jpg",
        "url_slug": "bubble-mouse-peach-zc-a01si-2n1",
        "amazon_link": "https://amzn.in/d/05zCkpwR"
    },
    {
        "asin": "B0FKPNYY9Z",
        "title": "Bubble Mouse White (ZC.A01SI.2MZ)",
        "category": "Wireless & Wired Mice",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.2MZ",
        "mrp": 999.0,
        "base_price": 499.0,
        "rating": 4.2,
        "review_count": 340,
        "image_url": "https://m.media-amazon.com/images/I/51wJ5rK0kGL._SX679_.jpg",
        "url_slug": "bubble-mouse-white-zc-a01si-2mz",
        "amazon_link": "https://amzn.in/d/0iDzqvS3"
    },
    {
        "asin": "B0GQVQF9YQ",
        "title": "PopGo Wireless Mouse | 2.4G + BT5.4 Dual Mode (ZC.A01SI.3ZE)",
        "category": "Wireless & Wired Mice",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.3ZE",
        "mrp": 999.0,
        "base_price": 499.0,
        "rating": 4.2,
        "review_count": 340,
        "image_url": "https://m.media-amazon.com/images/I/51wJ5rK0kGL._SX679_.jpg",
        "url_slug": "popgo-wireless-mouse-2-4g-bt5-4-dual-mode-zc-a01si",
        "amazon_link": "https://amzn.in/d/01DqOKBG"
    },
    {
        "asin": "B0H83FL8CJ",
        "title": "Acer Nitro Phantom X12 Tri-Mode Gaming Mouse (ZC.A01SI.4ND)",
        "category": "Gaming Mice",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.4ND",
        "mrp": 2499.0,
        "base_price": 1499.0,
        "rating": 4.4,
        "review_count": 310,
        "image_url": "https://m.media-amazon.com/images/I/61gR7G8O6UL._SX679_.jpg",
        "url_slug": "acer-nitro-phantom-x12-tri-mode-gaming-mouse-zc-a0",
        "amazon_link": "https://amzn.in/d/0hb3pkuS"
    },
    {
        "asin": "B0H83548VY",
        "title": "Acer Nitro Phantom X7 Wired Gaming Mouse | 7200 DPI (ZC.A01SI.4NE)",
        "category": "Gaming Mice",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.4NE",
        "mrp": 1799.0,
        "base_price": 899.0,
        "rating": 4.4,
        "review_count": 310,
        "image_url": "https://m.media-amazon.com/images/I/61gR7G8O6UL._SX679_.jpg",
        "url_slug": "acer-nitro-phantom-x7-wired-gaming-mouse-7200-dpi-",
        "amazon_link": "https://amzn.in/d/0a2asTCM"
    },
    {
        "asin": "B0G5FM1C7J",
        "title": "Nitro 7 Gaming Mouse (ZC.A01SI.3RX)",
        "category": "Gaming Mice",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.3RX",
        "mrp": 1799.0,
        "base_price": 899.0,
        "rating": 4.4,
        "review_count": 310,
        "image_url": "https://m.media-amazon.com/images/I/61gR7G8O6UL._SX679_.jpg",
        "url_slug": "nitro-7-gaming-mouse-zc-a01si-3rx",
        "amazon_link": "https://amzn.in/d/0iHFtpej"
    },
    {
        "asin": "B0G5FFNPDN",
        "title": "Acer Titan X Gaming Mouse (ZC.A01SI.3RY)",
        "category": "Gaming Mice",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.3RY",
        "mrp": 1799.0,
        "base_price": 899.0,
        "rating": 4.4,
        "review_count": 310,
        "image_url": "https://m.media-amazon.com/images/I/61gR7G8O6UL._SX679_.jpg",
        "url_slug": "acer-titan-x-gaming-mouse-zc-a01si-3ry",
        "amazon_link": "https://amzn.in/d/0cs3yrH9"
    },
    {
        "asin": "B0DP4M69WM",
        "title": "ACER Wireless Rechargeable Keyboard BLACK with GREEN cradle ACR101 (ZC.A01SI.18K)",
        "category": "Keyboards",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.18K",
        "mrp": 1999.0,
        "base_price": 1199.0,
        "rating": 4.2,
        "review_count": 115,
        "image_url": "https://m.media-amazon.com/images/I/61Bq-4O93tL._SX679_.jpg",
        "url_slug": "acer-wireless-rechargeable-keyboard-black-with-gre",
        "amazon_link": "https://amzn.in/d/0dZscBFB"
    },
    {
        "asin": "B0DP1FCHQ9",
        "title": "ACER ClearView Wireless Rechargeable Keyboard SILVER ACR100 (ZC.A01SI.18J)",
        "category": "Keyboards",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.18J",
        "mrp": 1999.0,
        "base_price": 1199.0,
        "rating": 4.2,
        "review_count": 115,
        "image_url": "https://m.media-amazon.com/images/I/61Bq-4O93tL._SX679_.jpg",
        "url_slug": "acer-clearview-wireless-rechargeable-keyboard-silv",
        "amazon_link": "https://amzn.in/d/0db8lr4G"
    },
    {
        "asin": "B0GRJXKCRQ",
        "title": "Acer KeyPro Wireless Dual Mode Keyboard - Space Grey (ZC.A01SI.3ZF)",
        "category": "Keyboards",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.3ZF",
        "mrp": 1999.0,
        "base_price": 1199.0,
        "rating": 4.2,
        "review_count": 115,
        "image_url": "https://m.media-amazon.com/images/I/61Bq-4O93tL._SX679_.jpg",
        "url_slug": "acer-keypro-wireless-dual-mode-keyboard-space-grey",
        "amazon_link": "https://amzn.in/d/0ah5sBet"
    },
    {
        "asin": "B0GRJX27DG",
        "title": "Acer KeyPro Wireless Dual Mode Keyboard - Silver (ZC.A01SI.3ZG)",
        "category": "Keyboards",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.3ZG",
        "mrp": 1999.0,
        "base_price": 1199.0,
        "rating": 4.2,
        "review_count": 115,
        "image_url": "https://m.media-amazon.com/images/I/61Bq-4O93tL._SX679_.jpg",
        "url_slug": "acer-keypro-wireless-dual-mode-keyboard-silver-zc-",
        "amazon_link": "https://amzn.in/d/05dx2Scc"
    },
    {
        "asin": "B0FG94XRNK",
        "title": "ACER Wireless Rechargeable Keyboard BLACK with GREEN cradle and Touchpad (ZC.A01SI.224)",
        "category": "Keyboards",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.224",
        "mrp": 3499.0,
        "base_price": 2299.0,
        "rating": 4.2,
        "review_count": 115,
        "image_url": "https://m.media-amazon.com/images/I/61Bq-4O93tL._SX679_.jpg",
        "url_slug": "acer-wireless-rechargeable-keyboard-black-with-gre",
        "amazon_link": "https://amzn.in/d/04lyF1ax"
    },
    {
        "asin": "B0FG995CZS",
        "title": "Acer Wireless Rechargeable Keyboard with cradle and Numpad - off white colored keys (ZC.A01SI.225)",
        "category": "Keyboards",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.225",
        "mrp": 1999.0,
        "base_price": 1199.0,
        "rating": 4.2,
        "review_count": 115,
        "image_url": "https://m.media-amazon.com/images/I/61Bq-4O93tL._SX679_.jpg",
        "url_slug": "acer-wireless-rechargeable-keyboard-with-cradle-an",
        "amazon_link": "https://amzn.in/d/02knIdjO"
    },
    {
        "asin": "B0F9PLCSKL",
        "title": "Acer Solar Keyboard (ZC.A01SI.1LH)",
        "category": "Keyboards",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.1LH",
        "mrp": 3499.0,
        "base_price": 2299.0,
        "rating": 4.2,
        "review_count": 115,
        "image_url": "https://m.media-amazon.com/images/I/61Bq-4O93tL._SX679_.jpg",
        "url_slug": "acer-solar-keyboard-zc-a01si-1lh",
        "amazon_link": "https://amzn.in/d/0dnY3fzz"
    },
    {
        "asin": "B0H18M1KZ5",
        "title": "Acer SoftKey Pro Wireless Keyboard | 2.4GHz (ZC.A01SI.4VY)",
        "category": "Keyboards",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.4VY",
        "mrp": 1999.0,
        "base_price": 1199.0,
        "rating": 4.2,
        "review_count": 115,
        "image_url": "https://m.media-amazon.com/images/I/61Bq-4O93tL._SX679_.jpg",
        "url_slug": "acer-softkey-pro-wireless-keyboard-2-4ghz-zc-a01si",
        "amazon_link": "https://amzn.in/d/07t1OXTz"
    },
    {
        "asin": "B0FTZXFSH1",
        "title": "Acer Trifold Pro | 60 Keys Foldable (ZC.A01SI.39X)",
        "category": "Keyboards",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.39X",
        "mrp": 3499.0,
        "base_price": 2299.0,
        "rating": 4.2,
        "review_count": 115,
        "image_url": "https://m.media-amazon.com/images/I/61Bq-4O93tL._SX679_.jpg",
        "url_slug": "acer-trifold-pro-60-keys-foldable-zc-a01si-39x",
        "amazon_link": "https://amzn.in/d/0j4CJByc"
    },
    {
        "asin": "B0FTZX7RP8",
        "title": "Acer Fold Max | 99 Keys (ZC.A01SI.39Y)",
        "category": "Keyboards",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.39Y",
        "mrp": 3499.0,
        "base_price": 2299.0,
        "rating": 4.2,
        "review_count": 115,
        "image_url": "https://m.media-amazon.com/images/I/61Bq-4O93tL._SX679_.jpg",
        "url_slug": "acer-fold-max-99-keys-zc-a01si-39y",
        "amazon_link": "https://amzn.in/d/07fZITfY"
    },
    {
        "asin": "B0FTZXX729",
        "title": "Acer Mini Fold | 67 Keys Compact (ZC.A01SI.39Z)",
        "category": "Keyboards",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.39Z",
        "mrp": 3499.0,
        "base_price": 2299.0,
        "rating": 4.2,
        "review_count": 115,
        "image_url": "https://m.media-amazon.com/images/I/61Bq-4O93tL._SX679_.jpg",
        "url_slug": "acer-mini-fold-67-keys-compact-zc-a01si-39z",
        "amazon_link": "https://amzn.in/d/091waa5V"
    },
    {
        "asin": "B0H65TZF1R",
        "title": "Acer NanoPad Touch (Green) (ZC.A01SI.4YV)",
        "category": "Keyboards",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.4YV",
        "mrp": 1999.0,
        "base_price": 1199.0,
        "rating": 4.2,
        "review_count": 115,
        "image_url": "https://m.media-amazon.com/images/I/61Bq-4O93tL._SX679_.jpg",
        "url_slug": "acer-nanopad-touch-green-zc-a01si-4yv",
        "amazon_link": "https://amzn.in/d/0hKaWdc5"
    },
    {
        "asin": "B0H65MQ33D",
        "title": "Acer NanoPad Touch (Peach) (ZC.A01SI.4YU)",
        "category": "Keyboards",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.4YU",
        "mrp": 1999.0,
        "base_price": 1199.0,
        "rating": 4.2,
        "review_count": 115,
        "image_url": "https://m.media-amazon.com/images/I/61Bq-4O93tL._SX679_.jpg",
        "url_slug": "acer-nanopad-touch-peach-zc-a01si-4yu",
        "amazon_link": "https://amzn.in/d/0h1ZTet3"
    },
    {
        "asin": "B0D8354479",
        "title": "Acer Wireless KBD Mouse White Gray Combo (ZC.A01SI.0WD)",
        "category": "Keyboard & Mouse Combos",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.0WD",
        "mrp": 2999.0,
        "base_price": 1699.0,
        "rating": 4.1,
        "review_count": 220,
        "image_url": "https://m.media-amazon.com/images/I/61vjG9-T3fL._SX679_.jpg",
        "url_slug": "acer-wireless-kbd-mouse-white-gray-combo-zc-a01si-",
        "amazon_link": "https://amzn.in/d/05wObS7l"
    },
    {
        "asin": "B0F9LN35XH",
        "title": "Acer Fusion Wireless KBD Mouse Black Silver COMBO (ZC.A01SI.204)",
        "category": "Keyboard & Mouse Combos",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.204",
        "mrp": 2999.0,
        "base_price": 1699.0,
        "rating": 4.1,
        "review_count": 220,
        "image_url": "https://m.media-amazon.com/images/I/61vjG9-T3fL._SX679_.jpg",
        "url_slug": "acer-fusion-wireless-kbd-mouse-black-silver-combo-",
        "amazon_link": "https://amzn.in/d/00oXwCPx"
    },
    {
        "asin": "B0FCS5V5V1",
        "title": "Acer PalmEase Wired Keyboard & Mouse Combo with Palm Rest (ZC.A01SI.2DQ)",
        "category": "Keyboard & Mouse Combos",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.2DQ",
        "mrp": 2999.0,
        "base_price": 1699.0,
        "rating": 4.1,
        "review_count": 220,
        "image_url": "https://m.media-amazon.com/images/I/61vjG9-T3fL._SX679_.jpg",
        "url_slug": "acer-palmease-wired-keyboard-mouse-combo-with-palm",
        "amazon_link": "https://amzn.in/d/0cvhC7Ds"
    },
    {
        "asin": "B0GTG3VHZW",
        "title": "Acer OfficeMate Wired Keyboard Mouse Combo-Black (ZC.A01SI.4JA)",
        "category": "Keyboard & Mouse Combos",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.4JA",
        "mrp": 1999.0,
        "base_price": 1099.0,
        "rating": 4.1,
        "review_count": 220,
        "image_url": "https://m.media-amazon.com/images/I/61vjG9-T3fL._SX679_.jpg",
        "url_slug": "acer-officemate-wired-keyboard-mouse-combo-black-z",
        "amazon_link": "https://amzn.in/d/0fvxtU2O"
    },
    {
        "asin": "B0GTG3X6FF",
        "title": "Acer OfficeMate Wired Keyboard Mouse Combo-White (ZC.A01SI.4JB)",
        "category": "Keyboard & Mouse Combos",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.4JB",
        "mrp": 1999.0,
        "base_price": 1099.0,
        "rating": 4.1,
        "review_count": 220,
        "image_url": "https://m.media-amazon.com/images/I/61vjG9-T3fL._SX679_.jpg",
        "url_slug": "acer-officemate-wired-keyboard-mouse-combo-white-z",
        "amazon_link": "https://amzn.in/d/0d0nItAm"
    },
    {
        "asin": "B0FCSFT4VX",
        "title": "Acer PalmEase Wireless Keyboard & Mouse Combo with Palm Rest-Black (ZC.A01SI.2DP)",
        "category": "Keyboard & Mouse Combos",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.2DP",
        "mrp": 2999.0,
        "base_price": 1699.0,
        "rating": 4.1,
        "review_count": 220,
        "image_url": "https://m.media-amazon.com/images/I/61vjG9-T3fL._SX679_.jpg",
        "url_slug": "acer-palmease-wireless-keyboard-mouse-combo-with-p",
        "amazon_link": "https://amzn.in/d/0bPFvu98"
    },
    {
        "asin": "B0GJTT63ML",
        "title": "Acer PalmEase Wireless Keyboard & Mouse Combo with Palm Rest-White (ZC.A01SI.313)",
        "category": "Keyboard & Mouse Combos",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.313",
        "mrp": 2999.0,
        "base_price": 1699.0,
        "rating": 4.1,
        "review_count": 220,
        "image_url": "https://m.media-amazon.com/images/I/61vjG9-T3fL._SX679_.jpg",
        "url_slug": "acer-palmease-wireless-keyboard-mouse-combo-with-p",
        "amazon_link": "https://amzn.in/d/028vmivd"
    },
    {
        "asin": "B0FFN8C3KW",
        "title": "Acer Nano Pad COMBO - Black (ZC.A01SI.223)",
        "category": "Keyboard & Mouse Combos",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.223",
        "mrp": 1999.0,
        "base_price": 1099.0,
        "rating": 4.1,
        "review_count": 220,
        "image_url": "https://m.media-amazon.com/images/I/61vjG9-T3fL._SX679_.jpg",
        "url_slug": "acer-nano-pad-combo-black-zc-a01si-223",
        "amazon_link": "https://amzn.in/d/0e0IBHGC"
    },
    {
        "asin": "B0FTTH71SY",
        "title": "Acer Nano Pad COMBO - Purple (ZC.A01SI.3BH)",
        "category": "Keyboard & Mouse Combos",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.3BH",
        "mrp": 1999.0,
        "base_price": 1099.0,
        "rating": 4.1,
        "review_count": 220,
        "image_url": "https://m.media-amazon.com/images/I/61vjG9-T3fL._SX679_.jpg",
        "url_slug": "acer-nano-pad-combo-purple-zc-a01si-3bh",
        "amazon_link": "https://amzn.in/d/0iKvJyBx"
    },
    {
        "asin": "B0G4DCBM4D",
        "title": "Acer ZenKeys Duos - Black/Lime (ZC.A01SI.3R2)",
        "category": "Keyboard & Mouse Combos",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.3R2",
        "mrp": 1999.0,
        "base_price": 1099.0,
        "rating": 4.1,
        "review_count": 220,
        "image_url": "https://m.media-amazon.com/images/I/61vjG9-T3fL._SX679_.jpg",
        "url_slug": "acer-zenkeys-duos-black-lime-zc-a01si-3r2",
        "amazon_link": "https://amzn.in/d/0fVcwg3C"
    },
    {
        "asin": "B0G4DJQMXK",
        "title": "Acer ZenKeys Duos - White/Blue (ZC.A01SI.3R3)",
        "category": "Keyboard & Mouse Combos",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.3R3",
        "mrp": 1999.0,
        "base_price": 1099.0,
        "rating": 4.1,
        "review_count": 220,
        "image_url": "https://m.media-amazon.com/images/I/61vjG9-T3fL._SX679_.jpg",
        "url_slug": "acer-zenkeys-duos-white-blue-zc-a01si-3r3",
        "amazon_link": "https://amzn.in/d/00Sw1xzi"
    },
    {
        "asin": "B0H8M56QXM",
        "title": "Acer OfficeLite KM 300 WL COMBO Black -DY (ZC.A01SI.4VM)",
        "category": "Keyboard & Mouse Combos",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.4VM",
        "mrp": 1999.0,
        "base_price": 1099.0,
        "rating": 4.1,
        "review_count": 220,
        "image_url": "https://m.media-amazon.com/images/I/61vjG9-T3fL._SX679_.jpg",
        "url_slug": "acer-officelite-km-300-wl-combo-black-dy-zc-a01si-",
        "amazon_link": "https://amzn.in/d/0e1xb7cm"
    },
    {
        "asin": "B0H8M8SF2R",
        "title": "Acer OfficeLite KM 300 WL COMBO White & Grey -DY (ZC.A01SI.4VN)",
        "category": "Keyboard & Mouse Combos",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.4VN",
        "mrp": 1999.0,
        "base_price": 1099.0,
        "rating": 4.1,
        "review_count": 220,
        "image_url": "https://m.media-amazon.com/images/I/61vjG9-T3fL._SX679_.jpg",
        "url_slug": "acer-officelite-km-300-wl-combo-white-grey-dy-zc-a",
        "amazon_link": "https://amzn.in/d/00A3nlLp"
    },
    {
        "asin": "B0GK2L7DW7",
        "title": "Acer RedShift Wireless Keyboard & Mouse Combo (ZC.A01SI.3U0)",
        "category": "Keyboard & Mouse Combos",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.3U0",
        "mrp": 2999.0,
        "base_price": 1699.0,
        "rating": 4.1,
        "review_count": 220,
        "image_url": "https://m.media-amazon.com/images/I/61vjG9-T3fL._SX679_.jpg",
        "url_slug": "acer-redshift-wireless-keyboard-mouse-combo-zc-a01",
        "amazon_link": "https://amzn.in/d/06sEKkEz"
    },
    {
        "asin": "B0DVGSLGB7",
        "title": "Acer Cuteo Keyboard Mouse COMBO - Pink (ZC.A01SI.18N)",
        "category": "Keyboard & Mouse Combos",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.18N",
        "mrp": 1999.0,
        "base_price": 1099.0,
        "rating": 4.1,
        "review_count": 220,
        "image_url": "https://m.media-amazon.com/images/I/61vjG9-T3fL._SX679_.jpg",
        "url_slug": "acer-cuteo-keyboard-mouse-combo-pink-zc-a01si-18n",
        "amazon_link": "https://amzn.in/d/03s6F5mt"
    },
    {
        "asin": "B0H66952HK",
        "title": "Acer PopGo Wireless COMBO - Beige (ZC.A01SI.4YN)",
        "category": "Keyboard & Mouse Combos",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.4YN",
        "mrp": 2999.0,
        "base_price": 1699.0,
        "rating": 4.1,
        "review_count": 220,
        "image_url": "https://m.media-amazon.com/images/I/61vjG9-T3fL._SX679_.jpg",
        "url_slug": "acer-popgo-wireless-combo-beige-zc-a01si-4yn",
        "amazon_link": "https://amzn.in/d/0ecovzK7"
    },
    {
        "asin": "B0H6628VLR",
        "title": "Acer PopGo Wireless COMBO - Purple (ZC.A01SI.4YP)",
        "category": "Keyboard & Mouse Combos",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.4YP",
        "mrp": 2999.0,
        "base_price": 1699.0,
        "rating": 4.1,
        "review_count": 220,
        "image_url": "https://m.media-amazon.com/images/I/61vjG9-T3fL._SX679_.jpg",
        "url_slug": "acer-popgo-wireless-combo-purple-zc-a01si-4yp",
        "amazon_link": "https://amzn.in/d/014JfY3b"
    },
    {
        "asin": "B0DT9TMYHW",
        "title": "Acer ALG 4 in 1 COMBO (ZC.A01SI.1LG)",
        "category": "Keyboard & Mouse Combos",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.1LG",
        "mrp": 2999.0,
        "base_price": 1699.0,
        "rating": 4.1,
        "review_count": 220,
        "image_url": "https://m.media-amazon.com/images/I/61vjG9-T3fL._SX679_.jpg",
        "url_slug": "acer-alg-4-in-1-combo-zc-a01si-1lg",
        "amazon_link": "https://amzn.in/d/0dd5h6uG"
    },
    {
        "asin": "B0D8YCXLRD",
        "title": "Predator Aethon 303 (GP.KBD11.048)",
        "category": "Gaming Keyboards",
        "product_group": "other_products",
        "part_no": "GP.KBD11.048",
        "mrp": 4499.0,
        "base_price": 2799.0,
        "rating": 4.3,
        "review_count": 145,
        "image_url": "https://m.media-amazon.com/images/I/71rQ6W9Z5fL._SX679_.jpg",
        "url_slug": "predator-aethon-303-gp-kbd11-048",
        "amazon_link": "https://amzn.in/d/02h2iZTD"
    },
    {
        "asin": "B0DNFL4C1R",
        "title": "Predator Aethon 330 (GP.KBD11.04A)",
        "category": "Gaming Keyboards",
        "product_group": "other_products",
        "part_no": "GP.KBD11.04A",
        "mrp": 5999.0,
        "base_price": 3999.0,
        "rating": 4.3,
        "review_count": 145,
        "image_url": "https://m.media-amazon.com/images/I/71rQ6W9Z5fL._SX679_.jpg",
        "url_slug": "predator-aethon-330-gp-kbd11-04a",
        "amazon_link": "https://amzn.in/d/053R055F"
    },
    {
        "asin": "B0G61CFR13",
        "title": "acer Nitro G Wired Mechanical Gaming Keyboard (ZC.A01SI.3RW)",
        "category": "Gaming Keyboards",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.3RW",
        "mrp": 5999.0,
        "base_price": 3999.0,
        "rating": 4.3,
        "review_count": 145,
        "image_url": "https://m.media-amazon.com/images/I/71rQ6W9Z5fL._SX679_.jpg",
        "url_slug": "acer-nitro-g-wired-mechanical-gaming-keyboard-zc-a",
        "amazon_link": "https://amzn.in/d/0awRxZWI"
    },
    {
        "asin": "B07H5R7K2M",
        "title": "Nitro Wired Gaming Headset (NP.HDS1A.008)",
        "category": "Audio & Headsets",
        "product_group": "other_products",
        "part_no": "NP.HDS1A.008",
        "mrp": 2999.0,
        "base_price": 1699.0,
        "rating": 4.2,
        "review_count": 190,
        "image_url": "https://m.media-amazon.com/images/I/61H3lR-3sTL._SX679_.jpg",
        "url_slug": "nitro-wired-gaming-headset-np-hds1a-008",
        "amazon_link": "https://amzn.in/d/032kanBK"
    },
    {
        "asin": "B0FTVYCWZ8",
        "title": "Nitro Wired Gaming Headset (ZC.A01SI.395)",
        "category": "Audio & Headsets",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.395",
        "mrp": 2999.0,
        "base_price": 1699.0,
        "rating": 4.2,
        "review_count": 190,
        "image_url": "https://m.media-amazon.com/images/I/61H3lR-3sTL._SX679_.jpg",
        "url_slug": "nitro-wired-gaming-headset-zc-a01si-395",
        "amazon_link": "https://amzn.in/d/0anrVGEF"
    },
    {
        "asin": "B0FR4KJ6NT",
        "title": "Nitro Wireless 4 in 1 Headset, 7.1 Surround (ZC.A01SI.396)",
        "category": "Audio & Headsets",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.396",
        "mrp": 4999.0,
        "base_price": 3299.0,
        "rating": 4.2,
        "review_count": 190,
        "image_url": "https://m.media-amazon.com/images/I/61H3lR-3sTL._SX679_.jpg",
        "url_slug": "nitro-wireless-4-in-1-headset-7-1-surround-zc-a01s",
        "amazon_link": "https://amzn.in/d/01GLG4A7"
    },
    {
        "asin": "B0H6629LXR",
        "title": "Nitro Phatom Headset (ZC.A01SI.4YR)",
        "category": "Audio & Headsets",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.4YR",
        "mrp": 2999.0,
        "base_price": 1699.0,
        "rating": 4.2,
        "review_count": 190,
        "image_url": "https://m.media-amazon.com/images/I/61H3lR-3sTL._SX679_.jpg",
        "url_slug": "nitro-phatom-headset-zc-a01si-4yr",
        "amazon_link": "https://amzn.in/d/05gaWPCq"
    },
    {
        "asin": "B0GKHYTGB3",
        "title": "Dreamwave Speaker (ZC.A01SI.3LG)",
        "category": "Audio & Headsets",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.3LG",
        "mrp": 3499.0,
        "base_price": 2199.0,
        "rating": 4.2,
        "review_count": 68,
        "image_url": "https://m.media-amazon.com/images/I/61kY8O8m4xL._SX679_.jpg",
        "url_slug": "dreamwave-speaker-zc-a01si-3lg",
        "amazon_link": "https://amzn.in/d/0gaJ0c9Q"
    },
    {
        "asin": "B0FZX217Q9",
        "title": "New Predator Backpack (ZC.A01SI.3BU)",
        "category": "Backpacks & Sleeves",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.3BU",
        "mrp": 3999.0,
        "base_price": 2499.0,
        "rating": 4.5,
        "review_count": 210,
        "image_url": "https://m.media-amazon.com/images/I/71uK+b-jMlL._SX679_.jpg",
        "url_slug": "new-predator-backpack-zc-a01si-3bu",
        "amazon_link": "https://amzn.in/d/04v36OgI"
    },
    {
        "asin": "B002EWQY5W",
        "title": "Acer Estilo Beige (ZC.A01SI.1B7)",
        "category": "Backpacks & Sleeves",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.1B7",
        "mrp": 2499.0,
        "base_price": 1299.0,
        "rating": 4.4,
        "review_count": 280,
        "image_url": "https://m.media-amazon.com/images/I/71uK+b-jMlL._SX679_.jpg",
        "url_slug": "acer-estilo-beige-zc-a01si-1b7",
        "amazon_link": "https://amzn.in/d/05L9cSW5"
    },
    {
        "asin": "B0FSSTD2VS",
        "title": "Acer Estilo Black (ZC.A01SI.3FJ)",
        "category": "Backpacks & Sleeves",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.3FJ",
        "mrp": 2499.0,
        "base_price": 1299.0,
        "rating": 4.4,
        "review_count": 280,
        "image_url": "https://m.media-amazon.com/images/I/71uK+b-jMlL._SX679_.jpg",
        "url_slug": "acer-estilo-black-zc-a01si-3fj",
        "amazon_link": "https://amzn.in/d/0bcvRtma"
    },
    {
        "asin": "B0DLB6QBH8",
        "title": "Acer Sling Bag Green (ZC.A01SI.1B5)",
        "category": "Backpacks & Sleeves",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.1B5",
        "mrp": 2499.0,
        "base_price": 1299.0,
        "rating": 4.4,
        "review_count": 280,
        "image_url": "https://m.media-amazon.com/images/I/71uK+b-jMlL._SX679_.jpg",
        "url_slug": "acer-sling-bag-green-zc-a01si-1b5",
        "amazon_link": "https://amzn.in/d/02hunQ83"
    },
    {
        "asin": "B008N4JKEC",
        "title": "Acer Sling Bag Grey (ZC.A01SI.1B6)",
        "category": "Backpacks & Sleeves",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.1B6",
        "mrp": 2499.0,
        "base_price": 1299.0,
        "rating": 4.4,
        "review_count": 280,
        "image_url": "https://m.media-amazon.com/images/I/71uK+b-jMlL._SX679_.jpg",
        "url_slug": "acer-sling-bag-grey-zc-a01si-1b6",
        "amazon_link": "https://amzn.in/d/07NNp9EU"
    },
    {
        "asin": "B0FWYRSPNB",
        "title": "Acer Sling Bag Black (ZC.A01SI.3LA)",
        "category": "Backpacks & Sleeves",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.3LA",
        "mrp": 2499.0,
        "base_price": 1299.0,
        "rating": 4.4,
        "review_count": 280,
        "image_url": "https://m.media-amazon.com/images/I/71uK+b-jMlL._SX679_.jpg",
        "url_slug": "acer-sling-bag-black-zc-a01si-3la",
        "amazon_link": "https://amzn.in/d/0736fmpt"
    },
    {
        "asin": "B0GKC55B4H",
        "title": "Acer ChargeMate 4-in-1 Wireless Charging Laptop Sleeve - Grey (ZC.A01SI.3LJ)",
        "category": "Backpacks & Sleeves",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.3LJ",
        "mrp": 3999.0,
        "base_price": 2299.0,
        "rating": 4.4,
        "review_count": 280,
        "image_url": "https://m.media-amazon.com/images/I/71uK+b-jMlL._SX679_.jpg",
        "url_slug": "acer-chargemate-4-in-1-wireless-charging-laptop-sl",
        "amazon_link": "https://amzn.in/d/0ih18G5u"
    },
    {
        "asin": "B0GKBXTL5S",
        "title": "Acer ChargeMate 4-in-1 Wireless Charging Laptop Sleeve - Black (ZC.A01SI.3LK)",
        "category": "Backpacks & Sleeves",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.3LK",
        "mrp": 3999.0,
        "base_price": 2299.0,
        "rating": 4.4,
        "review_count": 280,
        "image_url": "https://m.media-amazon.com/images/I/71uK+b-jMlL._SX679_.jpg",
        "url_slug": "acer-chargemate-4-in-1-wireless-charging-laptop-sl",
        "amazon_link": "https://amzn.in/d/0ii9l0h2"
    },
    {
        "asin": "B0FX5HWSWD",
        "title": "Acer Cross Body Bag (ZC.A01SI.3HB)",
        "category": "Backpacks & Sleeves",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.3HB",
        "mrp": 2499.0,
        "base_price": 1299.0,
        "rating": 4.4,
        "review_count": 280,
        "image_url": "https://m.media-amazon.com/images/I/71uK+b-jMlL._SX679_.jpg",
        "url_slug": "acer-cross-body-bag-zc-a01si-3hb",
        "amazon_link": "https://amzn.in/d/0acVoJ1E"
    },
    {
        "asin": "B0FXV4PWJ9",
        "title": "Acer UrbanLite Slim (ZC.A01SI.3BV)",
        "category": "Backpacks & Sleeves",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.3BV",
        "mrp": 2499.0,
        "base_price": 1299.0,
        "rating": 4.4,
        "review_count": 280,
        "image_url": "https://m.media-amazon.com/images/I/71uK+b-jMlL._SX679_.jpg",
        "url_slug": "acer-urbanlite-slim-zc-a01si-3bv",
        "amazon_link": "https://amzn.in/d/029BJiPl"
    },
    {
        "asin": "B0F6V5YMKJ",
        "title": "Acer Pulse Backpack Yellow/Navy blue (ZC.A01SI.21X)",
        "category": "Backpacks & Sleeves",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.21X",
        "mrp": 2499.0,
        "base_price": 1299.0,
        "rating": 4.4,
        "review_count": 280,
        "image_url": "https://m.media-amazon.com/images/I/71uK+b-jMlL._SX679_.jpg",
        "url_slug": "acer-pulse-backpack-yellow-navy-blue-zc-a01si-21x",
        "amazon_link": "https://amzn.in/d/09VAgml9"
    },
    {
        "asin": "B0F6VGF7K1",
        "title": "Acer Pulse Backpack Silver/Navy blue (ZC.A01SI.21Y)",
        "category": "Backpacks & Sleeves",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.21Y",
        "mrp": 2499.0,
        "base_price": 1299.0,
        "rating": 4.4,
        "review_count": 280,
        "image_url": "https://m.media-amazon.com/images/I/71uK+b-jMlL._SX679_.jpg",
        "url_slug": "acer-pulse-backpack-silver-navy-blue-zc-a01si-21y",
        "amazon_link": "https://amzn.in/d/07a22lJr"
    },
    {
        "asin": "B0G1CX438C",
        "title": "Acer Pulse Backpack Black / Maroon (ZC.A01SI.3VP)",
        "category": "Backpacks & Sleeves",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.3VP",
        "mrp": 2499.0,
        "base_price": 1299.0,
        "rating": 4.4,
        "review_count": 280,
        "image_url": "https://m.media-amazon.com/images/I/71uK+b-jMlL._SX679_.jpg",
        "url_slug": "acer-pulse-backpack-black-maroon-zc-a01si-3vp",
        "amazon_link": "https://amzn.in/d/0anqBsVY"
    },
    {
        "asin": "B0F3TJZ9JG",
        "title": "Acer Swift 2 in one Convertible Backpack ( Navy Blue) (ZC.A01SI.1KE)",
        "category": "Backpacks & Sleeves",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.1KE",
        "mrp": 2499.0,
        "base_price": 1299.0,
        "rating": 4.4,
        "review_count": 280,
        "image_url": "https://m.media-amazon.com/images/I/71uK+b-jMlL._SX679_.jpg",
        "url_slug": "acer-swift-2-in-one-convertible-backpack-navy-blue",
        "amazon_link": "https://amzn.in/d/0hVfDqZG"
    },
    {
        "asin": "B0F3TQ9655",
        "title": "Acer Swift 2 in one Convertible Backpack (TAN) (ZC.A01SI.1KF)",
        "category": "Backpacks & Sleeves",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.1KF",
        "mrp": 2499.0,
        "base_price": 1299.0,
        "rating": 4.4,
        "review_count": 280,
        "image_url": "https://m.media-amazon.com/images/I/71uK+b-jMlL._SX679_.jpg",
        "url_slug": "acer-swift-2-in-one-convertible-backpack-tan-zc-a0",
        "amazon_link": "https://amzn.in/d/0dHU9YZv"
    },
    {
        "asin": "B0FGQ2QD59",
        "title": "Acer Premium Business Laptop Backpack (ZC.A01SI.1QP)",
        "category": "Backpacks & Sleeves",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.1QP",
        "mrp": 3999.0,
        "base_price": 2299.0,
        "rating": 4.4,
        "review_count": 280,
        "image_url": "https://m.media-amazon.com/images/I/71uK+b-jMlL._SX679_.jpg",
        "url_slug": "acer-premium-business-laptop-backpack-zc-a01si-1qp",
        "amazon_link": "https://amzn.in/d/0iNKWFIP"
    },
    {
        "asin": "B0FGPTK1N8",
        "title": "Acer Premium Professional Laptop Backpack (ZC.A01SI.1QQ)",
        "category": "Backpacks & Sleeves",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.1QQ",
        "mrp": 2499.0,
        "base_price": 1299.0,
        "rating": 4.4,
        "review_count": 280,
        "image_url": "https://m.media-amazon.com/images/I/71uK+b-jMlL._SX679_.jpg",
        "url_slug": "acer-premium-professional-laptop-backpack-zc-a01si",
        "amazon_link": "https://amzn.in/d/0bibRtB8"
    },
    {
        "asin": "B0GRSB3DNX",
        "title": "Acer VacuPack Backpack (ZC.A01SI.4MB)",
        "category": "Backpacks & Sleeves",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.4MB",
        "mrp": 3999.0,
        "base_price": 2299.0,
        "rating": 4.4,
        "review_count": 280,
        "image_url": "https://m.media-amazon.com/images/I/71uK+b-jMlL._SX679_.jpg",
        "url_slug": "acer-vacupack-backpack-zc-a01si-4mb",
        "amazon_link": "https://amzn.in/d/0j5fMhx6"
    },
    {
        "asin": "B0FDKXG11W",
        "title": "Management Power Strip (ZC.A01SI.2P1)",
        "category": "Power & Cable Management",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.2P1",
        "mrp": 1499.0,
        "base_price": 799.0,
        "rating": 4.3,
        "review_count": 150,
        "image_url": "https://m.media-amazon.com/images/I/61+9F1z-uKL._SX679_.jpg",
        "url_slug": "management-power-strip-zc-a01si-2p1",
        "amazon_link": "https://amzn.in/d/0epw1kGk"
    },
    {
        "asin": "B0FDKWY2TS",
        "title": "Wifi Smart Power Strip (ZC.A01SI.2P2)",
        "category": "Power & Cable Management",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.2P2",
        "mrp": 2499.0,
        "base_price": 1499.0,
        "rating": 4.3,
        "review_count": 150,
        "image_url": "https://m.media-amazon.com/images/I/61+9F1z-uKL._SX679_.jpg",
        "url_slug": "wifi-smart-power-strip-zc-a01si-2p2",
        "amazon_link": "https://amzn.in/d/00SX8Ctx"
    },
    {
        "asin": "B0FDKXXQHH",
        "title": "Tower Extension (ZC.A01SI.2P3)",
        "category": "Power & Cable Management",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.2P3",
        "mrp": 2499.0,
        "base_price": 1499.0,
        "rating": 4.3,
        "review_count": 150,
        "image_url": "https://m.media-amazon.com/images/I/61+9F1z-uKL._SX679_.jpg",
        "url_slug": "tower-extension-zc-a01si-2p3",
        "amazon_link": "https://amzn.in/d/0h32ZOIv"
    },
    {
        "asin": "B0FDKYVCPP",
        "title": "Tubo GaN Strip (ZC.A01SI.2P4)",
        "category": "Power & Cable Management",
        "product_group": "other_products",
        "part_no": "ZC.A01SI.2P4",
        "mrp": 2499.0,
        "base_price": 1499.0,
        "rating": 4.3,
        "review_count": 150,
        "image_url": "https://m.media-amazon.com/images/I/61+9F1z-uKL._SX679_.jpg",
        "url_slug": "tubo-gan-strip-zc-a01si-2p4",
        "amazon_link": "https://amzn.in/d/04WN2Fzz"
    }
]

# Combined verified seed catalog (Total 90 items)
ACER_SEED_PRODUCTS = ACER_MONITOR_SEED_PRODUCTS + OTHER_SEED_PRODUCTS
